/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <Snapchat/SCAddFriendButtonV2Delegate.h>

@protocol AddFriendByNameCellDelegate;
@class UILabel, SCAddFriendButtonV2, MASConstraint, NSString, UIButton, UIFont, UIActivityIndicatorView, UIView;

@interface AddFriendByNameCell : UITableViewCell <SCAddFriendButtonV2Delegate> {

	UILabel* _mainLabel;
	UILabel* _subLabel;
	SCAddFriendButtonV2* _addFriendButtonV2;
	MASConstraint* _buttonRightOffsetConstraint;
	BOOL _needsBottomBorder;
	BOOL _isLongText;
	id<AddFriendByNameCellDelegate> _delegate;
	NSString* _username;
	NSString* _mainLabelText;
	NSString* _subLabelText;
	UIButton* _addFriendButton;
	UIFont* _oldFont;
	UIActivityIndicatorView* _loadingIndicator;
	UIView* _bottomBorder;

}

@property (nonatomic,retain) UIButton * addFriendButton;                                   //@synthesize addFriendButton=_addFriendButton - In the implementation block
@property (assign,nonatomic) BOOL isLongText;                                              //@synthesize isLongText=_isLongText - In the implementation block
@property (nonatomic,retain) UIFont * oldFont;                                             //@synthesize oldFont=_oldFont - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView * loadingIndicator;                   //@synthesize loadingIndicator=_loadingIndicator - In the implementation block
@property (nonatomic,retain) UIView * bottomBorder;                                        //@synthesize bottomBorder=_bottomBorder - In the implementation block
@property (assign,nonatomic,__weak) id<AddFriendByNameCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * username;                                            //@synthesize username=_username - In the implementation block
@property (assign,nonatomic) BOOL needsBottomBorder;                                       //@synthesize needsBottomBorder=_needsBottomBorder - In the implementation block
@property (nonatomic,copy) NSString * mainLabelText;                                       //@synthesize mainLabelText=_mainLabelText - In the implementation block
@property (nonatomic,copy) NSString * subLabelText;                                        //@synthesize subLabelText=_subLabelText - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setMainLabel:(id)arg1 subLabel:(id)arg2 isLoading:(BOOL)arg3 usernameExists:(BOOL)arg4 alreadyAdded:(BOOL)arg5 ;
-(void)setAddFriendButton:(UIButton *)arg1 ;
-(UIButton *)addFriendButton;
-(void)addFriendPressed;
-(void)setOldFont:(UIFont *)arg1 ;
-(BOOL)isLongText;
-(void)setIsLongText:(BOOL)arg1 ;
-(UIFont *)oldFont;
-(void)buttonV2Pressed:(id)arg1 friend:(id)arg2 ;
-(NSString *)mainLabelText;
-(NSString *)subLabelText;
-(void)updateButtonV2WithFriend:(id)arg1 buttonState:(long long)arg2 ;
-(void)setInvalidUsername:(id)arg1 ;
-(void)setBlockedForUsername:(id)arg1 ;
-(BOOL)pointInsideAddFriendButton:(CGPoint)arg1 ;
-(void)updateRightOffsetWithIsShowingTableIndex:(BOOL)arg1 ;
-(void)setMainLabelText:(NSString *)arg1 ;
-(void)setSubLabelText:(NSString *)arg1 ;
-(void)setDelegate:(id<AddFriendByNameCellDelegate>)arg1 ;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(id<AddFriendByNameCellDelegate>)delegate;
-(void)updateConstraints;
-(void)setUsername:(NSString *)arg1 ;
-(NSString *)username;
-(void)setLoadingIndicator:(UIActivityIndicatorView *)arg1 ;
-(UIActivityIndicatorView *)loadingIndicator;
-(UIView *)bottomBorder;
-(void)setBottomBorder:(UIView *)arg1 ;
-(void)setNeedsBottomBorder:(BOOL)arg1 ;
-(BOOL)needsBottomBorder;
@end

