/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:44 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NSObject;
@class NSString;

@interface ANSActivity : NSObject {

	id<NSObject> _processInfoToken;
	unsigned long long _options;
	NSString* _reason;
	unsigned long long _backgroundTaskIdentifier;

}

@property (nonatomic,retain) id<NSObject> processInfoToken;                            //@synthesize processInfoToken=_processInfoToken - In the implementation block
@property (assign,nonatomic) unsigned long long backgroundTaskIdentifier;              //@synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier - In the implementation block
@property (nonatomic,readonly) unsigned long long options;                             //@synthesize options=_options - In the implementation block
@property (nonatomic,readonly) NSString * reason;                                      //@synthesize reason=_reason - In the implementation block
+(id)beginActivity:(id)arg1 withOptions:(unsigned long long)arg2 ;
+(id)beginActivityIfAvailable:(id)arg1 options:(unsigned long long)arg2 ;
+(id)beginActivity:(id)arg1 withOptions:(unsigned long long)arg2 expirationHandler:(/*^block*/id)arg3 ;
+(void)performActivity:(id)arg1 options:(unsigned long long)arg2 withBlock:(/*^block*/id)arg3 ;
-(id)initWithProcessToken:(id)arg1 options:(unsigned long long)arg2 reason:(id)arg3 backgroundTaskIdentifier:(unsigned long long)arg4 ;
-(BOOL)supportsBackgroundTasks;
-(id)sharedAppInstance;
-(void)endAndInvalidateBackgroundTask;
-(void)endAndInvalidateInternalActivity;
-(id<NSObject>)processInfoToken;
-(void)setProcessInfoToken:(id<NSObject>)arg1 ;
-(void)dealloc;
-(unsigned long long)beginBackgroundTaskWithName:(id)arg1 expirationHandler:(/*^block*/id)arg2 ;
-(void)end;
-(unsigned long long)options;
-(NSString *)reason;
-(void)setBackgroundTaskIdentifier:(unsigned long long)arg1 ;
-(unsigned long long)backgroundTaskIdentifier;
@end

