/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:44 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate, NSString, NSDictionary;

@interface ANSEvent : NSObject {

	NSDate* _timestamp;
	NSString* _identifier;

}

@property (nonatomic,readonly) NSString * name; 
@property (nonatomic,readonly) NSDate * timestamp;                                   //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) NSString * identifier;                                //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
@property (nonatomic,readonly) BOOL triggersFlush; 
-(BOOL)triggersFlush;
-(id)init;
-(NSDate *)timestamp;
-(NSString *)name;
-(NSString *)identifier;
-(NSDictionary *)dictionaryRepresentation;
@end

