/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface BTUICardExpiryFormat : NSObject {

	BOOL _backspace;
	NSString* _value;
	unsigned long long _cursorLocation;

}

@property (nonatomic,copy) NSString * value;                                 //@synthesize value=_value - In the implementation block
@property (assign,nonatomic) unsigned long long cursorLocation;              //@synthesize cursorLocation=_cursorLocation - In the implementation block
@property (assign,nonatomic) BOOL backspace;                                 //@synthesize backspace=_backspace - In the implementation block
-(BOOL)backspace;
-(void)formattedValue:(id*)arg1 cursorLocation:(unsigned long long*)arg2 ;
-(NSString *)value;
-(void)setValue:(NSString *)arg1 ;
-(void)setCursorLocation:(unsigned long long)arg1 ;
-(void)setBackspace:(BOOL)arg1 ;
-(unsigned long long)cursorLocation;
@end

