/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <Snapchat/Subview.h>

@protocol ContactsLoadingViewControllerDelegate;
@class NSString, UIButton, UILabel, UIView, DancingGhostImageView;

@interface ContactsLoadingViewController : UIViewController <Subview> {

	NSString* _loadingText;
	id<ContactsLoadingViewControllerDelegate> _delegate;
	UIButton* _allowAccessButton;
	UILabel* _allowAccessLabel;
	UIView* _backgrondGhostView;
	UILabel* _couldNotAccessContactsLabel;
	DancingGhostImageView* _dancingGhostImageView;
	UIButton* _loadingFailedButton;
	UILabel* _loadingFailedLabel;
	UILabel* _loadingLabel;
	UILabel* _noContactsLabel;

}

@property (nonatomic,retain) UIButton * allowAccessButton;                                           //@synthesize allowAccessButton=_allowAccessButton - In the implementation block
@property (nonatomic,retain) UILabel * allowAccessLabel;                                             //@synthesize allowAccessLabel=_allowAccessLabel - In the implementation block
@property (nonatomic,retain) UIView * backgrondGhostView;                                            //@synthesize backgrondGhostView=_backgrondGhostView - In the implementation block
@property (nonatomic,retain) UILabel * couldNotAccessContactsLabel;                                  //@synthesize couldNotAccessContactsLabel=_couldNotAccessContactsLabel - In the implementation block
@property (nonatomic,retain) DancingGhostImageView * dancingGhostImageView;                          //@synthesize dancingGhostImageView=_dancingGhostImageView - In the implementation block
@property (nonatomic,retain) UIButton * loadingFailedButton;                                         //@synthesize loadingFailedButton=_loadingFailedButton - In the implementation block
@property (nonatomic,retain) UILabel * loadingFailedLabel;                                           //@synthesize loadingFailedLabel=_loadingFailedLabel - In the implementation block
@property (nonatomic,retain) UILabel * loadingLabel;                                                 //@synthesize loadingLabel=_loadingLabel - In the implementation block
@property (nonatomic,retain) UILabel * noContactsLabel;                                              //@synthesize noContactsLabel=_noContactsLabel - In the implementation block
@property (assign,nonatomic,__weak) id<ContactsLoadingViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)setBackgrondGhostView:(UIView *)arg1 ;
-(UIView *)backgrondGhostView;
-(void)setDancingGhostImageView:(DancingGhostImageView *)arg1 ;
-(DancingGhostImageView *)dancingGhostImageView;
-(void)setAllowAccessLabel:(UILabel *)arg1 ;
-(UILabel *)allowAccessLabel;
-(void)setAllowAccessButton:(UIButton *)arg1 ;
-(UIButton *)allowAccessButton;
-(void)allowAccessButtonClicked;
-(void)setCouldNotAccessContactsLabel:(UILabel *)arg1 ;
-(UILabel *)couldNotAccessContactsLabel;
-(void)setLoadingFailedLabel:(UILabel *)arg1 ;
-(UILabel *)loadingFailedLabel;
-(void)setLoadingFailedButton:(UIButton *)arg1 ;
-(UIButton *)loadingFailedButton;
-(void)loadingFailedButtonClicked;
-(void)setNoContactsLabel:(UILabel *)arg1 ;
-(UILabel *)noContactsLabel;
-(void)hideAll;
-(void)setLoadingHidden:(BOOL)arg1 ;
-(void)setAllowAccessHidden:(BOOL)arg1 ;
-(void)setAccessDeniedHidden:(BOOL)arg1 ;
-(void)setLoadingFailedHidden:(BOOL)arg1 ;
-(void)setNoContactsHidden:(BOOL)arg1 ;
-(id)initWithLoadingText:(id)arg1 ;
-(void)showAllowAccess;
-(void)showAccessDenied;
-(void)showLoadingFailed;
-(void)showNoContacts;
-(void)setDelegate:(id<ContactsLoadingViewControllerDelegate>)arg1 ;
-(id<ContactsLoadingViewControllerDelegate>)delegate;
-(void)loadView;
-(void)showLoading;
-(void)setLoadingLabel:(UILabel *)arg1 ;
-(UILabel *)loadingLabel;
@end

