/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:47 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Foundation/NSCoder.h>
#import <Snapchat/FCFasterCoder.h>

@class NSMutableData, NSMutableDictionary, NSString;

@interface FCNSCoder : NSCoder <FCFasterCoder> {

	id _rootObject;
	NSMutableData* _output;
	NSMutableDictionary* _objectCache;
	NSMutableDictionary* _classCache;
	NSMutableDictionary* _stringCache;
	NSMutableDictionary* _classesByName;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)encodeCMTime:(SCD_Struct_LS191)arg1 ;
-(void)encodeCMTimeRange:(SCD_Struct_BC197)arg1 ;
-(void)encodeSInt8:(char)arg1 ;
-(void)encodeSInt16:(short)arg1 ;
-(void)encodeSInt32:(int)arg1 ;
-(void)encodeSInt64:(long long)arg1 ;
-(void)encodeUInt8:(unsigned char)arg1 ;
-(void)encodeUInt16:(unsigned short)arg1 ;
-(void)encodeFloat32:(float)arg1 ;
-(void)encodeFloat64:(double)arg1 ;
-(void)encodeRange:(NSRange)arg1 ;
-(void)encodeVector:(CGVector)arg1 ;
-(void)encodeAffineTransform:(CGAffineTransform)arg1 ;
-(void)encode3DTransform:(CATransform3D)arg1 ;
-(void)encodeCMTimeMapping:(SCD_Struct_FC216)arg1 ;
-(void)encodeUIEdgeInsets:(UIEdgeInsets)arg1 ;
-(void)encodePoint:(CGPoint)arg1 ;
-(void)encodeSize:(CGSize)arg1 ;
-(void)encodeRect:(CGRect)arg1 ;
-(void)encodeBool:(BOOL)arg1 ;
-(void)encodeUInt32:(unsigned)arg1 ;
-(void)encodeUInt64:(unsigned long long)arg1 ;
-(void)encodeObject:(id)arg1 forKey:(id)arg2 ;
-(void)encodeBool:(BOOL)arg1 forKey:(id)arg2 ;
-(void)encodeInt:(int)arg1 forKey:(id)arg2 ;
-(BOOL)allowsKeyedCoding;
-(void)encodeInteger:(long long)arg1 forKey:(id)arg2 ;
-(void)encodeBytes:(const char*)arg1 length:(unsigned long long)arg2 forKey:(id)arg3 ;
-(void)encodeFloat:(float)arg1 forKey:(id)arg2 ;
-(void)encodeDouble:(double)arg1 forKey:(id)arg2 ;
-(void)encodeConditionalObject:(id)arg1 forKey:(id)arg2 ;
-(void)encodeInt32:(int)arg1 forKey:(id)arg2 ;
-(void)encodeInt64:(long long)arg1 forKey:(id)arg2 ;
-(void)encodeObject:(id)arg1 ;
@end

