/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:58 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@class NSString, NSMutableArray, GPBInt32Array, GPBFileOptions, GPBSourceCodeInfo;

@interface GPBFileDescriptorProto : GPBMessage

@property (nonatomic,copy) NSString * name; 
@property (assign,nonatomic) BOOL hasName; 
@property (nonatomic,copy) NSString * package; 
@property (assign,nonatomic) BOOL hasPackage; 
@property (nonatomic,retain) NSMutableArray * dependencyArray; 
@property (nonatomic,readonly) unsigned long long dependencyArray_Count; 
@property (nonatomic,retain) GPBInt32Array * publicDependencyArray; 
@property (nonatomic,readonly) unsigned long long publicDependencyArray_Count; 
@property (nonatomic,retain) GPBInt32Array * weakDependencyArray; 
@property (nonatomic,readonly) unsigned long long weakDependencyArray_Count; 
@property (nonatomic,retain) NSMutableArray * messageTypeArray; 
@property (nonatomic,readonly) unsigned long long messageTypeArray_Count; 
@property (nonatomic,retain) NSMutableArray * enumTypeArray; 
@property (nonatomic,readonly) unsigned long long enumTypeArray_Count; 
@property (nonatomic,retain) NSMutableArray * serviceArray; 
@property (nonatomic,readonly) unsigned long long serviceArray_Count; 
@property (nonatomic,retain) NSMutableArray * extensionArray; 
@property (nonatomic,readonly) unsigned long long extensionArray_Count; 
@property (nonatomic,retain) GPBFileOptions * options; 
@property (assign,nonatomic) BOOL hasOptions; 
@property (nonatomic,retain) GPBSourceCodeInfo * sourceCodeInfo; 
@property (assign,nonatomic) BOOL hasSourceCodeInfo; 
@property (nonatomic,copy) NSString * syntax; 
@property (assign,nonatomic) BOOL hasSyntax; 
+(id)descriptor;
@end

