/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:51 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCGenericSettingsViewController.h>
#import <UIKit/UIWebViewDelegate.h>

@protocol InformationSettingsViewDelegate;
@class UIWebView, NSURL, UIActivityIndicatorView, NSURLRequest, NSString;

@interface InformationSettingsViewController : SCGenericSettingsViewController <UIWebViewDelegate> {

	BOOL _snapcash;
	id<InformationSettingsViewDelegate> _delegate;
	UIWebView* _webView;
	NSURL* _url;
	UIActivityIndicatorView* _activityIndicatorView;
	NSURLRequest* _request;
	NSString* _implicitTitle;

}

@property (nonatomic,retain) UIWebView * webView;                                              //@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) NSURL * url;                                                      //@synthesize url=_url - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView * activityIndicatorView;                  //@synthesize activityIndicatorView=_activityIndicatorView - In the implementation block
@property (nonatomic,retain) NSURLRequest * request;                                           //@synthesize request=_request - In the implementation block
@property (nonatomic,retain) NSString * implicitTitle;                                         //@synthesize implicitTitle=_implicitTitle - In the implementation block
@property (assign,nonatomic) BOOL snapcash;                                                    //@synthesize snapcash=_snapcash - In the implementation block
@property (assign,nonatomic,__weak) id<InformationSettingsViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)leftButtonPressed;
-(id)imageForLeftButtonInState:(unsigned long long)arg1 ;
-(id)titleForHeader:(id)arg1 ;
-(id)textColorForHeader:(id)arg1 ;
-(BOOL)snapcash;
-(void)setSnapcash:(BOOL)arg1 ;
-(id)getPageViewName;
-(void)setImplicitTitle:(NSString *)arg1 ;
-(NSString *)implicitTitle;
-(void)setDelegate:(id<InformationSettingsViewDelegate>)arg1 ;
-(void)dealloc;
-(id<InformationSettingsViewDelegate>)delegate;
-(NSURL *)url;
-(NSURLRequest *)request;
-(unsigned long long)supportedInterfaceOrientations;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLayoutSubviews;
-(UIWebView *)webView;
-(void)setWebView:(UIWebView *)arg1 ;
-(id)initWithURL:(id)arg1 ;
-(void)setUrl:(NSURL *)arg1 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(id)initWithRequest:(id)arg1 ;
-(void)setRequest:(NSURLRequest *)arg1 ;
-(UIActivityIndicatorView *)activityIndicatorView;
-(void)setActivityIndicatorView:(UIActivityIndicatorView *)arg1 ;
@end

