/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:45 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface LSACategory : NSObject {

	NSString* _categoryId;
	long long _activatorType;
	unsigned long long _trackingRequirements;
	NSString* _initialEffectPath;
	NSDictionary* _activatorParameters;

}

@property (nonatomic,copy,readonly) NSString * categoryId;                           //@synthesize categoryId=_categoryId - In the implementation block
@property (nonatomic,readonly) long long activatorType;                              //@synthesize activatorType=_activatorType - In the implementation block
@property (nonatomic,readonly) unsigned long long trackingRequirements;              //@synthesize trackingRequirements=_trackingRequirements - In the implementation block
@property (nonatomic,copy,readonly) NSString * initialEffectPath;                    //@synthesize initialEffectPath=_initialEffectPath - In the implementation block
@property (nonatomic,copy) NSDictionary * activatorParameters;                       //@synthesize activatorParameters=_activatorParameters - In the implementation block
+(long long)activatorTypeFromActivatorId:(id)arg1 ;
+(id)categoryFromCategoryId:(id)arg1 activatorType:(id)arg2 ;
+(id)activatorParametersWithCagetory:(id)arg1 ;
+(id)categoriesFromLenses:(id)arg1 scope:(unsigned long long)arg2 ;
+(id)categoryFromLensCategory:(id)arg1 ;
+(double)currentDeviceNaturalFeatureTimeoutFromServer;
+(id)defaultCategories;
-(id)initWithId:(id)arg1 activatorType:(long long)arg2 trackingRequirements:(unsigned long long)arg3 initialEffectPath:(id)arg4 ;
-(long long)activatorType;
-(unsigned long long)trackingRequirements;
-(NSDictionary *)activatorParameters;
-(void)setActivatorParameters:(NSDictionary *)arg1 ;
-(NSString *)categoryId;
-(NSString *)initialEffectPath;
@end

