/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:45 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/MGLVectorStyleLayer.h>

@class MGLStyleValue;

@interface MGLFillStyleLayer : MGLVectorStyleLayer

@property (nonatomic,readonly) FillLayer* rawLayer; 
@property (getter=isFillAntialiased,nonatomic,retain) MGLStyleValue * fillAntialiased; 
@property (nonatomic,retain) MGLStyleValue * fillAntialias; 
@property (nonatomic,retain) MGLStyleValue * fillColor; 
@property (assign,nonatomic) MGLTransition fillColorTransition; 
@property (nonatomic,retain) MGLStyleValue * fillOpacity; 
@property (assign,nonatomic) MGLTransition fillOpacityTransition; 
@property (nonatomic,retain) MGLStyleValue * fillOutlineColor; 
@property (assign,nonatomic) MGLTransition fillOutlineColorTransition; 
@property (nonatomic,retain) MGLStyleValue * fillPattern; 
@property (assign,nonatomic) MGLTransition fillPatternTransition; 
@property (nonatomic,retain) MGLStyleValue * fillTranslation; 
@property (assign,nonatomic) MGLTransition fillTranslationTransition; 
@property (nonatomic,retain) MGLStyleValue * fillTranslate; 
@property (nonatomic,retain) MGLStyleValue * fillTranslationAnchor; 
@property (nonatomic,retain) MGLStyleValue * fillTranslateAnchor; 
-(FillLayer*)rawLayer;
-(id)initWithIdentifier:(id)arg1 source:(id)arg2 ;
-(id)sourceLayerIdentifier;
-(void)setSourceLayerIdentifier:(id)arg1 ;
-(id)isFillAntialiased;
-(MGLStyleValue *)fillTranslation;
-(MGLStyleValue *)fillTranslationAnchor;
-(void)setFillAntialiased:(MGLStyleValue *)arg1 ;
-(void)setFillAntialias:(MGLStyleValue *)arg1 ;
-(MGLStyleValue *)fillAntialias;
-(void)setFillColorTransition:(MGLTransition)arg1 ;
-(MGLTransition)fillColorTransition;
-(void)setFillOpacity:(MGLStyleValue *)arg1 ;
-(void)setFillOpacityTransition:(MGLTransition)arg1 ;
-(MGLTransition)fillOpacityTransition;
-(void)setFillOutlineColor:(MGLStyleValue *)arg1 ;
-(MGLStyleValue *)fillOutlineColor;
-(void)setFillOutlineColorTransition:(MGLTransition)arg1 ;
-(MGLTransition)fillOutlineColorTransition;
-(void)setFillPattern:(MGLStyleValue *)arg1 ;
-(MGLStyleValue *)fillPattern;
-(void)setFillPatternTransition:(MGLTransition)arg1 ;
-(MGLTransition)fillPatternTransition;
-(void)setFillTranslation:(MGLStyleValue *)arg1 ;
-(void)setFillTranslationTransition:(MGLTransition)arg1 ;
-(MGLTransition)fillTranslationTransition;
-(void)setFillTranslate:(MGLStyleValue *)arg1 ;
-(MGLStyleValue *)fillTranslate;
-(void)setFillTranslationAnchor:(MGLStyleValue *)arg1 ;
-(void)setFillTranslateAnchor:(MGLStyleValue *)arg1 ;
-(MGLStyleValue *)fillTranslateAnchor;
-(MGLStyleValue *)fillOpacity;
-(void)setFillColor:(MGLStyleValue *)arg1 ;
-(MGLStyleValue *)fillColor;
-(void)setPredicate:(id)arg1 ;
-(id)predicate;
-(id)sourceIdentifier;
@end

