/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:45 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIView.h>

@class NSArray, UIView, MGLDistanceFormatter, UIColor, CALayer;

@interface MGLScaleBar : UIView {

	double _metersPerPoint;
	NSArray* _labels;
	NSArray* _bars;
	UIView* _containerView;
	MGLDistanceFormatter* _formatter;
	UIColor* _primaryColor;
	UIColor* _secondaryColor;
	CALayer* _borderLayer;
	double _borderWidth;
	MGLRow _row;

}

@property (nonatomic,retain) NSArray * labels;                              //@synthesize labels=_labels - In the implementation block
@property (nonatomic,retain) NSArray * bars;                                //@synthesize bars=_bars - In the implementation block
@property (nonatomic,retain) UIView * containerView;                        //@synthesize containerView=_containerView - In the implementation block
@property (nonatomic,retain) MGLDistanceFormatter * formatter;              //@synthesize formatter=_formatter - In the implementation block
@property (assign,nonatomic) MGLRow row;                                    //@synthesize row=_row - In the implementation block
@property (nonatomic,retain) UIColor * primaryColor;                        //@synthesize primaryColor=_primaryColor - In the implementation block
@property (nonatomic,retain) UIColor * secondaryColor;                      //@synthesize secondaryColor=_secondaryColor - In the implementation block
@property (nonatomic,retain) CALayer * borderLayer;                         //@synthesize borderLayer=_borderLayer - In the implementation block
@property (assign,nonatomic) double borderWidth;                            //@synthesize borderWidth=_borderWidth - In the implementation block
@property (assign,nonatomic) double metersPerPoint;                         //@synthesize metersPerPoint=_metersPerPoint - In the implementation block
-(double)unitsPerPoint;
-(BOOL)usesRightToLeftLayout;
-(double)metersPerPoint;
-(MGLRow)preferredRow;
-(void)layoutBars;
-(void)layoutLabels;
-(void)setMetersPerPoint:(double)arg1 ;
-(BOOL)usesMetricSystem;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id)initWithCoder:(id)arg1 ;
-(MGLRow)row;
-(UIView *)containerView;
-(void)setContainerView:(UIView *)arg1 ;
-(void)setBorderWidth:(double)arg1 ;
-(CGSize)intrinsicContentSize;
-(double)maximumWidth;
-(double)borderWidth;
-(void)commonInit;
-(UIColor *)primaryColor;
-(void)updateLabels;
-(void)setLabels:(NSArray *)arg1 ;
-(NSArray *)labels;
-(void)setPrimaryColor:(UIColor *)arg1 ;
-(void)setSecondaryColor:(UIColor *)arg1 ;
-(UIColor *)secondaryColor;
-(MGLDistanceFormatter *)formatter;
-(void)setFormatter:(MGLDistanceFormatter *)arg1 ;
-(void)updateVisibility;
-(NSArray *)bars;
-(void)setBars:(NSArray *)arg1 ;
-(double)actualWidth;
-(void)setRow:(MGLRow)arg1 ;
-(CALayer *)borderLayer;
-(void)setBorderLayer:(CALayer *)arg1 ;
@end

