/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:59 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@interface MLBResetReason : GPBMessage

@property (assign,nonatomic) BOOL resetpin; 
@property (assign,nonatomic) BOOL hasResetpin; 
@property (assign,nonatomic) BOOL dog; 
@property (assign,nonatomic) BOOL hasDog; 
@property (assign,nonatomic) BOOL sreq; 
@property (assign,nonatomic) BOOL hasSreq; 
@property (assign,nonatomic) BOOL lockup; 
@property (assign,nonatomic) BOOL hasLockup; 
@property (assign,nonatomic) BOOL off; 
@property (assign,nonatomic) BOOL hasOff; 
@property (assign,nonatomic) BOOL lpcomp; 
@property (assign,nonatomic) BOOL hasLpcomp; 
@property (assign,nonatomic) BOOL dif; 
@property (assign,nonatomic) BOOL hasDif; 
@property (assign,nonatomic) BOOL nfc; 
@property (assign,nonatomic) BOOL hasNfc; 
@property (assign,nonatomic) BOOL por; 
@property (assign,nonatomic) BOOL hasPor; 
+(id)descriptor;
@end

