/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:59 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@interface MLBVideoData : GPBMessage

@property (assign,nonatomic) int durationMs; 
@property (assign,nonatomic) BOOL hasDurationMs; 
@property (assign,nonatomic) int codec; 
@property (assign,nonatomic) BOOL hasCodec; 
@property (assign,nonatomic) int requestedVideoCount; 
@property (assign,nonatomic) BOOL hasRequestedVideoCount; 
@property (assign,nonatomic) BOOL lastRecordAborted; 
@property (assign,nonatomic) BOOL hasLastRecordAborted; 
+(id)descriptor;
@end

