/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:05 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCAUserTrackedEvent.h>
#import <Snapchat/MapSerializable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber, NSString;

@interface SCAAdStoryView : SCAUserTrackedEvent <MapSerializable, NSCopying> {

	NSNumber* timeViewed;
	NSNumber* fullView;
	NSNumber* numSnapsViewed;
	NSNumber* numSnapsUniqueViewed;
	NSNumber* snapIndexCount;
	NSNumber* viewLocationPos;
	NSNumber* autoAdvanceIndex;
	NSNumber* snapCount;
	NSNumber* storySessionId;
	NSNumber* viewLocation;
	NSNumber* totalMediaDurationInSec;
	long long storyType;
	long long exitEvent;
	long long source;
	long long storyTypeSpecific;
	long long adProductSourceType;
	long long viewSource;
	NSString* adUnitId;
	NSString* adsnapLineItemId;
	NSString* adsnapPlacementId;
	NSString* adId;
	NSString* posterId;
	NSString* tabType;

}
-(void)setSnapCount:(long long)arg1 ;
-(void)setExitEvent:(long long)arg1 ;
-(void)setAdId:(id)arg1 ;
-(id)getEventName;
-(long long)getEventQoS;
-(double)getSamplingRate;
-(id)getAdId;
-(long long)getAutoAdvanceIndex;
-(void)setAutoAdvanceIndex:(long long)arg1 ;
-(long long)getStoryType;
-(long long)getSource;
-(double)getTimeViewed;
-(void)setTimeViewed:(double)arg1 ;
-(BOOL)getFullView;
-(void)setFullView:(BOOL)arg1 ;
-(long long)getNumSnapsViewed;
-(void)setNumSnapsViewed:(long long)arg1 ;
-(long long)getExitEvent;
-(long long)getViewSource;
-(void)setViewSource:(long long)arg1 ;
-(id)getAdsnapPlacementId;
-(void)setAdsnapPlacementId:(id)arg1 ;
-(id)getAdsnapLineItemId;
-(void)setAdsnapLineItemId:(id)arg1 ;
-(long long)getStoryTypeSpecific;
-(void)setStoryTypeSpecific:(long long)arg1 ;
-(long long)getSnapIndexCount;
-(void)setSnapIndexCount:(long long)arg1 ;
-(id)getAdUnitId;
-(void)setAdUnitId:(id)arg1 ;
-(long long)getViewLocationPos;
-(void)setViewLocationPos:(long long)arg1 ;
-(long long)getViewLocation;
-(void)setViewLocation:(long long)arg1 ;
-(id)getPosterId;
-(void)setPosterId:(id)arg1 ;
-(long long)getStorySessionId;
-(void)setStorySessionId:(long long)arg1 ;
-(long long)getAdProductSourceType;
-(void)setAdProductSourceType:(long long)arg1 ;
-(id)getTabType;
-(void)setTabType:(id)arg1 ;
-(long long)getSnapCount;
-(long long)getNumSnapsUniqueViewed;
-(void)setNumSnapsUniqueViewed:(long long)arg1 ;
-(double)getTotalMediaDurationInSec;
-(void)setTotalMediaDurationInSec:(double)arg1 ;
-(id)init;
-(void)setSource:(long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)asDictionary;
-(void)setStoryType:(long long)arg1 ;
@end

