/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:04 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/NamedEvent.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber, NSString, SCAAdView;

@interface SCAAdLongformView : NSObject <NamedEvent, NSCopying> {

	NSNumber* inlineVideoTimeViewed;
	NSNumber* inlineVideoViewCount;
	NSNumber* inlineVideoTotalCount;
	NSNumber* pageHeightTotalPixel;
	NSNumber* pageHeightSeenPixel;
	NSNumber* withCaptionOnStart;
	NSNumber* captionTimeSec;
	NSNumber* aspectRatio;
	NSNumber* landscapeTimeSec;
	NSNumber* durationSec;
	NSNumber* pageIsLoadedOnEntry;
	NSNumber* pageIsLoadedOnExit;
	NSNumber* pageUrlCount;
	NSNumber* pageLoadErrorCount;
	NSNumber* loadingScreenTimeSec;
	NSNumber* userPermissionPromptCount;
	NSNumber* userPermissionPromptAllowedCount;
	NSNumber* deepLinkedToAppCount;
	NSNumber* deepLinkedToAppInstallCount;
	NSNumber* withSubscription;
	long long longformType;
	NSString* videoPartnerId;
	NSString* webpageFieldsAutofillDetected;
	NSString* webpageFieldsDetected;
	SCAAdView* adView;

}
-(void)setDeepLinkedToAppCount:(long long)arg1 ;
-(void)setDeepLinkedToAppInstallCount:(long long)arg1 ;
-(id)getEventName;
-(long long)getEventQoS;
-(double)getSamplingRate;
-(long long)getLongformType;
-(void)setLongformType:(long long)arg1 ;
-(double)getInlineVideoTimeViewed;
-(void)setInlineVideoTimeViewed:(double)arg1 ;
-(long long)getInlineVideoViewCount;
-(void)setInlineVideoViewCount:(long long)arg1 ;
-(long long)getInlineVideoTotalCount;
-(void)setInlineVideoTotalCount:(long long)arg1 ;
-(long long)getPageHeightTotalPixel;
-(void)setPageHeightTotalPixel:(long long)arg1 ;
-(long long)getPageHeightSeenPixel;
-(void)setPageHeightSeenPixel:(long long)arg1 ;
-(BOOL)getWithCaptionOnStart;
-(void)setWithCaptionOnStart:(BOOL)arg1 ;
-(double)getCaptionTimeSec;
-(void)setCaptionTimeSec:(double)arg1 ;
-(double)getAspectRatio;
-(double)getLandscapeTimeSec;
-(void)setLandscapeTimeSec:(double)arg1 ;
-(double)getDurationSec;
-(void)setDurationSec:(double)arg1 ;
-(BOOL)getPageIsLoadedOnEntry;
-(void)setPageIsLoadedOnEntry:(BOOL)arg1 ;
-(BOOL)getPageIsLoadedOnExit;
-(void)setPageIsLoadedOnExit:(BOOL)arg1 ;
-(long long)getPageUrlCount;
-(void)setPageUrlCount:(long long)arg1 ;
-(long long)getPageLoadErrorCount;
-(void)setPageLoadErrorCount:(long long)arg1 ;
-(double)getLoadingScreenTimeSec;
-(void)setLoadingScreenTimeSec:(double)arg1 ;
-(long long)getUserPermissionPromptCount;
-(void)setUserPermissionPromptCount:(long long)arg1 ;
-(long long)getUserPermissionPromptAllowedCount;
-(void)setUserPermissionPromptAllowedCount:(long long)arg1 ;
-(long long)getDeepLinkedToAppCount;
-(long long)getDeepLinkedToAppInstallCount;
-(BOOL)getWithSubscription;
-(void)setWithSubscription:(BOOL)arg1 ;
-(id)getVideoPartnerId;
-(void)setVideoPartnerId:(id)arg1 ;
-(id)getWebpageFieldsAutofillDetected;
-(void)setWebpageFieldsAutofillDetected:(id)arg1 ;
-(id)getWebpageFieldsDetected;
-(void)setWebpageFieldsDetected:(id)arg1 ;
-(id)getAdView;
-(void)setAdView:(id)arg1 ;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)asDictionary;
-(void)setAspectRatio:(double)arg1 ;
@end

