/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:05 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCAUserTrackedEvent.h>
#import <Snapchat/MapSerializable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber, NSString;

@interface SCACameraMusicDetect : SCAUserTrackedEvent <MapSerializable, NSCopying> {

	NSNumber* latency;
	NSNumber* hasGeolens;
	long long cameraOrientation;
	long long source;
	NSString* songTitle;
	NSString* artistName;
	NSString* filterLensId;
	NSString* genre;

}
-(void)setSongTitle:(id)arg1 ;
-(id)getEventName;
-(long long)getEventQoS;
-(double)getSamplingRate;
-(long long)getLatency;
-(long long)getSource;
-(long long)getCameraOrientation;
-(id)getSongTitle;
-(id)getArtistName;
-(id)getFilterLensId;
-(void)setFilterLensId:(id)arg1 ;
-(BOOL)getHasGeolens;
-(void)setHasGeolens:(BOOL)arg1 ;
-(id)getGenre;
-(id)init;
-(void)setSource:(long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setLatency:(long long)arg1 ;
-(void)setGenre:(id)arg1 ;
-(void)setArtistName:(id)arg1 ;
-(void)setCameraOrientation:(long long)arg1 ;
-(id)asDictionary;
@end

