/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:04 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCADiscoverSnapViewBase.h>
#import <Snapchat/MapSerializable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber, NSString;

@interface SCADiscoverAdView : SCADiscoverSnapViewBase <MapSerializable, NSCopying> {

	NSNumber* fullView;
	NSNumber* adIndexCount;
	NSNumber* adIndexPos;
	NSNumber* snapTimeSec;
	NSNumber* mediaDisplayTimeSec;
	NSNumber* rollMaxDegree;
	NSNumber* rollMinDegree;
	NSNumber* isArchived;
	NSNumber* webviewLoadedOnEntry;
	NSNumber* webviewLoadedOnExit;
	NSNumber* deepLinkFromCard;
	NSNumber* deepLinkFallbackToAppStore;
	NSNumber* deepLinkFallbackToWebview;
	NSNumber* cardVisibleTime;
	NSNumber* isCameraAd;
	NSNumber* interactionIndexPos;
	NSNumber* interactionIndexCount;
	long long mediaType;
	long long cardExitEvent;
	NSString* adsnapId;
	NSString* adId;
	NSString* adUnitId;
	NSString* adRequestClientId;
	NSString* adsnapPlacementId;
	NSString* adsnapLineItemId;
	NSString* userAdId;

}
-(void)setDeepLinkFromCard:(BOOL)arg1 ;
-(void)setDeepLinkFallbackToAppStore:(BOOL)arg1 ;
-(void)setDeepLinkFallbackToWebview:(BOOL)arg1 ;
-(void)setUserAdId:(id)arg1 ;
-(void)setAdId:(id)arg1 ;
-(id)getEventName;
-(long long)getEventQoS;
-(double)getSamplingRate;
-(id)getAdId;
-(id)getUserAdId;
-(BOOL)getFullView;
-(void)setFullView:(BOOL)arg1 ;
-(id)getAdsnapId;
-(void)setAdsnapId:(id)arg1 ;
-(double)getRollMaxDegree;
-(void)setRollMaxDegree:(double)arg1 ;
-(double)getRollMinDegree;
-(void)setRollMinDegree:(double)arg1 ;
-(long long)getInteractionIndexPos;
-(void)setInteractionIndexPos:(long long)arg1 ;
-(long long)getInteractionIndexCount;
-(void)setInteractionIndexCount:(long long)arg1 ;
-(id)getAdsnapPlacementId;
-(void)setAdsnapPlacementId:(id)arg1 ;
-(id)getAdsnapLineItemId;
-(void)setAdsnapLineItemId:(id)arg1 ;
-(id)getAdRequestClientId;
-(void)setAdRequestClientId:(id)arg1 ;
-(BOOL)getWebviewLoadedOnEntry;
-(void)setWebviewLoadedOnEntry:(BOOL)arg1 ;
-(BOOL)getWebviewLoadedOnExit;
-(void)setWebviewLoadedOnExit:(BOOL)arg1 ;
-(long long)getMediaType;
-(long long)getCardExitEvent;
-(void)setCardExitEvent:(long long)arg1 ;
-(long long)getAdIndexCount;
-(void)setAdIndexCount:(long long)arg1 ;
-(long long)getAdIndexPos;
-(void)setAdIndexPos:(long long)arg1 ;
-(double)getSnapTimeSec;
-(void)setSnapTimeSec:(double)arg1 ;
-(BOOL)getIsArchived;
-(void)setIsArchived:(BOOL)arg1 ;
-(BOOL)getIsCameraAd;
-(void)setIsCameraAd:(BOOL)arg1 ;
-(id)getAdUnitId;
-(void)setAdUnitId:(id)arg1 ;
-(double)getMediaDisplayTimeSec;
-(void)setMediaDisplayTimeSec:(double)arg1 ;
-(BOOL)getDeepLinkFromCard;
-(BOOL)getDeepLinkFallbackToAppStore;
-(BOOL)getDeepLinkFallbackToWebview;
-(double)getCardVisibleTime;
-(void)setCardVisibleTime:(double)arg1 ;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setMediaType:(long long)arg1 ;
-(id)asDictionary;
@end

