/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:05 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCADirectSnapSendBase.h>
#import <Snapchat/MapSerializable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber, NSString;

@interface SCAGallerySnapSend : SCADirectSnapSendBase <MapSerializable, NSCopying> {

	NSNumber* smartShared;
	NSNumber* meo;
	NSNumber* hasCreative;
	NSNumber* retryCount;
	NSNumber* latencyMs;
	long long lensSource;
	long long playerVersion;
	long long sendSource;
	long long galleryMediaType;
	long long orientation;
	long long entryType;
	long long mediaFormat;
	NSString* filterLensId;
	NSString* lensOptionId;
	NSString* snapSessionId;
	NSString* storySessionId;
	NSString* destinations;
	NSString* failureReason;
	NSString* snapId;
	NSString* entryId;
	NSString* externalId;
	NSString* galleryCollectionCategory;
	NSString* specsContentId;

}
-(void)setSnapSessionId:(id)arg1 ;
-(void)setLensOptionId:(id)arg1 ;
-(void)setSnapId:(id)arg1 ;
-(void)setEntryId:(id)arg1 ;
-(void)setMediaFormat:(long long)arg1 ;
-(void)setSendSource:(long long)arg1 ;
-(id)getEventName;
-(long long)getEventQoS;
-(double)getSamplingRate;
-(long long)getRetryCount;
-(id)getFailureReason;
-(long long)getSendSource;
-(id)getSnapSessionId;
-(id)getSnapId;
-(long long)getLensSource;
-(void)setLensSource:(long long)arg1 ;
-(id)getLensOptionId;
-(long long)getPlayerVersion;
-(void)setPlayerVersion:(long long)arg1 ;
-(long long)getMediaFormat;
-(long long)getGalleryMediaType;
-(void)setGalleryMediaType:(long long)arg1 ;
-(id)getEntryId;
-(id)getSpecsContentId;
-(void)setSpecsContentId:(id)arg1 ;
-(id)getFilterLensId;
-(void)setFilterLensId:(id)arg1 ;
-(long long)getEntryType;
-(id)getExternalId;
-(id)getGalleryCollectionCategory;
-(void)setGalleryCollectionCategory:(id)arg1 ;
-(id)getStorySessionId;
-(void)setStorySessionId:(id)arg1 ;
-(long long)getLatencyMs;
-(id)getDestinations;
-(BOOL)getSmartShared;
-(void)setSmartShared:(BOOL)arg1 ;
-(BOOL)getMeo;
-(void)setMeo:(BOOL)arg1 ;
-(BOOL)getHasCreative;
-(void)setHasCreative:(BOOL)arg1 ;
-(long long)getOrientation;
-(id)init;
-(void)setOrientation:(long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setRetryCount:(long long)arg1 ;
-(void)setExternalId:(id)arg1 ;
-(void)setEntryType:(long long)arg1 ;
-(void)setDestinations:(id)arg1 ;
-(void)setLatencyMs:(long long)arg1 ;
-(id)asDictionary;
-(void)setFailureReason:(id)arg1 ;
@end

