/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:06 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCAUserTrackedEvent.h>
#import <Snapchat/MapSerializable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber, NSString;

@interface SCAStorySnapWaitTime : SCAUserTrackedEvent <MapSerializable, NSCopying> {

	NSNumber* autoAdvanceIndex;
	NSNumber* mediaBytesSize;
	NSNumber* snapTimeSec;
	NSNumber* startNumBytesDownloaded;
	NSNumber* bandwidthMean;
	NSNumber* bandwidthMedian;
	NSNumber* bandwidthSampleSize;
	NSNumber* deviceScore;
	NSNumber* time;
	NSNumber* snapIndexPos;
	NSNumber* snapIndexCount;
	NSNumber* storySessionId;
	NSNumber* withStreamingEnabled;
	long long viewSource;
	long long mediaType;
	long long connectionClass;
	long long itemLoadState;
	long long storyType;
	long long storyTypeSpecific;
	NSString* storySnapId;
	NSString* type;
	NSString* previousAction;
	NSString* sessionId;
	NSString* geofence;
	NSString* posterId;
	NSString* ghost_poster_id;

}
-(void)setDeviceScore:(long long)arg1 ;
-(void)setConnectionClass:(long long)arg1 ;
-(void)setGeofence:(id)arg1 ;
-(id)getSessionId;
-(id)getEventName;
-(long long)getEventQoS;
-(double)getSamplingRate;
-(long long)getAutoAdvanceIndex;
-(void)setAutoAdvanceIndex:(long long)arg1 ;
-(long long)getStoryType;
-(long long)getViewSource;
-(void)setViewSource:(long long)arg1 ;
-(long long)getMediaType;
-(long long)getStoryTypeSpecific;
-(void)setStoryTypeSpecific:(long long)arg1 ;
-(long long)getSnapIndexCount;
-(void)setSnapIndexCount:(long long)arg1 ;
-(long long)getSnapIndexPos;
-(void)setSnapIndexPos:(long long)arg1 ;
-(double)getSnapTimeSec;
-(void)setSnapTimeSec:(double)arg1 ;
-(long long)getDeviceScore;
-(id)getPosterId;
-(void)setPosterId:(id)arg1 ;
-(id)getGhost_poster_id;
-(void)setGhost_poster_id:(id)arg1 ;
-(double)getBandwidthMean;
-(double)getBandwidthMedian;
-(void)setBandwidthMedian:(double)arg1 ;
-(long long)getBandwidthSampleSize;
-(void)setBandwidthSampleSize:(long long)arg1 ;
-(long long)getConnectionClass;
-(id)getStorySnapId;
-(void)setStorySnapId:(id)arg1 ;
-(long long)getStorySessionId;
-(void)setStorySessionId:(long long)arg1 ;
-(BOOL)getWithStreamingEnabled;
-(void)setWithStreamingEnabled:(BOOL)arg1 ;
-(long long)getItemLoadState;
-(void)setItemLoadState:(long long)arg1 ;
-(long long)getMediaBytesSize;
-(void)setMediaBytesSize:(long long)arg1 ;
-(long long)getStartNumBytesDownloaded;
-(void)setStartNumBytesDownloaded:(long long)arg1 ;
-(long long)getTime;
-(id)getPreviousAction;
-(id)getGeofence;
-(id)init;
-(void)setType:(id)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(void)setTime:(long long)arg1 ;
-(void)setSessionId:(id)arg1 ;
-(void)setMediaType:(long long)arg1 ;
-(void)setBandwidthMean:(double)arg1 ;
-(id)asDictionary;
-(id)getType;
-(void)setPreviousAction:(id)arg1 ;
-(void)setStoryType:(long long)arg1 ;
@end

