/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:47 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCBitmojiUser.h>
@class NSString;


@protocol SCBitmojiUser <NSObject,NSCoding,NSCopying>
@property (nonatomic,copy,readonly) NSString * userId; 
@property (nonatomic,copy,readonly) NSString * bitmojiAvatarId; 
@property (nonatomic,copy,readonly) NSString * bitmojiSelfieId; 
@required
-(NSString *)bitmojiAvatarId;
-(NSString *)bitmojiSelfieId;
-(NSString *)userId;

@end


@class NSString;

@interface SCBitmojiUser : NSObject <SCBitmojiUser> {

	NSString* _userId;
	NSString* _bitmojiAvatarId;
	NSString* _bitmojiSelfieId;

}

@property (nonatomic,copy,readonly) NSString * userId;                       //@synthesize userId=_userId - In the implementation block
@property (nonatomic,copy,readonly) NSString * bitmojiAvatarId;              //@synthesize bitmojiAvatarId=_bitmojiAvatarId - In the implementation block
@property (nonatomic,copy,readonly) NSString * bitmojiSelfieId;              //@synthesize bitmojiSelfieId=_bitmojiSelfieId - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)fasterCodingVersion;
+(unsigned long long*)fasterCodingKeys;
-(BOOL)preferFasterCoding;
-(void)encodeWithFasterCoder:(id)arg1 ;
-(void)decodeWithFasterDecoder:(id)arg1 ;
-(void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2 ;
-(NSString *)bitmojiAvatarId;
-(NSString *)bitmojiSelfieId;
-(id)initWithUserId:(id)arg1 bitmojiAvatarId:(id)arg2 bitmojiSelfieId:(id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)userId;
@end

