/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:34 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCCachedSnapchatter.h>
@class NSString;


@protocol SCCachedSnapchatter <NSObject,NSCoding,NSCopying>
@property (nonatomic,readonly) BOOL exists; 
@property (nonatomic,copy,readonly) NSString * username; 
@property (nonatomic,copy,readonly) NSString * displayName; 
@property (nonatomic,readonly) long long lastFetchedTimestamp; 
@required
-(long long)lastFetchedTimestamp;
-(NSString *)displayName;
-(NSString *)username;
-(BOOL)exists;

@end


@class NSString;

@interface SCCachedSnapchatter : NSObject <SCCachedSnapchatter> {

	BOOL _exists;
	NSString* _username;
	NSString* _displayName;
	long long _lastFetchedTimestamp;

}

@property (nonatomic,readonly) BOOL exists;                                 //@synthesize exists=_exists - In the implementation block
@property (nonatomic,copy,readonly) NSString * username;                    //@synthesize username=_username - In the implementation block
@property (nonatomic,copy,readonly) NSString * displayName;                 //@synthesize displayName=_displayName - In the implementation block
@property (nonatomic,readonly) long long lastFetchedTimestamp;              //@synthesize lastFetchedTimestamp=_lastFetchedTimestamp - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(long long)lastFetchedTimestamp;
-(id)initWithExists:(BOOL)arg1 username:(id)arg2 displayName:(id)arg3 lastFetchedTimestamp:(long long)arg4 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)displayName;
-(NSString *)username;
-(BOOL)exists;
@end

