/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:07 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCCachingMediaRequest.h>
#import <Snapchat/SCProgressReporting.h>

@protocol OS_dispatch_queue, SCProgressReceiving;
@class NSObject, SCSentinel, SCCachingMediaRequestGroup, NSString;

@interface SCCachingMediaRequest : NSObject <SCCachingMediaRequest, SCProgressReporting> {

	/*^block*/id _resultHandler;
	NSObject*<OS_dispatch_queue> _queue;
	unsigned long long _deliveryMode;
	SCSentinel* _sentinel;
	id<SCProgressReceiving> _progressReceiver;
	SCCachingMediaRequestGroup* _requestGroup;

}

@property (assign,nonatomic,__weak) SCCachingMediaRequestGroup * requestGroup;              //@synthesize requestGroup=_requestGroup - In the implementation block
@property (nonatomic,readonly) BOOL isCancelled; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<SCProgressReceiving> progressReceiver;               //@synthesize progressReceiver=_progressReceiver - In the implementation block
-(id<SCProgressReceiving>)progressReceiver;
-(void)setProgressReceiver:(id<SCProgressReceiving>)arg1 ;
-(SCCachingMediaRequestGroup *)requestGroup;
-(void)setRequestGroup:(SCCachingMediaRequestGroup *)arg1 ;
-(id)initWithResultHandler:(/*^block*/id)arg1 queue:(id)arg2 deliveryMode:(unsigned long long)arg3 ;
-(void)perform:(id)arg1 fromCache:(BOOL)arg2 sourceLevel:(long long)arg3 final:(BOOL)arg4 ;
-(void)cancel;
-(BOOL)isCancelled;
@end

