/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:44 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSObject.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, NSAttributedString, NSArray, SOJUCaptionStyle, UIColor, NSDictionary;

@interface SCCaptionState : NSObject <NSObject, NSCopying> {

	BOOL _hidden;
	BOOL _editing;
	BOOL _isTracking;
	long long _mode;
	NSString* _text;
	NSAttributedString* _attributedText;
	double _fontSize;
	double _editingFontSize;
	double _centerX;
	double _centerY;
	double _rotation;
	double _keyboardHeight;
	NSArray* _trackingTrajectory;
	SOJUCaptionStyle* _captionStyle;
	UIColor* _pickedColor;
	long long _uniqueId;
	NSDictionary* _taggedUsers;
	long long _userTaggingStartIndex;

}

@property (assign,nonatomic) long long mode;                                 //@synthesize mode=_mode - In the implementation block
@property (nonatomic,copy) NSString * text;                                  //@synthesize text=_text - In the implementation block
@property (nonatomic,copy) NSAttributedString * attributedText;              //@synthesize attributedText=_attributedText - In the implementation block
@property (assign,nonatomic) double fontSize;                                //@synthesize fontSize=_fontSize - In the implementation block
@property (assign,nonatomic) double editingFontSize;                         //@synthesize editingFontSize=_editingFontSize - In the implementation block
@property (assign,nonatomic) double centerX;                                 //@synthesize centerX=_centerX - In the implementation block
@property (assign,nonatomic) double centerY;                                 //@synthesize centerY=_centerY - In the implementation block
@property (assign,nonatomic) double rotation;                                //@synthesize rotation=_rotation - In the implementation block
@property (assign,nonatomic) BOOL hidden;                                    //@synthesize hidden=_hidden - In the implementation block
@property (assign,nonatomic) BOOL editing;                                   //@synthesize editing=_editing - In the implementation block
@property (assign,nonatomic) double keyboardHeight;                          //@synthesize keyboardHeight=_keyboardHeight - In the implementation block
@property (assign,nonatomic) BOOL isTracking;                                //@synthesize isTracking=_isTracking - In the implementation block
@property (nonatomic,copy) NSArray * trackingTrajectory;                     //@synthesize trackingTrajectory=_trackingTrajectory - In the implementation block
@property (nonatomic,retain) SOJUCaptionStyle * captionStyle;                //@synthesize captionStyle=_captionStyle - In the implementation block
@property (nonatomic,copy) UIColor * pickedColor;                            //@synthesize pickedColor=_pickedColor - In the implementation block
@property (assign,nonatomic) long long uniqueId;                             //@synthesize uniqueId=_uniqueId - In the implementation block
@property (nonatomic,copy) NSDictionary * taggedUsers;                       //@synthesize taggedUsers=_taggedUsers - In the implementation block
@property (assign,nonatomic) long long userTaggingStartIndex;                //@synthesize userTaggingStartIndex=_userTaggingStartIndex - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)stateWithMode:(long long)arg1 text:(id)arg2 hidden:(BOOL)arg3 ;
-(double)editingFontSize;
-(NSArray *)trackingTrajectory;
-(SOJUCaptionStyle *)captionStyle;
-(UIColor *)pickedColor;
-(void)setEditingFontSize:(double)arg1 ;
-(void)setTrackingTrajectory:(NSArray *)arg1 ;
-(void)setCaptionStyle:(SOJUCaptionStyle *)arg1 ;
-(void)setPickedColor:(UIColor *)arg1 ;
-(NSDictionary *)taggedUsers;
-(void)setTaggedUsers:(NSDictionary *)arg1 ;
-(long long)userTaggingStartIndex;
-(void)setUserTaggingStartIndex:(long long)arg1 ;
-(id)init;
-(void)setHidden:(BOOL)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(void)setAttributedText:(NSAttributedString *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(BOOL)isTracking;
-(NSAttributedString *)attributedText;
-(BOOL)editing;
-(void)setEditing:(BOOL)arg1 ;
-(void)setMode:(long long)arg1 ;
-(long long)mode;
-(void)setFontSize:(double)arg1 ;
-(void)setRotation:(double)arg1 ;
-(double)rotation;
-(long long)uniqueId;
-(double)fontSize;
-(BOOL)hidden;
-(void)setIsTracking:(BOOL)arg1 ;
-(double)centerX;
-(double)centerY;
-(void)setCenterX:(double)arg1 ;
-(void)setCenterY:(double)arg1 ;
-(void)setUniqueId:(long long)arg1 ;
-(void)setKeyboardHeight:(double)arg1 ;
-(double)keyboardHeight;
@end

