/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:36 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCSwipePresentationController.h>

@class SCGalleryViewController, MainViewController;

@interface SCCameraToGalleryPresentationController : SCSwipePresentationController {

	SCGalleryViewController* _galleryViewController;
	MainViewController* _mainViewController;

}

@property (assign,nonatomic,__weak) SCGalleryViewController * galleryViewController;              //@synthesize galleryViewController=_galleryViewController - In the implementation block
@property (assign,nonatomic,__weak) MainViewController * mainViewController;                      //@synthesize mainViewController=_mainViewController - In the implementation block
-(void)_transitionWillBegin:(long long)arg1 ;
-(BOOL)_shouldAnimateTabBar:(long long)arg1 ;
-(void)_setDarkModeEnabled:(BOOL)arg1 tabBar:(id)arg2 ;
-(void)setGalleryViewController:(SCGalleryViewController *)arg1 ;
-(void)presentationTransitionDidEnd:(BOOL)arg1 ;
-(void)dismissalTransitionDidEnd:(BOOL)arg1 ;
-(void)presentationTransitionWillBegin;
-(void)dismissalTransitionWillBegin;
-(id)_tabBar;
-(MainViewController *)mainViewController;
-(void)setMainViewController:(MainViewController *)arg1 ;
-(id)_navigationBar;
-(SCGalleryViewController *)galleryViewController;
-(id)cameraViewController;
@end

