/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:29 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCGalleryInChatLogger;
#import <Snapchat/Snapchat-Structs.h>
@class SCChat, NSString, SCCustomStickerManager, SCAttachmentsLogger;

@interface SCChatSendHelper : NSObject {

	SCChat* _chat;
	NSString* _senderUsername;
	SCCustomStickerManager* _customStickerManager;
	SCAttachmentsLogger* _attachmentsLogger;
	id<SCGalleryInChatLogger> _galleryLogger;

}
-(void)insertSendingMessage:(id)arg1 ;
-(void)messageStateDidChange:(id)arg1 ;
-(id)initWithChat:(id)arg1 senderUsername:(id)arg2 customStickerManager:(id)arg3 galleryInChatLogger:(id)arg4 ;
-(void)sendStoryReplyMessage:(id)arg1 ;
-(void)sendMediaDrawerMedia:(id)arg1 fromLocation:(SCD_Struct_SC420)arg2 drawerMode:(long long)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)sendAudioNoteWithData:(id)arg1 duration:(double)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)sendVideoNoteWithData:(id)arg1 duration:(double)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)_prepareMediaData:(id)arg1 withMediaDrawerMedia:(id)arg2 atIndex:(unsigned long long)arg3 ;
-(void)sendCameraRollSaveForMessage:(id)arg1 ;
-(void)sendSticker:(id)arg1 fromPack:(id)arg2 fromPosition:(unsigned long long)arg3 drawerMode:(long long)arg4 fromSource:(long long)arg5 completionHandler:(/*^block*/id)arg6 ;
-(id)createStoryReplyMediaMessage:(id)arg1 story:(id)arg2 storyType:(long long)arg3 storyTypeSpecific:(long long)arg4 ;
-(void)createStickerMessage:(id)arg1 fromPack:(id)arg2 fromPosition:(unsigned long long)arg3 drawerMode:(long long)arg4 messageCreationCompletion:(/*^block*/id)arg5 ;
-(id)createMediaDrawerMediaMessage:(id)arg1 fromLocation:(SCD_Struct_SC420)arg2 drawerMode:(long long)arg3 ;
-(void)createAudioNoteMessageWithData:(id)arg1 duration:(double)arg2 messageCreationCompletion:(/*^block*/id)arg3 ;
-(void)createVideoNoteMessageWithData:(id)arg1 duration:(double)arg2 messageCreationCompletion:(/*^block*/id)arg3 ;
-(id)createGifMessageWithData:(id)arg1 ;
-(void)sendChatMessage:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)_createCustomSticker:(id)arg1 metricsEventInfo:(id)arg2 messageCreationCompletion:(/*^block*/id)arg3 ;
-(void)_sendCustomSticker:(id)arg1 chatMessage:(id)arg2 metricsEventInfo:(id)arg3 completionHandler:(/*^block*/id)arg4 ;
-(void)_sendMediaDrawerMessage:(id)arg1 mediaArray:(id)arg2 fromLocation:(SCD_Struct_SC420)arg3 drawerMode:(long long)arg4 completionHandler:(/*^block*/id)arg5 ;
-(void)_sendSingleMedia:(id)arg1 fromLocation:(SCD_Struct_SC420)arg2 drawerMode:(long long)arg3 completionHandler:(/*^block*/id)arg4 ;
-(id)_createSingleMediaMessage:(id)arg1 fromLocation:(SCD_Struct_SC420)arg2 drawerMode:(long long)arg3 ;
-(id)_createBatchedMediaMessage:(id)arg1 fromLocation:(SCD_Struct_SC420)arg2 drawerMode:(long long)arg3 ;
-(id)_mediaSaveForMessage:(id)arg1 saveType:(long long)arg2 ;
-(void)sendStoryReplyMessage:(id)arg1 completionProcess:(/*^block*/id)arg2 ;
-(void)removeMessage:(id)arg1 ;
@end

