/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:31 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString, SCSearchNetworkImage;

@interface SCCheetahSendToStoryDataModel : NSObject <NSCopying> {

	BOOL _isActive;
	NSString* _labelText;
	NSString* _officialFriendmoji;
	long long _itemType;
	NSString* _itemId;
	NSString* _mischiefId;
	SCSearchNetworkImage* _unselectedImage;

}

@property (nonatomic,copy,readonly) NSString * labelText;                                //@synthesize labelText=_labelText - In the implementation block
@property (nonatomic,copy,readonly) NSString * officialFriendmoji;                       //@synthesize officialFriendmoji=_officialFriendmoji - In the implementation block
@property (nonatomic,readonly) BOOL isActive;                                            //@synthesize isActive=_isActive - In the implementation block
@property (nonatomic,readonly) long long itemType;                                       //@synthesize itemType=_itemType - In the implementation block
@property (nonatomic,copy,readonly) NSString * itemId;                                   //@synthesize itemId=_itemId - In the implementation block
@property (nonatomic,copy,readonly) NSString * mischiefId;                               //@synthesize mischiefId=_mischiefId - In the implementation block
@property (nonatomic,copy,readonly) SCSearchNetworkImage * unselectedImage;              //@synthesize unselectedImage=_unselectedImage - In the implementation block
-(NSString *)mischiefId;
-(NSString *)officialFriendmoji;
-(id)initWithLabelText:(id)arg1 officialFriendmoji:(id)arg2 isActive:(BOOL)arg3 itemType:(long long)arg4 itemId:(id)arg5 mischiefId:(id)arg6 unselectedImage:(id)arg7 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(BOOL)isActive;
-(id)copyWithZone:(NSZone*)arg1 ;
-(SCSearchNetworkImage *)unselectedImage;
-(long long)itemType;
-(NSString *)labelText;
-(NSString *)itemId;
@end

