/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:31 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface SCCheetahSendToGroupDataModel : NSObject <NSCopying> {

	NSString* _groupId;
	NSString* _groupTitle;
	NSString* _groupDescription;
	NSString* _sectionType;

}

@property (nonatomic,copy,readonly) NSString * groupId;                       //@synthesize groupId=_groupId - In the implementation block
@property (nonatomic,copy,readonly) NSString * groupTitle;                    //@synthesize groupTitle=_groupTitle - In the implementation block
@property (nonatomic,copy,readonly) NSString * groupDescription;              //@synthesize groupDescription=_groupDescription - In the implementation block
@property (nonatomic,copy,readonly) NSString * sectionType;                   //@synthesize sectionType=_sectionType - In the implementation block
-(id)initWithGroupId:(id)arg1 groupTitle:(id)arg2 groupDescription:(id)arg3 sectionType:(id)arg4 ;
-(NSString *)groupDescription;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)groupTitle;
-(NSString *)sectionType;
-(NSString *)groupId;
@end

