/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:27 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCStoryShareCardViewDelegate.h>
#import <Snapchat/SCChatMessageRenderer.h>

@class SCChatSDKActionContext, NSString, SCMapPoiShareMetadata, SCMapStoryViewModel, UITapGestureRecognizer, SCMapSnapLocationCardView;

@interface SCChatMapStoryMessageRenderer : NSObject <SCStoryShareCardViewDelegate, SCChatMessageRenderer> {

	SCChatSDKActionContext* _actionContext;
	NSString* _conversationId;
	NSString* _messageId;
	NSString* _poiID;
	long long _state;
	SCMapPoiShareMetadata* _poiMetadata;
	SCMapStoryViewModel* _storyViewModel;
	UITapGestureRecognizer* _tapToRetryRecognizer;
	SCMapSnapLocationCardView* _locationCardView;

}

@property (nonatomic,copy) NSString * conversationId;                                          //@synthesize conversationId=_conversationId - In the implementation block
@property (nonatomic,copy) NSString * messageId;                                               //@synthesize messageId=_messageId - In the implementation block
@property (nonatomic,copy) NSString * poiID;                                                   //@synthesize poiID=_poiID - In the implementation block
@property (assign,nonatomic) long long state;                                                  //@synthesize state=_state - In the implementation block
@property (nonatomic,retain) SCMapPoiShareMetadata * poiMetadata;                              //@synthesize poiMetadata=_poiMetadata - In the implementation block
@property (nonatomic,retain) SCMapStoryViewModel * storyViewModel;                             //@synthesize storyViewModel=_storyViewModel - In the implementation block
@property (nonatomic,retain) UITapGestureRecognizer * tapToRetryRecognizer;                    //@synthesize tapToRetryRecognizer=_tapToRetryRecognizer - In the implementation block
@property (assign,nonatomic,__weak) SCMapSnapLocationCardView * locationCardView;              //@synthesize locationCardView=_locationCardView - In the implementation block
@property (assign,nonatomic,__weak) SCChatSDKActionContext * actionContext;                    //@synthesize actionContext=_actionContext - In the implementation block
-(id)createContentView;
-(void)setupContentView:(id)arg1 ;
-(void)prepareContentViewForReuse:(id)arg1 ;
-(void)willDisplayContentView:(id)arg1 ;
-(void)didEndDisplayingContentView:(id)arg1 ;
-(void)setActionContext:(SCChatSDKActionContext *)arg1 ;
-(void)didSelectPreserveMessageForMessageId:(id)arg1 conversationId:(id)arg2 ;
-(void)didTapDeepLinkWithUrl:(id)arg1 additionalInfo:(id)arg2 ;
-(void)sharedStoryPresenterDidDisappear;
-(void)sharedStoryPresenterWillAppear;
-(id)initWithConversationId:(id)arg1 messageId:(id)arg2 poiID:(id)arg3 state:(long long)arg4 ;
-(void)_loadMetadataIfReady;
-(UITapGestureRecognizer *)tapToRetryRecognizer;
-(id)_createLocationCardViewModel;
-(id)_createViewableLocationCardViewModel;
-(id)_createUnavailableLocationCardViewModel;
-(id)_createLoadingLocationCardViewModel;
-(id)_createFailureLocationCardViewModel;
-(NSString *)poiID;
-(void)setPoiID:(NSString *)arg1 ;
-(SCMapPoiShareMetadata *)poiMetadata;
-(void)setPoiMetadata:(SCMapPoiShareMetadata *)arg1 ;
-(SCMapStoryViewModel *)storyViewModel;
-(void)setStoryViewModel:(SCMapStoryViewModel *)arg1 ;
-(void)setTapToRetryRecognizer:(UITapGestureRecognizer *)arg1 ;
-(SCMapSnapLocationCardView *)locationCardView;
-(void)setLocationCardView:(SCMapSnapLocationCardView *)arg1 ;
-(CGSize)sizeThatFits:(double)arg1 ;
-(long long)state;
-(void)setState:(long long)arg1 ;
-(id)presentingViewController;
-(id)reuseIdentifier;
-(void)_setState:(long long)arg1 ;
-(id)userSession;
-(NSString *)conversationId;
-(void)setConversationId:(NSString *)arg1 ;
-(void)_updateUI;
-(SCChatSDKActionContext *)actionContext;
-(NSString *)messageId;
-(void)setMessageId:(NSString *)arg1 ;
@end

