/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:12 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCChatRequestManager, SCPerforming, SCChatLogger;
@class NSMutableDictionary, SCChatV3ConversationStore, SCChatV3MessageStateHandler, SCChatMediaStateManager, SCChatMediaReferenceManager, SCExperimentManager, SCSessionRequestManager, SCSnapTokenManager, SCChatMediaCache, SCChatMediaContentDownloadHandler, SCChatURLMetadataDownloadHandler, SCChatURLThumbnailDownloadHandler, SCChatAddressThumbnailDownloadHandler, SCChatSnapchatterDownloadHandler, SCChatStorySnapDownloadHandler, SCChatContributionStoryPublisherDownloadHandler, SCChatMapSnapDownloadHandler, SCChatMapPoiShareDownloadHandler, SCChatSearchStoryDownloadHandler;

@interface SCChatMediaRequestManager : NSObject {

	NSMutableDictionary* _downloadingMediaItemQueue;
	id<SCChatRequestManager> _chatRequestManager;
	id<SCPerforming> _downloadingQueue;
	SCChatV3ConversationStore* _conversationStore;
	SCChatV3MessageStateHandler* _messageStateHandler;
	SCChatMediaStateManager* _mediaStateManager;
	SCChatMediaReferenceManager* _mediaReferenceManager;
	id<SCChatLogger> _logger;
	SCExperimentManager* _experimentManager;
	SCSessionRequestManager* _requestManager;
	SCSnapTokenManager* _snapTokenManager;
	SCChatMediaCache* _chatMediaCache;
	SCChatMediaContentDownloadHandler* _mediaContentDownloadHandler;
	SCChatURLMetadataDownloadHandler* _urlMetadataDownloadHandler;
	SCChatURLThumbnailDownloadHandler* _urlThumbnailDownloadHandler;
	SCChatAddressThumbnailDownloadHandler* _addressThumbnailDownloadHandler;
	SCChatSnapchatterDownloadHandler* _snapchatterDownloadHandler;
	SCChatStorySnapDownloadHandler* _storySnapDownloadHandler;
	SCChatContributionStoryPublisherDownloadHandler* _contributionStoryPublisherDownloadHandler;
	SCChatMapSnapDownloadHandler* _mapSnapDownloadHandler;
	SCChatMapPoiShareDownloadHandler* _mapPoiShareDownloadHandler;
	SCChatSearchStoryDownloadHandler* _searchStoryDownloadHandler;
	NSMutableDictionary* _mediaContentFetchDispatchGroups;

}
-(id)initWithMediaRequestAPI:(id)arg1 withConversationStore:(id)arg2 withMessageStateHandler:(id)arg3 withMediaStateManager:(id)arg4 withMediaReferenceManager:(id)arg5 chatMediaCache:(id)arg6 experimentManager:(id)arg7 requestManager:(id)arg8 snapTokenManager:(id)arg9 withLogger:(id)arg10 ;
-(void)markMediaContentFetchStarted:(id)arg1 ;
-(void)executeBlockAfterMediaContentFetched:(id)arg1 block:(/*^block*/id)arg2 ;
-(void)_downloadChatMediaForChatMediaContent:(id)arg1 messageBodyType:(long long)arg2 messageId:(id)arg3 conversationId:(id)arg4 senderUsername:(id)arg5 requestContext:(long long)arg6 ;
-(BOOL)_isDownloadingForMediaId:(id)arg1 ;
-(id)mediaContentDownloadHandler;
-(void)startDownloadHandler:(id)arg1 downloableItem:(id)arg2 ;
-(void)makeChatMedias:(id)arg1 recipients:(id)arg2 groups:(id)arg3 successBlock:(/*^block*/id)arg4 failureBlock:(/*^block*/id)arg5 ;
-(id)urlMetadataDownloadHandler;
-(id)urlThumbnailDownloadHandler;
-(id)addressThumbnailDownloadHandler;
-(id)snapchatterDownloadHandler;
-(id)storySnapDownloadHandler;
-(id)mapSnapDownloadHandler;
-(id)mapPoiShareDownloadHandler;
-(id)searchStoryDownloadHandler;
-(id)contributionStoryPublisherDownloadHandler;
-(void)_insertDownloadableItem:(id)arg1 ;
-(void)_removeDownloadableItem:(id)arg1 ;
-(void)markMediaContentFetchCompleted:(id)arg1 ;
-(void)downloadChatMediaForChatMediaContent:(id)arg1 messageBodyType:(long long)arg2 messageId:(id)arg3 conversationId:(id)arg4 senderUsername:(id)arg5 requestContext:(long long)arg6 ;
-(void)uploadChatMediaForMedia:(id)arg1 message:(id)arg2 completion:(/*^block*/id)arg3 ;
-(void)downloadUrlMetadataForUrls:(id)arg1 messageId:(id)arg2 conversationId:(id)arg3 needSpamCheck:(BOOL)arg4 ;
-(void)downloadThumbnailForUrlMediaCardContent:(id)arg1 messageId:(id)arg2 conversationId:(id)arg3 ;
-(void)downloadThumbnailForAddressContent:(id)arg1 messageId:(id)arg2 conversationId:(id)arg3 ;
-(void)downloadSnapchatterForId:(id)arg1 messageId:(id)arg2 conversationId:(id)arg3 ;
-(void)downloadStorySnapForId:(id)arg1 messageId:(id)arg2 senderUsername:(id)arg3 sequenceNumber:(id)arg4 conversationId:(id)arg5 ;
-(void)downloadMapSnapForId:(id)arg1 messageId:(id)arg2 conversationId:(id)arg3 ;
-(void)downloadMapPoiShareForId:(id)arg1 messageId:(id)arg2 conversationId:(id)arg3 ;
-(void)downloadSearchStoryForId:(id)arg1 snapId:(id)arg2 messageId:(id)arg3 conversationId:(id)arg4 ;
-(void)downloadContributionStoryPublisher:(id)arg1 forMessageId:(id)arg2 conversationId:(id)arg3 ;
@end

