/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:31 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UICollectionViewCell.h>
#import <Snapchat/SCSearchActionable.h>
#import <Snapchat/SCSearchViewModelConfigurable.h>
#import <Snapchat/SCSearchViewportConfigurable.h>

@protocol SCSendPreviewMediaView, SCSearchActionHandling;
@class UIView, UILabel, SCShapeView, SCPlaceholderTextView, NSString;

@interface SCCheetahSendToPreviewCollectionViewCell : UICollectionViewCell <SCSearchActionable, SCSearchViewModelConfigurable, SCSearchViewportConfigurable> {

	UIView*<SCSendPreviewMediaView> _mediaView;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	BOOL _wantsMediaPlay;
	BOOL _shouldBeGrayedOut;
	SCShapeView* _horizontalContainerView;
	double _textFrameOriginY;
	id<SCSearchActionHandling> _actionHandler;
	id _viewModel;
	SCPlaceholderTextView* _textView;
	CGRect _viewportFrame;

}

@property (nonatomic,retain) SCPlaceholderTextView * textView;                       //@synthesize textView=_textView - In the implementation block
@property (nonatomic,retain) UIView*<SCSendPreviewMediaView> mediaView;              //@synthesize mediaView=_mediaView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,retain) id<SCSearchActionHandling> actionHandler;               //@synthesize actionHandler=_actionHandler - In the implementation block
@property (nonatomic,retain) id viewModel;                                           //@synthesize viewModel=_viewModel - In the implementation block
@property (assign,nonatomic) CGRect viewportFrame;                                   //@synthesize viewportFrame=_viewportFrame - In the implementation block
-(void)_updateWithViewModel;
-(void)viewportDidUpdateViewportFrame:(CGRect)arg1 dragging:(BOOL)arg2 decelerating:(BOOL)arg3 ;
-(CGRect)viewportFrame;
-(void)setViewportFrame:(CGRect)arg1 ;
-(double)textLabelMinContentHeight;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(void)setTextView:(SCPlaceholderTextView *)arg1 ;
-(SCPlaceholderTextView *)textView;
-(void)play;
-(void)pause;
-(UIView*<SCSendPreviewMediaView>)mediaView;
-(id)viewModel;
-(void)setViewModel:(id)arg1 ;
-(void)setActionHandler:(id<SCSearchActionHandling>)arg1 ;
-(id<SCSearchActionHandling>)actionHandler;
-(void)setMediaView:(UIView*<SCSendPreviewMediaView>)arg1 ;
@end

