/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:03 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSCoding.h>

@class NSString;

@interface SCCheetahPromotedSnap : NSObject <NSCopying, NSCoding> {

	NSString* _snapId;
	NSString* _snapUrl;
	NSString* _headline;
	NSString* _brandName;
	NSString* _requestId;
	NSString* _serveItemId;
	NSString* _adId;
	NSString* _adKey;
	NSString* _adPlacementId;
	NSString* _adLineItemId;
	double _mediaDurationSecs;
	long long _mediaType;

}

@property (nonatomic,copy,readonly) NSString * snapId;                     //@synthesize snapId=_snapId - In the implementation block
@property (nonatomic,copy,readonly) NSString * snapUrl;                    //@synthesize snapUrl=_snapUrl - In the implementation block
@property (nonatomic,copy,readonly) NSString * headline;                   //@synthesize headline=_headline - In the implementation block
@property (nonatomic,copy,readonly) NSString * brandName;                  //@synthesize brandName=_brandName - In the implementation block
@property (nonatomic,copy,readonly) NSString * requestId;                  //@synthesize requestId=_requestId - In the implementation block
@property (nonatomic,copy,readonly) NSString * serveItemId;                //@synthesize serveItemId=_serveItemId - In the implementation block
@property (nonatomic,copy,readonly) NSString * adId;                       //@synthesize adId=_adId - In the implementation block
@property (nonatomic,copy,readonly) NSString * adKey;                      //@synthesize adKey=_adKey - In the implementation block
@property (nonatomic,copy,readonly) NSString * adPlacementId;              //@synthesize adPlacementId=_adPlacementId - In the implementation block
@property (nonatomic,copy,readonly) NSString * adLineItemId;               //@synthesize adLineItemId=_adLineItemId - In the implementation block
@property (nonatomic,readonly) double mediaDurationSecs;                   //@synthesize mediaDurationSecs=_mediaDurationSecs - In the implementation block
@property (nonatomic,readonly) long long mediaType;                        //@synthesize mediaType=_mediaType - In the implementation block
-(NSString *)adId;
-(NSString *)snapId;
-(id)initWithSnapId:(id)arg1 snapUrl:(id)arg2 headline:(id)arg3 brandName:(id)arg4 requestId:(id)arg5 serveItemId:(id)arg6 adId:(id)arg7 adKey:(id)arg8 adPlacementId:(id)arg9 adLineItemId:(id)arg10 mediaDurationSecs:(double)arg11 mediaType:(long long)arg12 ;
-(NSString *)snapUrl;
-(NSString *)serveItemId;
-(NSString *)adKey;
-(NSString *)adPlacementId;
-(NSString *)adLineItemId;
-(double)mediaDurationSecs;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)requestId;
-(long long)mediaType;
-(NSString *)brandName;
-(NSString *)headline;
@end

