/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:32 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCContextSwipeUpInteractiveTransitioningDelegate <NSObject>
@optional
-(double)interactiveTransition:(id)arg1 totalSwipeDistanceForTransitionType:(unsigned long long)arg2;

@required
-(BOOL)interactiveTransition:(id)arg1 shouldRecognizeOtherGesture:(id)arg2;
-(BOOL)interactiveTransition:(id)arg1 shouldBeginWithGesture:(id)arg2;
-(void)interactiveTransitionDidBegin:(id)arg1;
-(void)interactiveTransitionDidComplete:(id)arg1;
-(void)interactiveTransitionDidCancel:(id)arg1;
-(void)interactiveTransition:(id)arg1 didUpdatePercentComplete:(double)arg2;

@end

