/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:45 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol SCStickerPickerMenuDelegate;
@class UIImageView, SCPlayerView, AVPlayer, UIView, UILabel, SCUserSession, SCLoadingIndicatorView, NSString;

@interface SCCustomStickerEmptyPage : UIView <UIGestureRecognizerDelegate> {

	UIImageView* _imageView;
	SCPlayerView* _playerView;
	AVPlayer* _player;
	UIView* _textContainer;
	UILabel* _button;
	UILabel* _introLabel;
	unsigned long long _sourceType;
	long long _orientation;
	SCUserSession* _userSession;
	SCLoadingIndicatorView* _loadingIndicator;
	id<SCStickerPickerMenuDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<SCStickerPickerMenuDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_createButtonTapped:(id)arg1 ;
-(void)_tryButtonTapped:(id)arg1 ;
-(void)_playVideo:(id)arg1 ;
-(void)_loadIndicator;
-(id)initWithFrame:(CGRect)arg1 sourceType:(unsigned long long)arg2 userSession:(id)arg3 ;
-(id)initEmptySavedSectionWithFrame:(CGRect)arg1 sourceType:(unsigned long long)arg2 userSession:(id)arg3 ;
-(id)initEmptyAutoSectionWithFrame:(CGRect)arg1 sourceType:(unsigned long long)arg2 userSession:(id)arg3 ;
-(void)tryPlayVideo;
-(void)stopPlayVideo;
-(void)layoutSubviews;
-(void)setDelegate:(id<SCStickerPickerMenuDelegate>)arg1 ;
-(void)dealloc;
-(id<SCStickerPickerMenuDelegate>)delegate;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(void)resetLayout;
@end

