/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:40 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCHovaTabBarView.h>
#import <Snapchat/SCTabBarViewDataSource_DEPRECATED.h>

@class NSString;

@interface SCDashboardTabBarView : SCHovaTabBarView <SCTabBarViewDataSource_DEPRECATED> {

	unsigned long long _activeItem;

}

@property (assign,nonatomic) unsigned long long activeItem;              //@synthesize activeItem=_activeItem - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithFrame:(CGRect)arg1 userSession:(id)arg2 ;
-(double)tabBarView:(id)arg1 horizontalVisibilityForItemType:(long long)arg2 ;
-(NSRange)visibleRangeForTabBarView:(id)arg1 ;
-(CGRect)tabBarView:(id)arg1 frameForItemWithType:(long long)arg2 inView:(id)arg3 ;
-(double)tabBarView:(id)arg1 verticalVisibilityForItemType:(long long)arg2 ;
-(double)tabBarView:(id)arg1 visibilityForItemViewWithItemType:(long long)arg2 ;
-(double)tabBarViewVerticalClippingHeight:(id)arg1 ;
-(BOOL)tabBarView:(id)arg1 shouldVerticallyClipItemOfType:(long long)arg2 ;
-(BOOL)tabBarViewIsTransitioningToPresentedController:(id)arg1 ;
-(double)tabBarViewVisibilityPercentForPresentedController:(id)arg1 ;
-(unsigned long long)activeItem;
-(void)setActiveItem:(unsigned long long)arg1 ;
-(id)lightGradientView;
-(id)darkGradientView;
@end

