/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:30 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class SCChatMainViewController, SCAppNotification;


@protocol SCFeedPage <SCPannableCellController,SwipeView>
@property (assign,nonatomic,__weak) SCChatMainViewController * chatVC; 
@property (assign,nonatomic,__weak) id<SCHovaOverscrollDelegate> hovaOverscrollDelegate; 
@property (assign,nonatomic,__weak) id<SCChatCardsOperaPresenterDelegate> chatCardsOperaPresenterDelegate; 
@property (nonatomic,retain) SCAppNotification * sourceNotification; 
@property (assign,nonatomic) BOOL didEnterThroughHova; 
@required
-(void)scrollToTop:(BOOL)arg1;
-(void)preparePanningStateWithIdentifier:(id)arg1;
-(BOOL)isPlayingSnap;
-(BOOL)isPlayingStory;
-(BOOL)isPlayingSnapOrStory;
-(void)pushStartChatView;
-(BOOL)isFirstFeedCellVisible;
-(void)dismissFullScreenMedia;
-(SCChatMainViewController *)chatVC;
-(void)setChatVC:(id)arg1;
-(id<SCHovaOverscrollDelegate>)hovaOverscrollDelegate;
-(void)setHovaOverscrollDelegate:(id)arg1;
-(id<SCChatCardsOperaPresenterDelegate>)chatCardsOperaPresenterDelegate;
-(void)setChatCardsOperaPresenterDelegate:(id)arg1;
-(SCAppNotification *)sourceNotification;
-(void)setSourceNotification:(id)arg1;
-(BOOL)didEnterThroughHova;
-(void)setDidEnterThroughHova:(BOOL)arg1;

@end

