/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:45 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIView.h>

@class NSDictionary;

@interface SCFilterView : UIView {

	BOOL _displayed;
	NSDictionary* _config;

}

@property (nonatomic,retain) NSDictionary * config;                          //@synthesize config=_config - In the implementation block
@property (assign,getter=isDisplayed,nonatomic) BOOL displayed;              //@synthesize displayed=_displayed - In the implementation block
+(id)idSpecificFilterNameWithFilterName:(id)arg1 filterId:(id)arg2 ;
+(id)geofilterIdFromName:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 config:(id)arg2 ;
-(void)updateConfig:(id)arg1 ;
-(id)renderState;
-(BOOL)shouldAddToAlternativeSuperview;
-(id)widgetValue;
-(void)startViewing;
-(void)stopViewing;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setOrientation:(long long)arg1 ;
-(NSDictionary *)config;
-(BOOL)isDisplayed;
-(void)setDisplayed:(BOOL)arg1 ;
-(void)setConfig:(NSDictionary *)arg1 ;
@end

