/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:35 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCGalleryPageNavigationController.h>

@interface SCGalleryPrivateGalleryFlowNavigationController : SCGalleryPageNavigationController
+(id)pagingAnimatorForOperation:(long long)arg1 ;
+(id)transitioningAnimatorForPresenting:(BOOL)arg1 vertical:(BOOL)arg2 ;
-(BOOL)shouldDisplayStatusBar;
-(id)pageName;
-(BOOL)shouldPopToRootViewController;
-(BOOL)shouldPopToRootViewControllerLater;
-(long long)preferredStatusBarStyle;
-(BOOL)prefersStatusBarHidden;
-(unsigned long long)supportedInterfaceOrientations;
@end

