/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:36 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIImageView.h>
#import <Snapchat/SCGalleryEntryThumbnailGeneratorDelegate.h>

@class SCGalleryEntryThumbnailGenerator, NSString;

@interface SCGallerySearchQueryResultImageView : UIImageView <SCGalleryEntryThumbnailGeneratorDelegate> {

	SCGalleryEntryThumbnailGenerator* _thumbnailGenerator;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)thumbnailGenerator:(id)arg1 didUpdateSnapThumbnailWithImageGenerating:(id)arg2 snap:(id)arg3 duration:(double)arg4 fromCache:(BOOL)arg5 isFramed:(BOOL)arg6 ;
-(void)thumbnailGenerator:(id)arg1 didUpdateStoryThumbnailWithImage:(id)arg2 snap:(id)arg3 fromCache:(BOOL)arg4 isFramed:(BOOL)arg5 ;
-(void)thumbnailGenerator:(id)arg1 didUpdateStoryThumbnailWithImage:(id)arg2 highlightedImage:(id)arg3 snap:(id)arg4 fromCache:(BOOL)arg5 isFramed:(BOOL)arg6 ;
-(void)thumbnailGenerator:(id)arg1 didLoadMiniThumbnail:(id)arg2 snap:(id)arg3 loadingLatency:(double)arg4 ;
-(void)thumbnailGenerator:(id)arg1 didLoadPosterFrame:(id)arg2 snap:(id)arg3 ;
-(void)thumbnailGenerator:(id)arg1 didLoadThumbnail:(BOOL)arg2 ;
-(void)setGalleryEntry:(id)arg1 targetSize:(CGSize)arg2 userSession:(id)arg3 ;
-(void)_setImage:(id)arg1 snap:(id)arg2 ;
-(void)dealloc;
@end

