/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:36 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCSearchIntentHandler.h>
#import <Snapchat/SCSearchModalPresenterConfigurable.h>

@protocol SCSearchModalPresenting, SCStartChatDelegate;
@class SCSearchNavigationCoordinator, SCGallerySearchActionHandler, SCSearchEventListenerAnnouncer, SCUserSession, NSString;

@interface SCGallerySearchIntentHandler : NSObject <SCSearchIntentHandler, SCSearchModalPresenterConfigurable> {

	SCGallerySearchActionHandler* _gallerySearchActionHandler;
	SCSearchEventListenerAnnouncer* _eventAnnouncer;
	SCUserSession* _userSession;
	SCSearchNavigationCoordinator* _searchNavigationCoordinator;
	id<SCSearchModalPresenting> _searchModalPresenter;
	id<SCStartChatDelegate> _startChatDelegate;

}

@property (assign,nonatomic,__weak) id<SCStartChatDelegate> startChatDelegate;                                //@synthesize startChatDelegate=_startChatDelegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) SCSearchNavigationCoordinator * searchNavigationCoordinator;              //@synthesize searchNavigationCoordinator=_searchNavigationCoordinator - In the implementation block
@property (assign,nonatomic,__weak) id<SCSearchModalPresenting> searchModalPresenter;                         //@synthesize searchModalPresenter=_searchModalPresenter - In the implementation block
+(id)announcerIdentifier;
-(id)initWithUserSession:(id)arg1 ;
-(BOOL)handleIntent:(id)arg1 ;
-(SCSearchNavigationCoordinator *)searchNavigationCoordinator;
-(void)setSearchNavigationCoordinator:(SCSearchNavigationCoordinator *)arg1 ;
-(void)setStartChatDelegate:(id<SCStartChatDelegate>)arg1 ;
-(id<SCStartChatDelegate>)startChatDelegate;
-(void)_chatWithFriend:(id)arg1 ;
-(BOOL)handleIntent:(id)arg1 notification:(id)arg2 ;
-(BOOL)handleIntent:(id)arg1 notification:(id)arg2 notificationDismissed:(BOOL)arg3 ;
-(void)_chatWithGroupId:(id)arg1 ;
-(id<SCSearchModalPresenting>)searchModalPresenter;
-(void)setSearchModalPresenter:(id<SCSearchModalPresenting>)arg1 ;
-(void)addListener:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
@end

