/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:15 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCGallerySnapDetail.h>
@class NSString, SOJUGallerySnapOverlay;


@protocol SCGallerySnapDetail <NSObject,NSCoding,NSCopying>
@property (nonatomic,copy,readonly) NSString * objectID; 
@property (nonatomic,copy,readonly) SOJUGallerySnapOverlay * overlay; 
@required
-(SOJUGallerySnapOverlay *)overlay;
-(NSString *)objectID;

@end


@class NSString, SOJUGallerySnapOverlay;

@interface SCGallerySnapDetail : NSObject <SCGallerySnapDetail> {

	NSString* _objectID;
	SOJUGallerySnapOverlay* _overlay;

}

@property (nonatomic,copy,readonly) NSString * objectID;                           //@synthesize objectID=_objectID - In the implementation block
@property (nonatomic,copy,readonly) SOJUGallerySnapOverlay * overlay;              //@synthesize overlay=_overlay - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)fasterCodingVersion;
+(unsigned long long*)fasterCodingKeys;
+(id)observe:(id)arg1 queue:(id)arg2 changeHandler:(/*^block*/id)arg3 ;
+(id)parseManagedObject:(id)arg1 ;
+(id)fetchGallerySnapDetailForSnap:(id)arg1 options:(id)arg2 ;
+(id)fetchSnapDetailsWithSnaps:(id)arg1 ;
+(id)fetchGallerySnapDetailsWithOptions:(id)arg1 ;
+(unsigned long long)countOfGallerySnapDetailsWithOptions:(id)arg1 ;
+(id)gallerySnapDetailWithOverlay:(id)arg1 ;
+(id)allKeys;
-(BOOL)preferFasterCoding;
-(void)encodeWithFasterCoder:(id)arg1 ;
-(void)decodeWithFasterDecoder:(id)arg1 ;
-(void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2 ;
-(id)initWithObjectID:(id)arg1 overlay:(id)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(SOJUGallerySnapOverlay *)overlay;
-(NSString *)objectID;
@end

