/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:35 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCSyncFileResolver.h>

@class NSString, SCUserSession;

@interface SCGalleryFilePathManager : NSObject <SCSyncFileResolver> {

	NSString* _rootStoragePathComponent;
	SCUserSession* _userSession;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)clearGalleryCacheData;
+(id)galleryUniqueJPGFileURLInCacheDirectoryWithPrefix:(id)arg1 ;
+(id)galleryUniqueMP4FileURLInCacheDirectoryWithPrefix:(id)arg1 ;
+(void)clearGalleryMediaExceptUserId:(id)arg1 ;
-(void)removeAllData;
-(id)initWithUserSession:(id)arg1 ;
-(id)renderedLowresMediaCachedURLForSnap:(id)arg1 ;
-(id)mediaCachedURLForSnap:(id)arg1 ;
-(id)mediaCachedOverlayURLForSnap:(id)arg1 ;
-(id)mediaCachedOverlayEntityURLForSnap:(id)arg1 ;
-(id)HDMediaCachedURLForSnap:(id)arg1 ;
-(id)renderedLowresMediaForSnap:(id)arg1 detail:(id)arg2 ;
-(id)rootDocumentURL;
-(void)_claimDocumentDirectoryWithUserId:(id)arg1 ;
-(id)rootCacheURL;
@end

