/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:15 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SCCDGalleryProfile, SCObjectPlaceholder, NSString, NSDate;

@interface SCGalleryProfileChangeRequest : NSObject {

	SCCDGalleryProfile* _galleryProfile;
	SCObjectPlaceholder* _objectPlaceholder;

}

@property (nonatomic,readonly) SCObjectPlaceholder * placeholderForCreatedGalleryProfile; 
@property (nonatomic,copy,readonly) NSString * objectID; 
@property (nonatomic,copy) NSDate * lastBackupNotificationTime; 
@property (nonatomic,copy) NSDate * lastFeaturedStorySyncTime; 
@property (nonatomic,copy) NSDate * lastFullSyncTime; 
@property (assign,nonatomic) long long lastUpdateSeqNum; 
@property (assign,nonatomic) BOOL privateGalleryEnabled; 
@property (assign,nonatomic) int snapTotalQuota; 
@property (nonatomic,copy) NSString * syncToken; 
@property (assign,nonatomic) BOOL topSecretPrivateGalleryEnabled; 
@property (nonatomic,copy) NSString * userId; 
+(id)changeRequestForGalleryProfile:(id)arg1 ;
+(id)creationRequestWithGalleryProfile:(id)arg1 ;
+(void)deleteGalleryProfiles:(id)arg1 ;
+(void)deleteAllGalleryProfiles;
-(BOOL)privateGalleryEnabled;
-(BOOL)topSecretPrivateGalleryEnabled;
-(void)addSnaps:(id)arg1 ;
-(void)removeSnaps:(id)arg1 ;
-(long long)lastUpdateSeqNum;
-(void)setLastUpdateSeqNum:(long long)arg1 ;
-(void)setPrivateGalleryEnabled:(BOOL)arg1 ;
-(int)snapTotalQuota;
-(void)setSnapTotalQuota:(int)arg1 ;
-(void)setTopSecretPrivateGalleryEnabled:(BOOL)arg1 ;
-(NSDate *)lastBackupNotificationTime;
-(NSDate *)lastFeaturedStorySyncTime;
-(NSDate *)lastFullSyncTime;
-(void)setLastBackupNotificationTime:(NSDate *)arg1 ;
-(void)setLastFeaturedStorySyncTime:(NSDate *)arg1 ;
-(void)setLastFullSyncTime:(NSDate *)arg1 ;
-(id)initWithGalleryProfile:(id)arg1 ;
-(void)addDeletedEntries:(id)arg1 ;
-(void)removeDeletedEntries:(id)arg1 ;
-(void)addDeletedSnaps:(id)arg1 ;
-(void)removeDeletedSnaps:(id)arg1 ;
-(void)addFailedEntries:(id)arg1 ;
-(void)removeFailedEntries:(id)arg1 ;
-(void)removeOperations:(id)arg1 ;
-(void)setQuotaStatus:(id)arg1 ;
-(SCObjectPlaceholder *)placeholderForCreatedGalleryProfile;
-(void)setWithGalleryProfile:(id)arg1 ;
-(void)setUserDefaults:(id)arg1 ;
-(void)addEntries:(id)arg1 ;
-(void)removeEntries:(id)arg1 ;
-(NSString *)userId;
-(void)setUserId:(NSString *)arg1 ;
-(NSString *)objectID;
-(NSString *)syncToken;
-(void)setSyncToken:(NSString *)arg1 ;
-(void)addOperations:(id)arg1 ;
@end

