/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:28 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCBaseMediaMessage.h>

@class FLAnimatedImage;

@interface SCGifMediaMessage : SCBaseMediaMessage {

	FLAnimatedImage* _gif;

}

@property (nonatomic,retain) FLAnimatedImage * gif;              //@synthesize gif=_gif - In the implementation block
-(id)cacheId;
-(void)gifWithCompletionHandler:(/*^block*/id)arg1 ;
-(id)sendJSON;
-(id)initWithUsername:(id)arg1 dictionary:(id)arg2 ;
-(id)initWithData:(id)arg1 sender:(id)arg2 recipient:(id)arg3 ;
-(/*^block*/id)uploadSuccessBlock;
-(/*^block*/id)uploadFailureBlock;
-(BOOL)isMediaDataLoadedInCache;
-(id)trackingMediaTypeForMedia:(id)arg1 ;
-(void)fetchMediaDidSucceedForMedia:(id)arg1 ;
-(BOOL)containsGif;
-(long long)scaMediaType;
-(void)setGif:(FLAnimatedImage *)arg1 ;
-(FLAnimatedImage *)gif;
-(void)gifFromCache:(/*^block*/id)arg1 ;
-(long long)mediaType;
-(long long)messageType;
-(void)upload;
@end

