/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:36 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SCGroupStoriesStringHelper : NSObject
+(id)customStoryDescriptionTextForNames:(id)arg1 font:(id)arg2 maxWidth:(double)arg3 ;
+(id)customStoryDescriptionTextForNames:(id)arg1 numOthers:(unsigned long long)arg2 ;
+(id)croppedCustomStoryDescriptionTextForNames:(id)arg1 numOthers:(unsigned long long)arg2 font:(id)arg3 maxWidth:(double)arg4 ;
+(id)groupStoryDescriptionTextForNames:(id)arg1 font:(id)arg2 maxWidth:(double)arg3 ;
@end

