/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:30 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCGenericSettingsViewController.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>
#import <Snapchat/SCGroupStorySelectMembersViewControllerDelegate.h>
#import <Snapchat/SCSendViewControllerNavigationDelegate.h>

@protocol SCGroupStorySettingsViewControllerDelegate;
@class SCUserSession, UITableView, UILabel, NSArray, SCGroupStoryCreationSettings, SCGroupStoryCreationSession, SCSearchContainerView, SCSendToTransitionProvider, NSString;

@interface SCGroupStoryCreateOptionsViewController : SCGenericSettingsViewController <UITableViewDataSource, UITableViewDelegate, SCGroupStorySelectMembersViewControllerDelegate, SCSendViewControllerNavigationDelegate> {

	SCUserSession* _userSession;
	UITableView* _tableView;
	UILabel* _footerLabel;
	NSArray* _sections;
	SCGroupStoryCreationSettings* _creationSettings;
	SCGroupStoryCreationSession* _creationSession;
	id<SCGroupStorySettingsViewControllerDelegate> _settingsVCDelegate;
	SCSearchContainerView* _blurredContainerView;
	SCSendToTransitionProvider* _sendToTransitionProvider;
	BOOL _limitToGroupChatStory;
	BOOL _dismissChildVCAnimated;
	long long _context;

}

@property (assign,nonatomic) long long context;                     //@synthesize context=_context - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)leftButtonPressed;
-(id)imageForLeftButtonInState:(unsigned long long)arg1 ;
-(id)backgroundColorForHeader;
-(id)textColorForHeader:(id)arg1 ;
-(void)leftSwipeSucceed;
-(id)getTitle;
-(void)dismissSendViewController:(id)arg1 ;
-(id)_sectionsTemplate;
-(long long)_createTypeForIndex:(unsigned long long)arg1 ;
-(void)_createCustomStory;
-(void)_createGeoStory;
-(void)_createPrivateStory;
-(void)_createGroupChatStory;
-(id)_customStoryCellAtIndexPath:(id)arg1 ;
-(id)_geoStoryCellAtIndexPath:(id)arg1 ;
-(id)_privateStoryCellAtIndexPath:(id)arg1 ;
-(id)_groupChatStoryCellAtIndexPath:(id)arg1 ;
-(UIEdgeInsets)_createOptionCellEdgeInsets;
-(void)_presentMemberSelectorWithStoryType:(long long)arg1 selectingPosters:(BOOL)arg2 ;
-(void)_logCreationSession;
-(void)newGroupStorySelectMembersViewController:(id)arg1 updateCustomGroupStoryPrivacyWithPosterIds:(id)arg2 viewerIds:(id)arg3 modifiedSettings:(BOOL)arg4 storyType:(long long)arg5 ;
-(id)initWithCreationContext:(long long)arg1 userSession:(id)arg2 settingsDelegate:(id)arg3 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(long long)preferredStatusBarStyle;
-(long long)context;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)updateViewConstraints;
-(void)setContext:(long long)arg1 ;
@end

