/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:13 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIImpactFeedbackGenerator, UISelectionFeedbackGenerator, UINotificationFeedbackGenerator;

@interface SCHapticsManager : NSObject {

	UIImpactFeedbackGenerator* _generatorImpactLight;
	UIImpactFeedbackGenerator* _generatorImpactMedium;
	UIImpactFeedbackGenerator* _generatorImpactHeavy;
	UISelectionFeedbackGenerator* _generatorSelection;
	UINotificationFeedbackGenerator* _generatorNotification;

}

@property (nonatomic,retain) UIImpactFeedbackGenerator * generatorImpactLight;                     //@synthesize generatorImpactLight=_generatorImpactLight - In the implementation block
@property (nonatomic,retain) UIImpactFeedbackGenerator * generatorImpactMedium;                    //@synthesize generatorImpactMedium=_generatorImpactMedium - In the implementation block
@property (nonatomic,retain) UIImpactFeedbackGenerator * generatorImpactHeavy;                     //@synthesize generatorImpactHeavy=_generatorImpactHeavy - In the implementation block
@property (nonatomic,retain) UISelectionFeedbackGenerator * generatorSelection;                    //@synthesize generatorSelection=_generatorSelection - In the implementation block
@property (nonatomic,retain) UINotificationFeedbackGenerator * generatorNotification;              //@synthesize generatorNotification=_generatorNotification - In the implementation block
+(id)sharedManager;
-(UISelectionFeedbackGenerator *)generatorSelection;
-(UINotificationFeedbackGenerator *)generatorNotification;
-(UIImpactFeedbackGenerator *)generatorImpactHeavy;
-(UIImpactFeedbackGenerator *)generatorImpactMedium;
-(UIImpactFeedbackGenerator *)generatorImpactLight;
-(void)performFeedback:(long long)arg1 ;
-(void)performGatedFeedback:(long long)arg1 ;
-(void)hapticUserInteractionStarted;
-(void)hapticUserInteractionEnded;
-(void)setGeneratorImpactLight:(UIImpactFeedbackGenerator *)arg1 ;
-(void)setGeneratorImpactMedium:(UIImpactFeedbackGenerator *)arg1 ;
-(void)setGeneratorImpactHeavy:(UIImpactFeedbackGenerator *)arg1 ;
-(void)setGeneratorSelection:(UISelectionFeedbackGenerator *)arg1 ;
-(void)setGeneratorNotification:(UINotificationFeedbackGenerator *)arg1 ;
-(void)prepare;
@end

