/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:53 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIView.h>

@class UIImageView, UIView, UILabel, NSString;

@interface SCHovaTabBarItemView : UIView {

	UIImageView* _imageView;
	UIView* _imageBadgeView;
	CGAffineTransform _pendingImageViewTransform;
	double _pendingImageViewAlpha;
	double _pendingBadgeViewAlpha;
	double _pendingDarkModeImageViewAlpha;
	BOOL _verticallyVisible;
	long long _itemType;
	UILabel* _hintLabel;
	UIView* _cameraPageView;
	UIImageView* _cameraPageImageView;
	UIView* _circleView;
	NSString* _backgroundImageName;
	long long _interfaceStyle;
	double _percentVisible;
	UIView* _selectedView;
	long long _badgeCount;
	UIView* _cameraPageImageBadgeView;
	UIImageView* _backgroundImageView;
	UIImageView* _darkModeImageView;
	UIView* _darkModeImageBadgeView;
	NSString* _darkModeImageName;

}

@property (nonatomic,retain) UIView * cameraPageView;                                          //@synthesize cameraPageView=_cameraPageView - In the implementation block
@property (nonatomic,retain) UIView * circleView;                                              //@synthesize circleView=_circleView - In the implementation block
@property (nonatomic,retain) UILabel * hintLabel;                                              //@synthesize hintLabel=_hintLabel - In the implementation block
@property (nonatomic,retain) UIImageView * cameraPageImageView;                                //@synthesize cameraPageImageView=_cameraPageImageView - In the implementation block
@property (nonatomic,retain) UIView * cameraPageImageBadgeView;                                //@synthesize cameraPageImageBadgeView=_cameraPageImageBadgeView - In the implementation block
@property (getter=isBadged,nonatomic,readonly) BOOL badged; 
@property (nonatomic,retain) UIImageView * backgroundImageView;                                //@synthesize backgroundImageView=_backgroundImageView - In the implementation block
@property (nonatomic,retain) NSString * backgroundImageName;                                   //@synthesize backgroundImageName=_backgroundImageName - In the implementation block
@property (nonatomic,retain) UIImageView * darkModeImageView;                                  //@synthesize darkModeImageView=_darkModeImageView - In the implementation block
@property (nonatomic,retain) UIView * darkModeImageBadgeView;                                  //@synthesize darkModeImageBadgeView=_darkModeImageBadgeView - In the implementation block
@property (nonatomic,retain) NSString * darkModeImageName;                                     //@synthesize darkModeImageName=_darkModeImageName - In the implementation block
@property (nonatomic,readonly) long long itemType;                                             //@synthesize itemType=_itemType - In the implementation block
@property (nonatomic,readonly) UIImageView * imageView; 
@property (assign,nonatomic) long long interfaceStyle;                                         //@synthesize interfaceStyle=_interfaceStyle - In the implementation block
@property (getter=isVerticallyVisible,nonatomic,readonly) BOOL verticallyVisible;              //@synthesize verticallyVisible=_verticallyVisible - In the implementation block
@property (assign,nonatomic) double percentVisible;                                            //@synthesize percentVisible=_percentVisible - In the implementation block
@property (nonatomic,readonly) double cameraViewWidth; 
@property (nonatomic,retain) UIView * selectedView;                                            //@synthesize selectedView=_selectedView - In the implementation block
@property (assign,nonatomic) long long badgeCount;                                             //@synthesize badgeCount=_badgeCount - In the implementation block
+(id)chatTabBarView;
+(id)storiesTabBarView;
+(id)captureTabBarView;
+(id)memoriesTabBarView;
+(id)playButtonTabBarView;
+(id)_genBadgeCircleViewForImageView:(id)arg1 scaleFactor:(double)arg2 alpha:(double)arg3 itemType:(long long)arg4 ;
-(long long)interfaceStyle;
-(void)setInterfaceStyle:(long long)arg1 ;
-(BOOL)isBadged;
-(double)percentVisible;
-(void)setPercentVisible:(double)arg1 ;
-(void)setSelectedView:(UIView *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 itemType:(long long)arg2 ;
-(void)setVerticallyVisible:(BOOL)arg1 ;
-(void)setBackgroundImageName:(NSString *)arg1 ;
-(void)setDarkModeImageName:(NSString *)arg1 ;
-(BOOL)isVerticallyVisible;
-(UIImageView *)cameraPageImageView;
-(UIView *)cameraPageView;
-(double)cameraViewWidth;
-(UIImageView *)darkModeImageView;
-(void)setImageViewAlpha:(double)arg1 ;
-(void)setDarkModeImageViewAlpha:(double)arg1 ;
-(CGSize)imageViewSize;
-(void)setImageViewTransform:(CGAffineTransform)arg1 ;
-(BOOL)isDarkModeImageViewLoaded;
-(void)setCameraPageImageBadgeView:(UIView *)arg1 ;
-(UIView *)cameraPageImageBadgeView;
-(id)_genBadgeCircleViewForImageView:(id)arg1 scaleFactor:(double)arg2 ;
-(NSString *)darkModeImageName;
-(void)updateImageViewsAndLayout;
-(void)showHintLabelWithText:(id)arg1 ;
-(BOOL)isImageViewLoaded;
-(void)setCameraPageView:(UIView *)arg1 ;
-(void)setCameraPageImageView:(UIImageView *)arg1 ;
-(void)setDarkModeImageView:(UIImageView *)arg1 ;
-(UIView *)darkModeImageBadgeView;
-(void)setDarkModeImageBadgeView:(UIView *)arg1 ;
-(void)layoutSubviews;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(UIImageView *)backgroundImageView;
-(UIImageView *)imageView;
-(id)fillColor;
-(BOOL)isAccessibilityElement;
-(NSString *)backgroundImageName;
-(long long)itemType;
-(UIView *)selectedView;
-(void)setHintLabel:(UILabel *)arg1 ;
-(UILabel *)hintLabel;
-(void)setBadgeCount:(long long)arg1 ;
-(long long)badgeCount;
-(UIView *)circleView;
-(void)setCircleView:(UIView *)arg1 ;
-(void)setBackgroundImageView:(UIImageView *)arg1 ;
@end

