/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:14 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SCImageProcessToneCurve : NSObject {

	char* _toneCurve;

}

@property (nonatomic,readonly) char* toneCurve;              //@synthesize toneCurve=_toneCurve - In the implementation block
+(id)_generatePreparedSplineCurve:(id)arg1 ;
+(id)_splineCurve:(id)arg1 ;
+(id)_secondDerivative:(id)arg1 ;
-(char*)toneCurve;
-(id)initWithDefaultCurve:(id)arg1 RGBCompositeCurve:(id)arg2 ;
-(void)dealloc;
@end

