/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:15 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SCLagunaRemoteFile : NSObject {

	NSString* _contentName;
	unsigned long long _type;
	long long _size;

}

@property (nonatomic,copy,readonly) NSString * contentName;              //@synthesize contentName=_contentName - In the implementation block
@property (nonatomic,readonly) unsigned long long type;                  //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) long long size;                           //@synthesize size=_size - In the implementation block
-(NSString *)contentName;
-(id)remoteFilename;
-(id)initWithRemoteFilename:(id)arg1 size:(long long)arg2 ;
-(id)initWithRemoteContentName:(id)arg1 type:(unsigned long long)arg2 size:(long long)arg3 ;
-(long long)size;
-(id)description;
-(unsigned long long)type;
@end

