/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:38 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/LSAEffectComponentListener.h>
#import <Snapchat/SCLensUIUpdateListener.h>

@protocol SCLensHintPresenterDelegate;
@class UILabel, SCLensHintProvider, SCLens, NSString;

@interface SCLensHintPresenter : NSObject <LSAEffectComponentListener, SCLensUIUpdateListener> {

	/*^block*/id _hintLabelInitializationBlock;
	UILabel* _lensHintLabel;
	SCLensHintProvider* _hintProvider;
	BOOL _lensesActive;
	SCLens* _selectedLens;
	id<SCLensHintPresenterDelegate> _delegate;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)effectComponent:(id)arg1 willTurnOnEffectWithId:(id)arg2 ;
-(void)effectComponent:(id)arg1 didTurnOnEffectWithId:(id)arg2 features:(unsigned long long)arg3 ;
-(void)effectComponent:(id)arg1 willTurnOffEffectWithId:(id)arg2 features:(unsigned long long)arg3 ;
-(void)effectComponent:(id)arg1 didTurnOffEffectWithId:(id)arg2 features:(unsigned long long)arg3 ;
-(void)effectComponent:(id)arg1 effectId:(id)arg2 showHintWithId:(id)arg3 ;
-(void)effectComponent:(id)arg1 hideAllHintsForEffectWithId:(id)arg2 ;
-(void)effectComponent:(id)arg1 effectId:(id)arg2 performHapticFeedback:(unsigned long long)arg3 ;
-(void)effectComponent:(id)arg1 effectId:(id)arg2 showPopUpHintWithId:(id)arg3 interfaceElement:(unsigned long long)arg4 ;
-(void)effectComponent:(id)arg1 effectId:(id)arg2 performInterfaceAction:(unsigned long long)arg3 interfaceElement:(unsigned long long)arg4 interfaceData:(id)arg5 ;
-(void)effectComponent:(id)arg1 loadPersistentStoreForEffectWithId:(id)arg2 ;
-(void)effectComponent:(id)arg1 effectId:(id)arg2 savePersistentStore:(id)arg3 ;
-(void)effectComponent:(id)arg1 didInstantiatedEffectWithId:(id)arg2 isFromCache:(BOOL)arg3 ;
-(void)willShowLenses;
-(void)didHideLenses;
-(void)didUpdateActiveLensOrder:(id)arg1 ;
-(void)didSelectLens:(id)arg1 ;
-(void)willDisplayLens:(id)arg1 ;
-(void)didEndDisplayingLens:(id)arg1 ;
-(void)hideLensHintAnimated:(BOOL)arg1 ;
-(id)lensHintLabel;
-(void)showHintWithId:(id)arg1 lens:(id)arg2 animated:(BOOL)arg3 autohide:(BOOL)arg4 ;
-(id)initWithHintLabelBlock:(/*^block*/id)arg1 hintProvider:(id)arg2 delegate:(id)arg3 ;
@end

