/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:59 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@class SCLensSbSnappable, NSMutableArray, NSString;

@interface SCLensSbSnappableMessage : GPBMessage

@property (nonatomic,retain) SCLensSbSnappable * snappable; 
@property (assign,nonatomic) BOOL hasSnappable; 
@property (nonatomic,retain) NSMutableArray * mediaArray; 
@property (nonatomic,readonly) unsigned long long mediaArray_Count; 
@property (nonatomic,copy) NSString * effectId; 
@property (nonatomic,retain) NSMutableArray * userIdsArray; 
@property (nonatomic,readonly) unsigned long long userIdsArray_Count; 
@property (assign,nonatomic) float focusPointX; 
@property (assign,nonatomic) float focusPointY; 
@property (assign,nonatomic) float focusPointWidth; 
@property (assign,nonatomic) int replyType; 
+(id)sc_initWithBase64String:(id)arg1 error:(id*)arg2 ;
+(id)descriptor;
-(id)sc_prefetchableAssetsWithOrigin:(unsigned long long)arg1 ;
-(void)sc_encryptUsingKey:(id)arg1 iv:(id)arg2 ;
-(void)sc_decryptUsingKey:(id)arg1 iv:(id)arg2 ;
@end

