/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:38 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCLensDownloadOperationV2.h>

@class SCLensCategory, SCLensURLDataFetcher, SCLensSecurity;

@interface SCLensCategoryDownloadOperationV2 : SCLensDownloadOperationV2 {

	SCLensCategory* _category;
	SCLensURLDataFetcher* _urlDataFetcher;
	SCLensSecurity* _signatureValidator;

}

@property (nonatomic,retain) SCLensURLDataFetcher * urlDataFetcher;              //@synthesize urlDataFetcher=_urlDataFetcher - In the implementation block
@property (nonatomic,retain) SCLensSecurity * signatureValidator;                //@synthesize signatureValidator=_signatureValidator - In the implementation block
@property (nonatomic,readonly) SCLensCategory * category;                        //@synthesize category=_category - In the implementation block
-(void)executeWithSettings:(id)arg1 ;
-(void)boostWithSettings:(id)arg1 ;
-(SCLensURLDataFetcher *)urlDataFetcher;
-(SCLensSecurity *)signatureValidator;
-(void)setUrlDataFetcher:(SCLensURLDataFetcher *)arg1 ;
-(void)setSignatureValidator:(SCLensSecurity *)arg1 ;
-(void)processDataFetcherResponseForUrl:(id)arg1 contentPath:(id)arg2 cached:(BOOL)arg3 inputSettings:(id)arg4 error:(id)arg5 ;
-(void)verifySignatureForContentAtPath:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)initWithLens:(id)arg1 requestTiming:(long long)arg2 category:(id)arg3 urlDataFetcher:(id)arg4 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(SCLensCategory *)category;
-(void)finishWithResult:(id)arg1 ;
@end

