/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:38 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCExperimentContext.h>

@class NSString;

@interface SCLensRegressorExperimentContext : SCExperimentContext {

	NSString* _trackingResourcesTag;
	NSString* _trackingResourcesChecksum;

}

@property (nonatomic,retain) NSString * trackingResourcesTag;                   //@synthesize trackingResourcesTag=_trackingResourcesTag - In the implementation block
@property (nonatomic,retain) NSString * trackingResourcesChecksum;              //@synthesize trackingResourcesChecksum=_trackingResourcesChecksum - In the implementation block
-(void)setupParameters;
-(NSString *)trackingResourcesTag;
-(void)setTrackingResourcesTag:(NSString *)arg1 ;
-(NSString *)trackingResourcesChecksum;
-(void)setTrackingResourcesChecksum:(NSString *)arg1 ;
-(id)experimentName;
@end

