/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:38 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCLensAssetDownloadOperationV2.h>

@class SCLensBlobDataFetcher;

@interface SCLensUserGeneratedRemoteAssetDownloadOperationV2 : SCLensAssetDownloadOperationV2 {

	SCLensBlobDataFetcher* _blobDataFetcher;

}

@property (nonatomic,retain) SCLensBlobDataFetcher * blobDataFetcher;              //@synthesize blobDataFetcher=_blobDataFetcher - In the implementation block
-(void)executeWithSettings:(id)arg1 ;
-(void)boostWithSettings:(id)arg1 ;
-(SCLensBlobDataFetcher *)blobDataFetcher;
-(id)initWithLens:(id)arg1 requestTiming:(long long)arg2 asset:(id)arg3 blobDataFetcher:(id)arg4 ;
-(void)setBlobDataFetcher:(SCLensBlobDataFetcher *)arg1 ;
@end

