/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:38 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCLensCarouselPresenterDelegate <NSObject>
@required
-(void)lensCarouselPresenter:(id)arg1 didSelectLens:(id)arg2 index:(unsigned long long)arg3 originalLensIndex:(unsigned long long)arg4 totalLensesCount:(unsigned long long)arg5;
-(BOOL)lensCarouselPresenter:(id)arg1 isLensBeingApplied:(id)arg2;
-(void)lensCarouselPresenter:(id)arg1 willDisplayLens:(id)arg2;
-(void)lensCarouselPresenter:(id)arg1 didEndDisplayingLens:(id)arg2;
-(void)lensCarouselPresenter:(id)arg1 didScroll:(id)arg2 selectedCellDistance:(double)arg3 selectedLens:(id)arg4;
-(void)lensCarouselPresenter:(id)arg1 didEndScrolling:(id)arg2 atLens:(id)arg3;
-(void)lensCarouselPresenter:(id)arg1 didUpdateLensesList:(id)arg2;

@end

