/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:15 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCService.h>

@protocol SCGalleryProfile, SCProgressReportingSCCanceling;
@class SCCloudSync, SCCloudFS, SCQueuePerformer, SCCloudFSFile, SCSentinel, NSArray, NSString;

@interface SCLowresMediaFilePreloader : NSObject <SCService> {

	id<SCGalleryProfile> _profile;
	SCCloudSync* _cloudSync;
	SCCloudFS* _cloudFS;
	unsigned long long _status;
	SCQueuePerformer* _performer;
	SCCloudFSFile* _currentCloudFile;
	id<SCProgressReporting><SCCanceling> _currentDownloadRequest;
	SCSentinel* _invalidateSentinel;
	NSArray* _pendingEntries;
	NSArray* _pendingSnaps;
	long long _entryIndex;
	long long _snapIndex;
	long long _processedSnapCount;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)dedicatedQueue;
-(void)runWithServiceTerm:(id)arg1 ;
-(void)_transitToState:(unsigned long long)arg1 serviceTerm:(id)arg2 ;
-(id)defaultLongRunningNotifier;
-(id)defaultImmediateNotifier;
-(id)_notifierWithCloudSyncReadyNotifier:(double)arg1 ;
-(void)_fetchAllEntriesWithServiceTerm:(id)arg1 ;
-(void)_processEntryWithServiceTerm:(id)arg1 ;
-(void)_downloadLowresMediaWithServiceTerm:(id)arg1 ;
-(id)_fileDownloadingNotifier;
-(void)_continueDownloadSnapsWithServiceTerm:(id)arg1 ;
-(id)initWithProfile:(id)arg1 cloudSync:(id)arg2 cloudFS:(id)arg3 ;
-(void)invalidate;
-(BOOL)_isInvalidated;
@end

