/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:41 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIViewController.h>
#import <Snapchat/SCPassthroughDataSource.h>
#import <Snapchat/SCTimeProfilable.h>
#import <Snapchat/SCMapHeaderViewDelegate.h>
#import <Snapchat/MGLMapViewDelegate.h>
#import <Snapchat/SCSearchViewDelegate.h>

@class SCPassthroughView, SCMapCompassButton, CALayer, SCUserSession, SCMapView, SCMapHeaderView, UIView, SCMapTimeAndWeatherView, CLLocation, NSString;

@interface SCMapBaseViewController : UIViewController <SCPassthroughDataSource, SCTimeProfilable, SCMapHeaderViewDelegate, MGLMapViewDelegate, SCSearchViewDelegate> {

	SCPassthroughView* _cameraButton;
	SCMapCompassButton* _compassButton;
	CALayer* _searchGradientLayer;
	SCUserSession* _userSession;
	SCMapView* _mapView;
	SCMapHeaderView* _headerView;
	UIView* _toolbarView;
	UIView* _localTimeAndWeatherViewContainer;
	SCMapTimeAndWeatherView* _localTimeAndWeatherView;
	UIView* _originalCameraTimer;

}

@property (nonatomic,readonly) SCMapView * mapView;                                            //@synthesize mapView=_mapView - In the implementation block
@property (nonatomic,readonly) SCMapHeaderView * headerView;                                   //@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,readonly) UIView * toolbarView;                                           //@synthesize toolbarView=_toolbarView - In the implementation block
@property (nonatomic,readonly) UIView * cameraButton;                                          //@synthesize cameraButton=_cameraButton - In the implementation block
@property (nonatomic,readonly) SCMapCompassButton * compassButton;                             //@synthesize compassButton=_compassButton - In the implementation block
@property (nonatomic,readonly) UIView * localTimeAndWeatherViewContainer;                      //@synthesize localTimeAndWeatherViewContainer=_localTimeAndWeatherViewContainer - In the implementation block
@property (nonatomic,readonly) SCMapTimeAndWeatherView * localTimeAndWeatherView;              //@synthesize localTimeAndWeatherView=_localTimeAndWeatherView - In the implementation block
@property (assign,nonatomic,__weak) UIView * originalCameraTimer;                              //@synthesize originalCameraTimer=_originalCameraTimer - In the implementation block
@property (nonatomic,readonly) SCUserSession * userSession;                                    //@synthesize userSession=_userSession - In the implementation block
@property (nonatomic,readonly) CLLocation * userLocation; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(int)context;
-(id)hitTest:(CGPoint)arg1 forPassthroughView:(id)arg2 ;
-(id)initWithUserSession:(id)arg1 ;
-(void)_didTapOnBackButton;
-(void)mapHeaderViewDidTapOnBackButton:(id)arg1 ;
-(void)_setupHeaderView;
-(UIView *)cameraButton;
-(void)setOriginalCameraTimer:(UIView *)arg1 ;
-(void)_setupMapboxView;
-(void)_setupToolbarView;
-(SCMapCompassButton *)compassButton;
-(SCMapTimeAndWeatherView *)localTimeAndWeatherView;
-(UIView *)localTimeAndWeatherViewContainer;
-(BOOL)mapViewHasActiveGesture;
-(void)_didTouchCameraButton;
-(UIView *)originalCameraTimer;
-(long long)preferredStatusBarStyle;
-(BOOL)prefersStatusBarHidden;
-(long long)preferredStatusBarUpdateAnimation;
-(unsigned long long)supportedInterfaceOrientations;
-(BOOL)shouldAutorotate;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillLayoutSubviews;
-(long long)preferredInterfaceOrientationForPresentation;
-(void)viewDidLoad;
-(SCMapHeaderView *)headerView;
-(SCUserSession *)userSession;
-(CLLocation *)userLocation;
-(SCMapView *)mapView;
-(UIView *)toolbarView;
@end

