/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:40 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SCMapSerialAsyncBlockPerformerBlockWrapper : NSObject {

	/*^block*/id _block;
	/*^block*/id _canceledBlock;

}

@property (nonatomic,copy) id block;                      //@synthesize block=_block - In the implementation block
@property (nonatomic,copy) id canceledBlock;              //@synthesize canceledBlock=_canceledBlock - In the implementation block
-(void)setCanceledBlock:(id)arg1 ;
-(id)canceledBlock;
-(void)setBlock:(id)arg1 ;
-(id)block;
@end

