/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:00 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@class SCMETravelAction_Location, NSString;

@interface SCMETravelAction : GPBMessage

@property (nonatomic,retain) SCMETravelAction_Location * startLocation; 
@property (assign,nonatomic) BOOL hasStartLocation; 
@property (nonatomic,retain) SCMETravelAction_Location * endLocation; 
@property (assign,nonatomic) BOOL hasEndLocation; 
@property (nonatomic,copy) NSString * mode; 
@property (assign,nonatomic) double speed; 
@property (assign,nonatomic) double distance; 
@property (assign,nonatomic) long long duration; 
+(id)descriptor;
@end

