/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:13 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIApplication, SCObservable, SCDisposableObserverLifecycle, NSOperationQueue;

@interface SCNotificationBadgeUpdater : NSObject {

	UIApplication* _application;
	/*function pointer*/void* _badgeableContentDetector;
	SCObservable* _friendsFeedItems;
	SCDisposableObserverLifecycle* _disposableLifecycle;
	NSOperationQueue* _utilityQueue;

}
-(id)initWithApplication:(id)arg1 badgeableContentDetector:(/*function pointer*/void*)arg2 friendsFeedItems:(id)arg3 ;
-(void)startMonitoringFeedItemUpdates;
@end

