/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:33 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <UIKit/UITableViewDataSource.h>
#import <UIKit/UITableViewDelegate.h>

@protocol SCOAuth2ContentViewDelegate;
@class SCOAuth2ViewModel, UITableView, UIImageView, UILabel, SCButton, NSMutableSet, SCAlertViewActionButton, NSString;

@interface SCOAuth2ContentView : UIView <UITableViewDataSource, UITableViewDelegate> {

	SCOAuth2ViewModel* _viewModel;
	id<SCOAuth2ContentViewDelegate> _delegate;
	UITableView* _tableView;
	UIImageView* _appImageView;
	UILabel* _titleLabel;
	UILabel* _actionDescriptionLabel;
	SCButton* _continueButton;
	UILabel* _otherLabel;
	UIImageView* _avatarImageView;
	NSMutableSet* _permissions;
	SCAlertViewActionButton* _cancelButton;
	UILabel* _cancelLabel;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)initTableView;
-(id)initWithViewModel:(id)arg1 delegate:(id)arg2 ;
-(void)initImageView;
-(void)initTitleLabel;
-(void)initActionDescriptionLabel;
-(void)initOtherLabel;
-(void)initCancelButton;
-(void)initContinueButton;
-(void)initBitmojiAvatar;
-(void)otherButtonPressed;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(long long)numberOfSectionsInTableView:(id)arg1 ;
-(void)switchChanged:(id)arg1 ;
-(void)continueButtonPressed;
@end

