/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:18 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, NSMutableSet;

@interface SCOnDemandGeofilterCreativeSafeZoneView : UIView {

	UILabel* _warningLabel;
	NSMutableSet* _viewsInFrame;
	double _backgroundAlpha;

}
-(BOOL)_safeZoneContainsObjectFrame:(CGRect)arg1 ;
-(void)_updateViewForState:(long long)arg1 ;
-(void)_hideSafeZone;
-(void)_showSafeZoneWithLabel:(BOOL)arg1 ;
-(void)updateBackGroundAlpha:(double)arg1 ;
-(void)respondToGesture:(id)arg1 ;
-(void)clearObjectReferencesInSafeZone;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)warningLabel;
@end

