/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:19 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIControl.h>
#import <UIKit/UIPickerViewDataSource.h>
#import <UIKit/UIPickerViewDelegate.h>

@protocol SCOnDemandGeofilterDatePickerDelegate;
@class NSDate, UIPickerView, NSCalendar, NSString;

@interface SCOnDemandGeofilterDatePicker : UIControl <UIPickerViewDataSource, UIPickerViewDelegate> {

	NSDate* _earliestPresentedDate;
	UIPickerView* _pickerView;
	NSCalendar* _calendar;
	id<SCOnDemandGeofilterDatePickerDelegate> _datePickerDelegate;
	NSDate* _date;
	NSDate* _minimumDate;
	NSDate* _maximumDate;

}

@property (assign,nonatomic,__weak) id<SCOnDemandGeofilterDatePickerDelegate> datePickerDelegate;              //@synthesize datePickerDelegate=_datePickerDelegate - In the implementation block
@property (nonatomic,retain) NSDate * date;                                                                    //@synthesize date=_date - In the implementation block
@property (nonatomic,retain) NSDate * minimumDate;                                                             //@synthesize minimumDate=_minimumDate - In the implementation block
@property (nonatomic,retain) NSDate * maximumDate;                                                             //@synthesize maximumDate=_maximumDate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)nextRoundHour:(id)arg1 ;
+(id)dateByHoursFromNow:(long long)arg1 ;
+(BOOL)requiresConstraintBasedLayout;
-(id)_toComponents:(id)arg1 ;
-(long long)rollNumber:(long long)arg1 toReminder:(long long)arg2 modulo:(long long)arg3 inTheDirection:(long long)arg4 ;
-(void)selectRowsForDay:(long long)arg1 Hour:(long long)arg2 Meridiem:(long long)arg3 animated:(BOOL)arg4 ;
-(long long)_daysBetweenDate:(id)arg1 andDate:(id)arg2 ;
-(BOOL)_regularizeDate:(id)arg1 ;
-(id<SCOnDemandGeofilterDatePickerDelegate>)datePickerDelegate;
-(void)setDatePickerDelegate:(id<SCOnDemandGeofilterDatePickerDelegate>)arg1 ;
-(void)reloadDayComponent;
-(void)selectDate:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(long long)numberOfComponentsInPickerView:(id)arg1 ;
-(long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2 ;
-(id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3 ;
-(double)pickerView:(id)arg1 widthForComponent:(long long)arg2 ;
-(double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2 ;
-(id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4 ;
-(void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3 ;
-(NSDate *)date;
-(void)updateConstraints;
-(void)setDate:(NSDate *)arg1 ;
-(void)setMinimumDate:(NSDate *)arg1 ;
-(void)setMaximumDate:(NSDate *)arg1 ;
-(NSDate *)minimumDate;
-(NSDate *)maximumDate;
@end

