/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:19 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCOperaLayer.h>

@class NSNumber, NSString, SCOperaPage;

@interface SCOperaCardInteractionLayer : NSObject <SCOperaLayer> {

	NSNumber* _appId;
	NSString* _appIconImageKey;
	NSString* _customUserAgent;
	NSString* _openingAppText;
	NSString* _subtitle;
	NSString* _title;
	NSString* _uri;
	SCOperaPage* _page;
	long long _cardLayerUseType;
	long long _loadingIndicatorType;
	NSString* _imageName;
	NSNumber* _cardDeepLinkDelaySeconds;
	long long _deepLinkFallbackType;

}

@property (nonatomic,readonly) NSNumber * appId;                                 //@synthesize appId=_appId - In the implementation block
@property (nonatomic,copy,readonly) NSString * appIconImageKey;                  //@synthesize appIconImageKey=_appIconImageKey - In the implementation block
@property (nonatomic,readonly) NSString * customUserAgent;                       //@synthesize customUserAgent=_customUserAgent - In the implementation block
@property (nonatomic,copy,readonly) NSString * openingAppText;                   //@synthesize openingAppText=_openingAppText - In the implementation block
@property (nonatomic,copy,readonly) NSString * subtitle;                         //@synthesize subtitle=_subtitle - In the implementation block
@property (nonatomic,copy,readonly) NSString * title;                            //@synthesize title=_title - In the implementation block
@property (nonatomic,copy,readonly) NSString * uri;                              //@synthesize uri=_uri - In the implementation block
@property (assign,nonatomic,__weak) SCOperaPage * page;                          //@synthesize page=_page - In the implementation block
@property (assign,nonatomic) long long cardLayerUseType;                         //@synthesize cardLayerUseType=_cardLayerUseType - In the implementation block
@property (assign,nonatomic) long long loadingIndicatorType;                     //@synthesize loadingIndicatorType=_loadingIndicatorType - In the implementation block
@property (nonatomic,copy,readonly) NSString * imageName;                        //@synthesize imageName=_imageName - In the implementation block
@property (nonatomic,readonly) NSNumber * cardDeepLinkDelaySeconds;              //@synthesize cardDeepLinkDelaySeconds=_cardDeepLinkDelaySeconds - In the implementation block
@property (nonatomic,readonly) long long deepLinkFallbackType;                   //@synthesize deepLinkFallbackType=_deepLinkFallbackType - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)layerWithProperties:(id)arg1 page:(id)arg2 ;
-(long long)deepLinkFallbackType;
-(id)initWithProperties:(id)arg1 page:(id)arg2 ;
-(NSString *)appIconImageKey;
-(long long)cardLayerUseType;
-(long long)loadingIndicatorType;
-(NSNumber *)cardDeepLinkDelaySeconds;
-(NSString *)openingAppText;
-(void)setCardLayerUseType:(long long)arg1 ;
-(void)setLoadingIndicatorType:(long long)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(NSString *)title;
-(unsigned long long)type;
-(NSString *)subtitle;
-(SCOperaPage *)page;
-(void)setPage:(SCOperaPage *)arg1 ;
-(NSNumber *)appId;
-(NSString *)customUserAgent;
-(NSString *)imageName;
-(NSString *)uri;
@end

