/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:24 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCOperaPlaylistEventTrackerPlugin.h>
#import <Snapchat/SCOperaPlaylistItemExtraPropertiesProvider.h>
#import <Snapchat/SCStoryMediaStateListener.h>

@protocol SCOperaPlaylistItemController;
@class SCOperaViewController, SCUserSession, SCStopwatch, NSMutableSet, NSString;

@interface SCOperaPlaylistOptOutInterstitialPlugin : SCOperaPlaylistEventTrackerPlugin <SCOperaPlaylistItemExtraPropertiesProvider, SCStoryMediaStateListener> {

	id<SCOperaPlaylistItemController> _playlistItemController;
	SCOperaViewController* _operaVC;
	SCUserSession* _userSession;
	long long _viewLocation;
	SCStopwatch* _snapViewStopwatch;
	NSMutableSet* _groupIdsWithRemovedOptOutLayerProperties;
	unsigned long long _entryInteractionType;
	unsigned long long _entryGroupIndex;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3 ;
-(void)extraPropertiesForDataModel:(id)arg1 item:(id)arg2 completion:(/*^block*/id)arg3 ;
-(id)registeredEventsForOperaSession;
-(BOOL)isHighPriorityEventListener;
-(void)setPlaylistItemController:(id)arg1 ;
-(void)setOperaViewController:(id)arg1 ;
-(id)extraPropertiesProvider;
-(id)initWithUserSession:(id)arg1 viewLocation:(long long)arg2 ;
-(void)_logOptOutInterstitialViewWithEntryInteractionType:(unsigned long long)arg1 exitInteractionType:(unsigned long long)arg2 context:(id)arg3 ;
-(id)_extraOptOutInterstitialPropertiesForPromotedStory:(id)arg1 item:(id)arg2 ;
-(id)_extraOptOutInterstitialPropertiesForStory:(id)arg1 item:(id)arg2 ;
-(id)_extraOptOutInterstitialPropertiesForChunk:(id)arg1 item:(id)arg2 ;
-(/*^block*/id)_thumbnailImageFetchBlockForStory:(id)arg1 ;
-(id)_posterIdForContext:(id)arg1 ;
-(void)story:(id)arg1 didChangeMediaState:(long long)arg2 ;
-(void)story:(id)arg1 didChangeThumbnailMediaState:(long long)arg2 ;
@end

