/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:19 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCAudioSessionListener.h>

@class SCOperaWebViewWrapper, NSString;

@interface SCOperaWebViewAudioController : NSObject <SCAudioSessionListener> {

	SCOperaWebViewWrapper* _webViewWrapper;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)audioSession:(id)arg1 didChangeVolume:(double)arg2 ;
-(void)muteWebView;
-(void)unmuteWebView;
-(id)initWithOperaWebViewWrapper:(id)arg1 ;
-(void)syncMuteStatus;
-(void)dealloc;
-(void)eval:(id)arg1 ;
@end

