/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCOperaLayerViewController.h>
#import <libobjc.A.dylib/SKStoreProductViewControllerDelegate.h>
#import <Snapchat/SCOperaStoreLayerViewDelegate.h>
#import <Snapchat/SCOperaSwipeInteractionControllerDelegate.h>
#import <Snapchat/SCOperaEventListener.h>

@class SCOperaStoreLayerView, SKStoreProductViewController, SCOperaSwipeInteractionController, UIView, NSString;

@interface SCOperaStoreLayerViewController : SCOperaLayerViewController <SKStoreProductViewControllerDelegate, SCOperaStoreLayerViewDelegate, SCOperaSwipeInteractionControllerDelegate, SCOperaEventListener> {

	SCOperaStoreLayerView* _layerView;
	SKStoreProductViewController* _productViewController;
	BOOL _hasError;
	BOOL _storeViewLoaded;
	SCOperaSwipeInteractionController* _interactionController;
	UIView* _delegateViewForPanGesture;
	BOOL _didPeekBottom;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)_registeredEventsForOperaSession;
-(void)viewDidFullyAppear;
-(void)viewDidFullyDisappear;
-(void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3 ;
-(void)neighborViewDidFullyAppearWithCurrentViewRelativePosition:(unsigned long long)arg1 ;
-(long long)pageabilityForRelativePosition:(unsigned long long)arg1 ;
-(void)updateViewWithPreviousLayer:(id)arg1 currentLayer:(id)arg2 ;
-(void)swipeInteractionController:(id)arg1 didUpdateVisiblePercent:(double)arg2 ;
-(void)swipeInteractionController:(id)arg1 didStartInteractionWithDelegateViewVisible:(BOOL)arg2 ;
-(void)swipeInteractionController:(id)arg1 didFinishInteractionWithDelegateViewVisible:(BOOL)arg2 ;
-(BOOL)swipeInteractionController:(id)arg1 shouldBeginPanWithDirection:(unsigned long long)arg2 ;
-(void)setDelegateViewForPanGesture:(id)arg1 ;
-(id)initWithConfiguration:(id)arg1 eventAnnouncer:(id)arg2 sharedResourceManager:(id)arg3 ;
-(void)loadProduct;
-(void)disableTouches:(BOOL)arg1 ;
-(void)didTapStoreMask:(id)arg1 ;
-(void)storeLayerViewDidCancel:(id)arg1 ;
-(void)loadView;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)teardown;
-(void)_cleanUp;
-(void)productViewControllerDidFinish:(id)arg1 ;
@end

