/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol SCOperaSwipeInteractionControllerDelegate;
@class UIPanGestureRecognizer, UIView, NSString;

@interface SCOperaSwipeInteractionController : NSObject <UIGestureRecognizerDelegate> {

	UIPanGestureRecognizer* _panGesture;
	UIView* _delegateView;
	unsigned long long _swipeDirection;
	double _totalSwipeDistance;
	id<SCOperaSwipeInteractionControllerDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<SCOperaSwipeInteractionControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)didPan:(id)arg1 ;
-(void)updateSwipeDirection:(unsigned long long)arg1 ;
-(void)startTrackingWithView:(id)arg1 swipeDirection:(unsigned long long)arg2 totalSwipeDistance:(double)arg3 ;
-(void)_updateWithPercentMoved:(double)arg1 ;
-(void)_finishPanWithSwipeUpSucceed:(BOOL)arg1 ;
-(void)setDelegate:(id<SCOperaSwipeInteractionControllerDelegate>)arg1 ;
-(id<SCOperaSwipeInteractionControllerDelegate>)delegate;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2 ;
-(void)stopTracking;
@end

