/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:26 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCPaymentMessageDelegate.h>
#import <Snapchat/SCChatMessage.h>
#import <Snapchat/SCChatMessageState.h>
#import <Snapchat/SCMessageText.h>
#import <Snapchat/SCSendStateDelegate.h>

@class NSString, SCPayment, NSArray, NSDate, SCSummaries;

@interface SCPaymentMessage : NSObject <SCPaymentMessageDelegate, SCChatMessage, SCChatMessageState, SCMessageText, SCSendStateDelegate> {

	BOOL _failedAtLeastOnce;
	BOOL _savedByUser;
	BOOL _savedByFriend;
	BOOL _releasedByUser;
	BOOL _releasedByFriend;
	BOOL _swipeToSend;
	BOOL _swipePaymentRainPresented;
	BOOL _pendingSaveWrite;
	BOOL _pendingViewedWrite;
	BOOL _seenFromSnapchatServer;
	BOOL _isDisplayed;
	NSString* _iterToken;
	SCPayment* _payment;
	unsigned long long _userSaveVersion;
	unsigned long long _friendSaveVersion;
	NSString* _text;
	NSArray* _cashTagRanges;
	NSDate* _creationTimestamp;
	NSDate* _sentTimestamp;
	NSDate* _updateTimestamp;
	long long _groupId;
	long long _viewedTransactionStatus;
	NSArray* _attributes;
	SCSummaries* _summaries;

}

@property (nonatomic,retain) SCPayment * payment;                               //@synthesize payment=_payment - In the implementation block
@property (assign,nonatomic) BOOL savedByUser;                                  //@synthesize savedByUser=_savedByUser - In the implementation block
@property (assign,nonatomic) BOOL savedByFriend;                                //@synthesize savedByFriend=_savedByFriend - In the implementation block
@property (assign,nonatomic) unsigned long long userSaveVersion;                //@synthesize userSaveVersion=_userSaveVersion - In the implementation block
@property (assign,nonatomic) unsigned long long friendSaveVersion;              //@synthesize friendSaveVersion=_friendSaveVersion - In the implementation block
@property (assign,nonatomic) BOOL releasedByUser;                               //@synthesize releasedByUser=_releasedByUser - In the implementation block
@property (assign,nonatomic) BOOL releasedByFriend;                             //@synthesize releasedByFriend=_releasedByFriend - In the implementation block
@property (nonatomic,copy) NSString * text;                                     //@synthesize text=_text - In the implementation block
@property (nonatomic,copy) NSArray * cashTagRanges;                             //@synthesize cashTagRanges=_cashTagRanges - In the implementation block
@property (nonatomic,retain) NSDate * creationTimestamp;                        //@synthesize creationTimestamp=_creationTimestamp - In the implementation block
@property (nonatomic,retain) NSDate * sentTimestamp;                            //@synthesize sentTimestamp=_sentTimestamp - In the implementation block
@property (nonatomic,retain) NSDate * updateTimestamp;                          //@synthesize updateTimestamp=_updateTimestamp - In the implementation block
@property (assign,nonatomic) BOOL swipeToSend;                                  //@synthesize swipeToSend=_swipeToSend - In the implementation block
@property (assign,nonatomic) BOOL swipePaymentRainPresented;                    //@synthesize swipePaymentRainPresented=_swipePaymentRainPresented - In the implementation block
@property (assign,nonatomic) BOOL pendingSaveWrite;                             //@synthesize pendingSaveWrite=_pendingSaveWrite - In the implementation block
@property (assign,nonatomic) BOOL pendingViewedWrite;                           //@synthesize pendingViewedWrite=_pendingViewedWrite - In the implementation block
@property (assign,nonatomic) BOOL seenFromSnapchatServer;                       //@synthesize seenFromSnapchatServer=_seenFromSnapchatServer - In the implementation block
@property (assign,nonatomic) long long viewedTransactionStatus;                 //@synthesize viewedTransactionStatus=_viewedTransactionStatus - In the implementation block
@property (nonatomic,retain) NSArray * attributes;                              //@synthesize attributes=_attributes - In the implementation block
@property (nonatomic,retain) SCSummaries * summaries;                           //@synthesize summaries=_summaries - In the implementation block
@property (assign,nonatomic) BOOL isDisplayed;                                  //@synthesize isDisplayed=_isDisplayed - In the implementation block
@property (nonatomic,copy,readonly) NSString * _id; 
@property (nonatomic,copy) NSString * iterToken;                                //@synthesize iterToken=_iterToken - In the implementation block
@property (nonatomic,copy,readonly) NSString * sender; 
@property (nonatomic,copy,readonly) NSString * recipient; 
@property (nonatomic,readonly) BOOL sentByUser; 
@property (assign,nonatomic) BOOL failedAtLeastOnce;                            //@synthesize failedAtLeastOnce=_failedAtLeastOnce - In the implementation block
@property (assign,nonatomic) long long groupId;                                 //@synthesize groupId=_groupId - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)cashTagsJsonFromRanges:(id)arg1 ;
+(BOOL)shouldShowTextForPaymentMessage:(id)arg1 ;
+(BOOL)shouldShowSubtextForPaymentMessage:(id)arg1 ;
+(id)subtextForPaymentMessage:(id)arg1 ;
+(id)actionTextForPaymentMessage:(id)arg1 ;
+(BOOL)isLargeIconForPaymentMessage:(id)arg1 ;
+(id)chatIconImageForPaymentMessage:(id)arg1 ;
+(BOOL)shouldResolveBlockersForPaymentMessage:(id)arg1 ;
+(id)rangesFromCashTagDictionaries:(id)arg1 ;
-(NSString *)iterToken;
-(void)setIterToken:(NSString *)arg1 ;
-(id)savedState;
-(id)mediaCardAttributes;
-(NSDate *)sentTimestamp;
-(NSString *)_id;
-(BOOL)isReleased;
-(id)consistentId;
-(void)setSentTimestamp:(NSDate *)arg1 ;
-(BOOL)failedToSend;
-(id)mediaSendTaskId;
-(id)messageTimestampForOrdering;
-(BOOL)isSavedBy:(id)arg1 ;
-(BOOL)isReleasedBy:(id)arg1 ;
-(id)messageTimestamp;
-(BOOL)isSendingOrHasFailed;
-(BOOL)timeToSendHasExpired;
-(id)releaseState;
-(BOOL)isPreserved;
-(unsigned long long)saveVersionOf:(id)arg1 ;
-(BOOL)shouldDisplayBelowFoldInChat;
-(BOOL)shouldRetryMediaSendTask;
-(id)sendJSON;
-(BOOL)isForwardable;
-(BOOL)savedByUser;
-(void)markAsDisplayed;
-(SCSummaries *)summaries;
-(void)setFailed;
-(id)feedDisplayTimestamp;
-(id)feedSortTimestamp;
-(BOOL)isInvalidAfterUnarchiving;
-(id)clearedDictionary;
-(BOOL)releasedByUser;
-(BOOL)shouldBeAddedAgainGivenClearedDictionary:(id)arg1 ;
-(NSArray *)cashTagRanges;
-(BOOL)sentByUser;
-(void)setCashTagRanges:(NSArray *)arg1 ;
-(void)paymentDidChange;
-(void)paymentBlockersDidChange:(id)arg1 ;
-(void)paymentStatusDidChange:(id)arg1 ;
-(id)initWithUsername:(id)arg1 dictionary:(id)arg2 ;
-(unsigned long long)userSaveVersion;
-(BOOL)swipeToSend;
-(id)initWithPayment:(id)arg1 attributedText:(id)arg2 cashTagRanges:(id)arg3 swipe:(BOOL)arg4 ;
-(void)setSwipeToSend:(BOOL)arg1 ;
-(void)setSwipePaymentRainPresented:(BOOL)arg1 ;
-(void)setPendingViewedWrite:(BOOL)arg1 ;
-(void)setPendingSaveWrite:(BOOL)arg1 ;
-(void)setSeenFromSnapchatServer:(BOOL)arg1 ;
-(void)setViewedTransactionStatus:(long long)arg1 ;
-(void)setSummaries:(SCSummaries *)arg1 ;
-(void)setSavedByUser:(BOOL)arg1 ;
-(void)setSavedByFriend:(BOOL)arg1 ;
-(void)setUserSaveVersion:(unsigned long long)arg1 ;
-(void)setFriendSaveVersion:(unsigned long long)arg1 ;
-(void)setReleasedByUser:(BOOL)arg1 ;
-(void)setReleasedByFriend:(BOOL)arg1 ;
-(void)setUpdateTimestamp:(NSDate *)arg1 ;
-(BOOL)shouldAutomaticallyMarkAsViewed;
-(void)markAsReleasedByUser:(BOOL)arg1 ;
-(void)setFailedAtLeastOnce:(BOOL)arg1 ;
-(BOOL)savedByFriend;
-(unsigned long long)friendSaveVersion;
-(BOOL)releasedByFriend;
-(NSDate *)updateTimestamp;
-(BOOL)swipePaymentRainPresented;
-(BOOL)pendingViewedWrite;
-(BOOL)pendingSaveWrite;
-(BOOL)seenFromSnapchatServer;
-(long long)viewedTransactionStatus;
-(BOOL)failedAtLeastOnce;
-(void)messageUpdated;
-(BOOL)isCurrentUser:(id)arg1 ;
-(BOOL)mayHaveBlockers;
-(BOOL)canRelease;
-(void)sendStateChanged;
-(id)initWithPayment:(id)arg1 text:(id)arg2 cashTagRanges:(id)arg3 swipe:(BOOL)arg4 ;
-(BOOL)updateSentTimestampToNow;
-(void)updateWithPaymentMessage:(id)arg1 ;
-(void)unsave;
-(void)markAsInferredUnsavedByFriend;
-(BOOL)canUnsave;
-(void)markAsReleasedByFriend;
-(BOOL)retriableAfterFailToSend;
-(unsigned long long)unrainedAmountInDollarBills;
-(BOOL)hasFailedAtLeastOnce;
-(BOOL)shouldUpdateRemoteViewedState;
-(BOOL)shouldUpdateRemoteSaveState;
-(void)successfullyUpdatedRemoteViewedStateWithTransactionStatus:(long long)arg1 ;
-(void)successfullyUpdatedRemoteSaveStateWithSaveVersion:(unsigned long long)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(NSString *)description;
-(NSString *)sender;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(BOOL)isDisplayed;
-(NSArray *)attributes;
-(void)setAttributes:(NSArray *)arg1 ;
-(void)setIsDisplayed:(BOOL)arg1 ;
-(id)sequenceNumber;
-(id)conversationId;
-(void)save;
-(NSString *)recipient;
-(void)setPayment:(SCPayment *)arg1 ;
-(BOOL)canDelete;
-(BOOL)isSaved;
-(BOOL)canSave;
-(BOOL)sending;
-(void)setCreationTimestamp:(NSDate *)arg1 ;
-(NSDate *)creationTimestamp;
-(BOOL)isSent;
-(BOOL)isBlocked;
-(long long)messageType;
-(id)messageSender;
-(void)setGroupId:(long long)arg1 ;
-(long long)groupId;
-(SCPayment *)payment;
-(BOOL)isUnread;
@end

