/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:26 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCSendStateDelegate;
@class NSString;

@interface SCPaymentMessageSendState : NSObject {

	long long _stateTag;
	id<SCSendStateDelegate> _delegate;
	NSString* _signature;
	NSString* _passcode;
	long long _currentAction;

}

@property (assign,nonatomic) long long currentAction;                              //@synthesize currentAction=_currentAction - In the implementation block
@property (readonly) long long stateTag;                                           //@synthesize stateTag=_stateTag - In the implementation block
@property (assign,nonatomic,__weak) id<SCSendStateDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (copy) NSString * signature;                                             //@synthesize signature=_signature - In the implementation block
@property (copy,readonly) NSString * passcode;                                     //@synthesize passcode=_passcode - In the implementation block
+(BOOL)paymentIsSuccessfullySent:(id)arg1 ;
-(BOOL)failedToSend;
-(long long)stateTag;
-(void)setStateTag:(long long)arg1 ;
-(void)updateWithPayment:(id)arg1 ;
-(long long)getAndBeginNextAction;
-(void)actionSucceeded:(long long)arg1 withPayment:(id)arg2 ;
-(void)actionFailed:(long long)arg1 withPayment:(id)arg2 ;
-(id)initWithDelegate:(id)arg1 payment:(id)arg2 ;
-(void)beginAction:(long long)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setDelegate:(id<SCSendStateDelegate>)arg1 ;
-(id<SCSendStateDelegate>)delegate;
-(long long)currentAction;
-(id)initWithDelegate:(id)arg1 ;
-(NSString *)passcode;
-(void)setCurrentAction:(long long)arg1 ;
-(BOOL)isSending;
-(void)setSignature:(NSString *)arg1 ;
-(NSString *)signature;
-(BOOL)isSent;
-(long long)nextAction;
@end

