/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:13 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCPreviewToolbarPickerListView.h>

@interface SCPixelationPickerListView : SCPreviewToolbarPickerListView {

	CGSize _previousBoundsSize;

}
-(double)estimateContentHeight;
-(id)_imageMaskForImageView:(id)arg1 roundedCorners:(unsigned long long)arg2 ;
-(void)configureItemViewsFromImageNames:(id)arg1 ;
-(void)layoutSubviews;
@end

