/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:38 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCPreLoginLensActivatorDelegate;
@class SCLensURLDataFetcher;

@interface SCPreLoginLensActivator : NSObject {

	SCLensURLDataFetcher* _dataFetcher;
	id<SCPreLoginLensActivatorDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<SCPreLoginLensActivatorDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(void)_activateWithParameters:(id)arg1 ;
-(id)_lensFetchEndpoint;
-(void)_activateAsyncWithLens:(id)arg1 ;
-(void)_requestLensWithParameters:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_downloadContentForLens:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_reportDownloadEventForLens:(id)arg1 downloadTime:(double)arg2 downloadSize:(long long)arg3 ;
-(void)setDelegate:(id<SCPreLoginLensActivatorDelegate>)arg1 ;
-(id<SCPreLoginLensActivatorDelegate>)delegate;
-(void)activate;
-(id)_requestKey;
@end

