/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCExperimentContext.h>

@interface SCPrefetchWithoutJSForPreloadingOptOutExperimentContext : SCExperimentContext {

	BOOL _enablePrefetchingWithoutJSForPreloadingOptOut;
	BOOL _enableBlockImagePreloadingForPreloadingOptOut;

}

@property (nonatomic,readonly) BOOL enablePrefetchingWithoutJSForPreloadingOptOut;              //@synthesize enablePrefetchingWithoutJSForPreloadingOptOut=_enablePrefetchingWithoutJSForPreloadingOptOut - In the implementation block
@property (nonatomic,readonly) BOOL enableBlockImagePreloadingForPreloadingOptOut;              //@synthesize enableBlockImagePreloadingForPreloadingOptOut=_enableBlockImagePreloadingForPreloadingOptOut - In the implementation block
-(void)setupParameters;
-(BOOL)enablePrefetchingWithoutJSForPreloadingOptOut;
-(BOOL)enableBlockImagePreloadingForPreloadingOptOut;
-(id)experimentName;
@end

