/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:32 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCProductDetailsCardTableViewCell.h>

@class UILabel, UIView, SOJUCommerceProductVariant;

@interface SCProductDetailsCardTitleTableViewCell : SCProductDetailsCardTableViewCell {

	UILabel* _titleLabel;
	UILabel* _storeLabel;
	UILabel* _priceLabel;
	UIView* _cornerTopBackgroundView;
	UIView* _backgroundView;
	SOJUCommerceProductVariant* _selectedOption;

}

@property (assign,nonatomic,__weak) SOJUCommerceProductVariant * selectedOption;              //@synthesize selectedOption=_selectedOption - In the implementation block
+(CGSize)_priceSizeForProduct:(id)arg1 ;
+(id)_titleTextForProduct:(id)arg1 ;
+(id)_storeTextForProduct:(id)arg1 ;
+(CGSize)_priceSizeForString:(id)arg1 ;
+(id)_priceTextForValue:(double)arg1 ;
+(double)heightForProduct:(id)arg1 ;
-(void)layoutSubviews;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(void)setSelectedOption:(SOJUCommerceProductVariant *)arg1 ;
-(void)setProductInfo:(id)arg1 ;
-(SOJUCommerceProductVariant *)selectedOption;
@end

