/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:23 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCFriendProfileCellViewDelegate.h>
#import <Snapchat/SCFriendActionButtonDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@protocol SCQuickAddControllerDataSrouce, SCQuickAddControllerDelegate;
@class AddFriendsDelegateObject, NSMutableArray, SCUserSession, NSMutableSet, NSNumber, UITableView, NSString;

@interface SCQuickAddController : NSObject <SCFriendProfileCellViewDelegate, SCFriendActionButtonDelegate, UITableViewDataSource> {

	AddFriendsDelegateObject* _addFriendsDelegate;
	NSMutableArray* _userSuggestions;
	unsigned long long _source;
	SCUserSession* _userSession;
	unsigned long long _quickAddSection;
	BOOL _friendsDidChange;
	NSMutableSet* _suggestedFriendsSeen;
	NSMutableSet* _suggestedFriendsAdded;
	long long _suggestedFriendsInitialCount;
	long long _suggestedFriendsHiddenCount;
	NSNumber* _impressionId;
	BOOL _viewAppeared;
	id<SCQuickAddControllerDataSrouce> _friendActionDataSource;
	id<SCQuickAddControllerDelegate> _friendActionDelegate;
	UITableView* _tableView;

}

@property (assign,nonatomic,__weak) id<SCQuickAddControllerDataSrouce> friendActionDataSource;              //@synthesize friendActionDataSource=_friendActionDataSource - In the implementation block
@property (assign,nonatomic,__weak) id<SCQuickAddControllerDelegate> friendActionDelegate;                  //@synthesize friendActionDelegate=_friendActionDelegate - In the implementation block
@property (assign,nonatomic) BOOL viewAppeared;                                                             //@synthesize viewAppeared=_viewAppeared - In the implementation block
@property (assign,nonatomic,__weak) UITableView * tableView;                                                //@synthesize tableView=_tableView - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)metricsContextTagFeed;
+(id)metricsContextTagSendTo;
+(id)metricsContextTagStories;
+(BOOL)shouldFilterForAddSuggestedFriend:(id)arg1 name:(id)arg2 pageType:(unsigned long long)arg3 cellId:(id)arg4 ;
+(id)userInfoWithPageType:(unsigned long long)arg1 cellId:(id)arg2 ;
-(void)_generateImpressionId;
-(id)addFriendsDelegate;
-(void)friendProfileCellView:(id)arg1 addFriendPressed:(id)arg2 friend:(id)arg3 ;
-(void)didDisplayProfilePictureOnCellView:(id)arg1 onThumbnail:(id)arg2 friend:(id)arg3 ;
-(void)didPressHideButtonForFriend:(id)arg1 ;
-(id)initWithTableView:(id)arg1 source:(unsigned long long)arg2 userSession:(id)arg3 friendActionDelegate:(id)arg4 ;
-(void)setFriendActionDataSource:(id<SCQuickAddControllerDataSrouce>)arg1 ;
-(void)logSeenSuggestions;
-(void)reloadUserSuggestions;
-(id)userSuggestions;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 suggestedFriendDelegate:(id)arg3 ;
-(long long)getAddSourceTypeForFriend:(id)arg1 ;
-(void)addToAddedSuggestions:(id)arg1 ;
-(void)_didTapViewAllButton;
-(id)cellForFullPageQuickAdd:(id)arg1 suggestedFriend:(id)arg2 suggestedFriendDelegate:(id)arg3 ;
-(void)reloadOnNotification:(id)arg1 ;
-(void)friendsDidChange:(id)arg1 ;
-(unsigned long long)dataPageType;
-(id)placementForSuggestedFriend;
-(id)requestsContext;
-(long long)getSuggestedFriendIndex:(id)arg1 ;
-(void)_updateProfileCellView:(id)arg1 withFriend:(id)arg2 ;
-(void)reloadQuickAdd;
-(id)_newFriendProfileCellConfigurationForFriend:(id)arg1 ;
-(BOOL)_shouldShowViewAll;
-(BOOL)isViewAllCellAtIndexPath:(id)arg1 ;
-(id)friendForRowAtIndexPath:(id)arg1 ;
-(id)_getFriendProfileCellForFindFriendMenuViewOnTableView:(id)arg1 indexPath:(id)arg2 suggestedFriendDelegate:(id)arg3 ;
-(long long)_getButtonStateWithFriendProcessingType:(unsigned long long)arg1 ;
-(id)viewAllCell;
-(void)_updateProfileCell:(id)arg1 withSuggestedFriend:(id)arg2 ;
-(id<SCQuickAddControllerDataSrouce>)friendActionDataSource;
-(void)didFinishFriendAction:(id)arg1 ;
-(BOOL)canShowQuickAdd;
-(long long)suggestedFriendsInitialCount;
-(long long)suggestedFriendsSeenCount;
-(long long)suggestedFriendsAddedCount;
-(long long)suggestedFriendsHiddenCount;
-(id)cellForSendToPageTableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 cellIdentifier:(id)arg3 cellDelegate:(id)arg4 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 hideBottom:(BOOL)arg3 ;
-(id)_getSuggestedFriendFor:(id)arg1 ;
-(id<SCQuickAddControllerDelegate>)friendActionDelegate;
-(void)setFriendActionDelegate:(id<SCQuickAddControllerDelegate>)arg1 ;
-(void)dealloc;
-(double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id)context;
-(void)setTableView:(UITableView *)arg1 ;
-(UITableView *)tableView;
-(void)setViewAppeared:(BOOL)arg1 ;
-(BOOL)viewAppeared;
@end

