/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:01 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@class SCRBrowserCardAction, SCRStoryCardAction, SCRDeeplinkCardAction, SCRUserProfileCardAction, SCRExternalUrlCardAction, SCRSaveSearchAction, SCRUserStoryCardAction, SCRSearchAction, SCRUserChatCardAction;

@interface SCRCardAction : GPBMessage

@property (nonatomic,readonly) int actionOneOfCase; 
@property (nonatomic,retain) SCRBrowserCardAction * showBrowser; 
@property (nonatomic,retain) SCRStoryCardAction * showStory; 
@property (nonatomic,retain) SCRDeeplinkCardAction * gotoDeeplink; 
@property (nonatomic,retain) SCRUserProfileCardAction * showProfile; 
@property (nonatomic,retain) SCRExternalUrlCardAction * showExternalURL; 
@property (nonatomic,retain) SCRSaveSearchAction * saveSearch; 
@property (nonatomic,retain) SCRUserStoryCardAction * showMyStory; 
@property (nonatomic,retain) SCRSearchAction * search; 
@property (nonatomic,retain) SCRUserChatCardAction * chat; 
@property (assign,nonatomic) BOOL preload; 
+(id)descriptor;
@end

