/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:07 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SCRequestConcurrencyLoggingItem : NSObject {

	double _startReceiveDataTimestamp;
	double _finishReceiveDataTimestamp;
	long long _requestType;
	double _accumulatedOverlappedTransmitDurationOfOtherRequests;
	double _accumulatedOverlappedTransmitDurationOfOtherDownloadRequests;
	double _accumulatedOverlappedTransmitDurationOfOtherMetadataRequests;

}

@property (assign,nonatomic) double startReceiveDataTimestamp;                                                 //@synthesize startReceiveDataTimestamp=_startReceiveDataTimestamp - In the implementation block
@property (assign,nonatomic) double finishReceiveDataTimestamp;                                                //@synthesize finishReceiveDataTimestamp=_finishReceiveDataTimestamp - In the implementation block
@property (assign,nonatomic) long long requestType;                                                            //@synthesize requestType=_requestType - In the implementation block
@property (assign,nonatomic) double accumulatedOverlappedTransmitDurationOfOtherRequests;                      //@synthesize accumulatedOverlappedTransmitDurationOfOtherRequests=_accumulatedOverlappedTransmitDurationOfOtherRequests - In the implementation block
@property (assign,nonatomic) double accumulatedOverlappedTransmitDurationOfOtherDownloadRequests;              //@synthesize accumulatedOverlappedTransmitDurationOfOtherDownloadRequests=_accumulatedOverlappedTransmitDurationOfOtherDownloadRequests - In the implementation block
@property (assign,nonatomic) double accumulatedOverlappedTransmitDurationOfOtherMetadataRequests;              //@synthesize accumulatedOverlappedTransmitDurationOfOtherMetadataRequests=_accumulatedOverlappedTransmitDurationOfOtherMetadataRequests - In the implementation block
-(BOOL)isDownloadRequestItem;
-(BOOL)isMetadataRequestItem;
-(id)initRequestConcurrencyLoggingItemWithStartTimestamp:(double)arg1 requestType:(long long)arg2 ;
-(void)updateRequestConcurrencyLoggingItemWithFinishTimestamp:(double)arg1 ;
-(void)updateAccumulatedOverlappedTransmitTimeOfOtherRequestsWithDuration:(double)arg1 overlappedRequest:(id)arg2 ;
-(double)startReceiveDataTimestamp;
-(void)setStartReceiveDataTimestamp:(double)arg1 ;
-(double)finishReceiveDataTimestamp;
-(void)setFinishReceiveDataTimestamp:(double)arg1 ;
-(double)accumulatedOverlappedTransmitDurationOfOtherRequests;
-(void)setAccumulatedOverlappedTransmitDurationOfOtherRequests:(double)arg1 ;
-(double)accumulatedOverlappedTransmitDurationOfOtherDownloadRequests;
-(void)setAccumulatedOverlappedTransmitDurationOfOtherDownloadRequests:(double)arg1 ;
-(double)accumulatedOverlappedTransmitDurationOfOtherMetadataRequests;
-(void)setAccumulatedOverlappedTransmitDurationOfOtherMetadataRequests:(double)arg1 ;
-(void)setRequestType:(long long)arg1 ;
-(long long)requestType;
@end

