/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:48 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCSearchIntent.h>

@class SCSearchDynamicStory, UIView, NSString;

@interface SCSearchStoryPlayIntent : NSObject <SCSearchIntent> {

	SCSearchDynamicStory* _story;
	UIView* _sourceView;
	/*^block*/id _dismissBlock;

}

@property (nonatomic,retain) SCSearchDynamicStory * story;              //@synthesize story=_story - In the implementation block
@property (assign,nonatomic,__weak) UIView * sourceView;                //@synthesize sourceView=_sourceView - In the implementation block
@property (nonatomic,copy,readonly) id dismissBlock;                    //@synthesize dismissBlock=_dismissBlock - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(SCSearchDynamicStory *)story;
-(void)setStory:(SCSearchDynamicStory *)arg1 ;
-(id)dismissBlock;
-(id)initWithStory:(id)arg1 withSourceView:(id)arg2 dismissBlock:(/*^block*/id)arg3 ;
-(UIView *)sourceView;
-(void)setSourceView:(UIView *)arg1 ;
@end

