/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:11 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@protocol NSCopying;
@class SCSearchSectionHeaderModel, SCSearchListSectionExpansionModel, NSValue, NSObject;

@interface SCSearchCollectionViewListSectionConfiguration : NSObject <NSCopying> {

	BOOL _automaticallyManageRoundedCorners;
	BOOL _automaticallyManageCellSeparators;
	SCSearchSectionHeaderModel* _sectionHeaderModel;
	SCSearchListSectionExpansionModel* _expansionModel;
	double _minimumInteritemSpacing;
	NSValue* _sectionInsets;
	NSObject*<NSCopying> _contentDataModel;

}

@property (nonatomic,copy,readonly) SCSearchSectionHeaderModel * sectionHeaderModel;                 //@synthesize sectionHeaderModel=_sectionHeaderModel - In the implementation block
@property (nonatomic,copy,readonly) SCSearchListSectionExpansionModel * expansionModel;              //@synthesize expansionModel=_expansionModel - In the implementation block
@property (nonatomic,readonly) double minimumInteritemSpacing;                                       //@synthesize minimumInteritemSpacing=_minimumInteritemSpacing - In the implementation block
@property (nonatomic,copy,readonly) NSValue * sectionInsets;                                         //@synthesize sectionInsets=_sectionInsets - In the implementation block
@property (nonatomic,readonly) BOOL automaticallyManageRoundedCorners;                               //@synthesize automaticallyManageRoundedCorners=_automaticallyManageRoundedCorners - In the implementation block
@property (nonatomic,readonly) BOOL automaticallyManageCellSeparators;                               //@synthesize automaticallyManageCellSeparators=_automaticallyManageCellSeparators - In the implementation block
@property (nonatomic,copy,readonly) NSObject*<NSCopying> contentDataModel;                           //@synthesize contentDataModel=_contentDataModel - In the implementation block
-(NSObject*<NSCopying>)contentDataModel;
-(SCSearchSectionHeaderModel *)sectionHeaderModel;
-(BOOL)automaticallyManageRoundedCorners;
-(SCSearchListSectionExpansionModel *)expansionModel;
-(BOOL)automaticallyManageCellSeparators;
-(id)initWithSectionHeaderModel:(id)arg1 expansionModel:(id)arg2 minimumInteritemSpacing:(double)arg3 sectionInsets:(id)arg4 automaticallyManageRoundedCorners:(BOOL)arg5 automaticallyManageCellSeparators:(BOOL)arg6 contentDataModel:(id)arg7 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(double)minimumInteritemSpacing;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSValue *)sectionInsets;
@end

