/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:20 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SCScreenshotSendListenerAnnouncer, NSMutableDictionary;

@interface SCSendScreenshotManager : NSObject {

	SCScreenshotSendListenerAnnouncer* _announcer;
	BOOL _isPresentingScreenshotPreview;
	double _startPreviewTime;
	NSMutableDictionary* _pausedIntervals;

}

@property (assign,nonatomic) double startPreviewTime;                            //@synthesize startPreviewTime=_startPreviewTime - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * pausedIntervals;              //@synthesize pausedIntervals=_pausedIntervals - In the implementation block
@property (assign,nonatomic) BOOL isPresentingScreenshotPreview;                 //@synthesize isPresentingScreenshotPreview=_isPresentingScreenshotPreview - In the implementation block
+(id)sharedInstance;
-(void)screenshotSendPreviewDidDismiss;
-(void)screenshotSendPreviewWillPresent;
-(double)startPreviewTime;
-(void)setStartPreviewTime:(double)arg1 ;
-(NSMutableDictionary *)pausedIntervals;
-(void)setPausedIntervals:(NSMutableDictionary *)arg1 ;
-(BOOL)isPresentingScreenshotPreview;
-(void)setIsPresentingScreenshotPreview:(BOOL)arg1 ;
-(id)init;
-(void)addListener:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
@end

