/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:49 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCSearchCollectionViewCellDelegate.h>
#import <Snapchat/SCSearchResultViewMoreCollectionViewCellDelegate.h>
#import <Snapchat/SCFeedManagerListener.h>
#import <Snapchat/SCSearchCollectionViewSection.h>
#import <Snapchat/SCSearchEventAnnouncing.h>

@protocol SCSearchCollectionViewSectionDelegate, SCSearchIntentHandler;
@class SCQueuePerformer, SCSearchSession, SCSearchQuery, NSArray, SCSearchThresholdBasedModelContainer, SCSearchEventListenerAnnouncer, SCSearchQueryStateAwareSupplementaryViewProvider, SCScopedAccess, SCSearchCollectionViewSectionUpdateModel, NSString;

@interface SCSearchResultFriendsSection : NSObject <SCSearchCollectionViewCellDelegate, SCSearchResultViewMoreCollectionViewCellDelegate, SCFeedManagerListener, SCSearchCollectionViewSection, SCSearchEventAnnouncing> {

	SCQueuePerformer* _performer;
	SCSearchSession* _searchSession;
	SCSearchQuery* _currentQuery;
	NSArray* _verifiedUsernames;
	NSArray* _displayedFriendsViewModel;
	SCSearchThresholdBasedModelContainer* _rankedFriendsContainer;
	SCSearchEventListenerAnnouncer* _eventAnnouncer;
	BOOL _resetData;
	BOOL _didUpdateFriendInCurrentQuery;
	BOOL _isFirstTimeFeedManagerUpdate;
	SCSearchQueryStateAwareSupplementaryViewProvider* _queryStateAwareSupplementaryProvider;
	SCScopedAccess* _friendmojiPresenter;
	id<SCSearchCollectionViewSectionDelegate> _delegate;
	id<SCSearchIntentHandler> _intentHandler;
	SCSearchCollectionViewSectionUpdateModel* _sectionUpdateModel;
	long long _dataLoadingStatus;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,copy) SCSearchCollectionViewSectionUpdateModel * sectionUpdateModel;                    //@synthesize sectionUpdateModel=_sectionUpdateModel - In the implementation block
@property (assign,nonatomic,__weak) id<SCSearchCollectionViewSectionDelegate> delegate;                      //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<SCSearchIntentHandler> intentHandler;                                 //@synthesize intentHandler=_intentHandler - In the implementation block
@property (assign,nonatomic) long long dataLoadingStatus;                                                    //@synthesize dataLoadingStatus=_dataLoadingStatus - In the implementation block
@property (nonatomic,retain) id<SCSearchCollectionViewSectionLayoutProviding> layoutCalculator; 
+(id)announcerIdentifier;
-(void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3 ;
-(void)searchCollectionViewCell:(id)arg1 didTriggerActionWithActionModel:(id)arg2 fromSourceView:(id)arg3 ;
-(void)didFeedManagerViewModelChange:(id)arg1 ;
-(double)minimumSectionInteritemSpacing;
-(CGSize)sizeForItemAtIndexInSection:(unsigned long long)arg1 withWidth:(double)arg2 ;
-(id)reuseCellClassesByIdentifiers;
-(unsigned long long)numberOfCellsInSection;
-(id)cellForItemAtIndexInSection:(unsigned long long)arg1 ;
-(SCSearchCollectionViewSectionUpdateModel *)sectionUpdateModel;
-(void)setSectionUpdateModel:(SCSearchCollectionViewSectionUpdateModel *)arg1 ;
-(id<SCSearchIntentHandler>)intentHandler;
-(void)setIntentHandler:(id<SCSearchIntentHandler>)arg1 ;
-(long long)dataLoadingStatus;
-(void)setDataLoadingStatus:(long long)arg1 ;
-(id)supplementaryViewProvider;
-(void)collectionViewWillDisplayCell:(id)arg1 atIndexInSection:(unsigned long long)arg2 ;
-(double)minimumSectionLineSpacing;
-(void)resultViewMoreCollectionViewCellDidTapViewMore:(id)arg1 ;
-(id)initWithSearchSession:(id)arg1 ;
-(void)_updateSection;
-(void)_expandResults;
-(void)_announceSearchResultForSection;
-(void)_handleActionForFriend:(id)arg1 actionModel:(id)arg2 sourceView:(id)arg3 atIndexPath:(id)arg4 ;
-(void)_handleOpenChatForFriend:(id)arg1 atIndexPath:(id)arg2 ;
-(void)_handleOpenMiniProfileForFriend:(id)arg1 atIndexPath:(id)arg2 ;
-(void)_handleOpenStoriesForFriendStories:(id)arg1 sourceView:(id)arg2 atIndexPath:(id)arg3 ;
-(id)_loggingInfoForAction:(long long)arg1 atIndexPath:(id)arg2 ;
-(void)_handleFriendsUpdate;
-(void)_performNewQueryWithQuery:(id)arg1 verifiedUsernames:(id)arg2 ;
-(void)_announceOnScreenForCell:(id)arg1 atIndexInSection:(unsigned long long)arg2 ;
-(void)_updateResultsForFriendsUpdate;
-(id)_searchResultsForQuery:(id)arg1 verifiedUsernames:(id)arg2 ;
-(void)_processUpdatedDataModel:(id)arg1 withQuery:(id)arg2 verifiedUsernames:(id)arg3 ;
-(void)_updateSectionIfDataLoadingStatusNeedsUpdate;
-(void)_updateSectionWithRankedFriends:(id)arg1 displayedViewModels:(id)arg2 queryText:(id)arg3 verifiedUsernames:(id)arg4 ;
-(void)_updateCellsWithRankedFriends:(id)arg1 displayedViewModels:(id)arg2 queryText:(id)arg3 verifiedUsernames:(id)arg4 ;
-(void)_reloadCellWithIndexes:(id)arg1 rankedFriends:(id)arg2 displayedViewModels:(id)arg3 queryText:(id)arg4 verifiedUsernames:(id)arg5 ;
-(void)_updateDataSourceWithRankedFriends:(id)arg1 displayedViewModels:(id)arg2 queryText:(id)arg3 verifiedUsernames:(id)arg4 ;
-(void)_updateForExpansion;
-(void)setDelegate:(id<SCSearchCollectionViewSectionDelegate>)arg1 ;
-(id<SCSearchCollectionViewSectionDelegate>)delegate;
-(id)sectionInfo;
-(void)tearDown;
-(void)addListener:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
-(void)applyConfiguration:(id)arg1 ;
-(void)setUp;
@end

