/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:51 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface SCShazamRecogniseResponse : NSObject {

	NSArray* _matches;
	double _retry;

}

@property (nonatomic,copy,readonly) NSArray * matches;              //@synthesize matches=_matches - In the implementation block
@property (nonatomic,readonly) double retry;                        //@synthesize retry=_retry - In the implementation block
-(id)initWithJSONDictionary:(id)arg1 ;
-(id)_parseSongInfoFromJSONMatch:(id)arg1 withRecordDate:(id)arg2 ;
-(id)_parseSongInfoArtistFromJSONArtist:(id)arg1 ;
-(NSArray *)matches;
-(double)retry;
@end

