/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:49 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCSingleIconViewBase.h>

@class SCLoadingIndicatorView, UIView;

@interface SCSingleIconView : SCSingleIconViewBase {

	SCLoadingIndicatorView* _loadingSpinner;
	UIView* _borderView;

}

@property (nonatomic,retain) SCLoadingIndicatorView * loadingSpinner;              //@synthesize loadingSpinner=_loadingSpinner - In the implementation block
@property (nonatomic,retain) UIView * borderView;                                  //@synthesize borderView=_borderView - In the implementation block
-(void)configureBorderedThumbnailWithBorderWidth:(double)arg1 inset:(double)arg2 alpha:(double)arg3 ;
-(UIView *)borderView;
-(id)initWithType:(unsigned long long)arg1 frame:(CGRect)arg2 ;
-(void)setBorderView:(UIView *)arg1 ;
-(void)setSpinnerProgress:(double)arg1 animated:(BOOL)arg2 ;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(void)setLoadingSpinner:(SCLoadingIndicatorView *)arg1 ;
-(SCLoadingIndicatorView *)loadingSpinner;
-(void)showSpinner;
-(void)setImageAlpha:(double)arg1 ;
-(void)hideSpinner;
@end

