/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:34 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SCSnapPlayContainer, SCSnapPlayDelegate;
@class UIViewController, Snap;

@interface SCSnapPlayController : NSObject {

	UIViewController*<SCSnapPlayContainer> _containerViewController;
	long long _containerViewType;
	Snap* _replaySnap;
	id<SCSnapPlayDelegate> _delegate;

}

@property (nonatomic,retain) Snap * replaySnap;                                   //@synthesize replaySnap=_replaySnap - In the implementation block
@property (assign,nonatomic,__weak) id<SCSnapPlayDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)shared;
-(id)getPageViewName;
-(void)switchToContainerViewController:(id)arg1 delegate:(id)arg2 ;
-(void)promptReplaySnap:(id)arg1 replayAllSnaps:(BOOL)arg2 ;
-(void)setReplaySnap:(Snap *)arg1 ;
-(void)changeSnapOrSnapStackStateWithFirstSnap:(id)arg1 state:(long long)arg2 replayAllSnaps:(BOOL)arg3 ;
-(void)resetWaitingUpdateCreditsSnaps;
-(void)showReplayCreditUpdatePromptAndReplayAllSnaps:(BOOL)arg1 ;
-(void)showFreeReplayAlertView:(id)arg1 replayAllSnaps:(BOOL)arg2 ;
-(void)replaySnapOrSnapStackWithFirstSnap:(id)arg1 hasBeenPaidToReplay:(BOOL)arg2 replayAllSnaps:(BOOL)arg3 ;
-(id)replayableSnapsForUsername:(id)arg1 ;
-(Snap *)replaySnap;
-(void)setDelegate:(id<SCSnapPlayDelegate>)arg1 ;
-(id<SCSnapPlayDelegate>)delegate;
@end

