/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:39 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSCoding.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSNumber, NSString, NSArray, NSDate, SCFilterViewMetrics, SCFilterCarouselLoggingParameters, SCGalleryUserContext, NSSet, SCMagicToolsState;

@interface SCSnapCommonLoggingParameters : NSObject <NSCoding, NSCopying> {

	BOOL _withAnimated;
	BOOL _drawing;
	BOOL _cropping;
	BOOL _flashOn;
	BOOL _frontCamera;
	BOOL _hasLabel;
	BOOL _lowLightBoostEnabledBeforeCapture;
	BOOL _handsFree;
	BOOL _withGallery;
	BOOL _withMyStory;
	BOOL _withOurStory;
	BOOL _withSnap;
	BOOL _withLocationEnabled;
	BOOL _savedToGalleryByScreenshot;
	BOOL _savedToGalleryByScreenRecording;
	BOOL _reply;
	BOOL _trimmed;
	BOOL _hasSplit;
	BOOL _hasIndividualCreativeTools;
	BOOL _hasGeoLens;
	BOOL _hasSponsoredLens;
	BOOL _captionTracking;
	BOOL _captionHasStyling;
	BOOL _filterReverse;
	BOOL _snapTimeIsLoop;
	BOOL _shouldSaveToMemories;
	BOOL _snapDidSendToChat;
	BOOL _snapDidPostToStory;
	BOOL _snapDidSaveAsCopy;
	BOOL _snapDidSaveToReplace;
	BOOL _meo;
	BOOL _hasCreative;
	BOOL _hasBackgroundFilter;
	BOOL _withAttachment;
	BOOL _contextFilterHighEndModelIsEnabled;
	BOOL _contextFilterIsSeen;
	BOOL _contextFilterIsEnabled;
	BOOL _visualFilterIsSeen;
	float _mediaDuration;
	float _viewTime;
	long long _animatedStickerCount;
	long long _animatedFilterCount;
	long long _lowLightStatus;
	long long _cameraFlipsWhileRecording;
	NSNumber* _withMyStoryPrivacyOverride;
	long long _mediaType;
	long long _caption;
	long long _filterIndexCount;
	long long _filterSeenCount;
	long long _filterIndexPos;
	long long _recipientCount;
	long long _invitedRecipientCount;
	long long _invitedRecipientShown;
	long long _storyPostCount;
	long long _source;
	long long _cameraSource;
	NSString* _encryptedGeoData;
	NSString* _filterGeoId;
	NSString* _filterInfo;
	NSString* _geoFilterDynamicContextSources;
	NSString* _filterVisual;
	NSString* _lagunaUserAgent;
	NSString* _lagunaDeviceId;
	NSString* _shareChannel;
	long long _multiSnapCount;
	long long _multiSnapIndex;
	long long _deletedSegments;
	long long _multiSnapPreviewCount;
	long long _multiSnapPreviewIndex;
	long long _multiSnapOutputCount;
	long long _multiSnapOutputIndex;
	NSString* _lensId;
	NSString* _lensOptionId;
	long long _lensSource;
	long long _faceFrontCameraCount;
	long long _faceBackCameraCount;
	long long _lensIndexPos;
	long long _lensIndexCount;
	NSString* _lensBundleUrl;
	NSArray* _lensConfigurations;
	long long _captionAddCount;
	long long _captionUseCount;
	long long _captionDeletionCount;
	NSString* _captionStyleList;
	long long _tagFromCarouselCount;
	long long _tagCount;
	long long _unverifiedTagCount;
	long long _stickerCount;
	long long _stickerTrackingCount;
	long long _stickerDeletionCount;
	long long _stickerAutoGeneratedUsageCount;
	long long _filterMotion;
	long long _swipeCount;
	NSString* _snapSessionId;
	NSDate* _startRecordingTimestamp;
	NSString* _captureSessionId;
	long long _firstSwipeDirection;
	SCFilterViewMetrics* _infoFilterViewMetrics;
	NSDate* _lastFilterRenderTime;
	NSString* _filterRenderTimes;
	NSNumber* _filterInfoValue;
	long long _filterStreakValue;
	long long _filterStreakType;
	SCFilterCarouselLoggingParameters* _filterCarouselLoggingParameters;
	long long _saveCount;
	SCGalleryUserContext* _galleryUserContext;
	long long _gallerySendSource;
	NSString* _destinations;
	long long _galleryMediaType;
	long long _orientation;
	long long _entryType;
	NSString* _entryExternalId;
	NSString* _galleryCollectionCategory;
	long long _emojiStickersCount;
	long long _bitmojiStickersCount;
	long long _bitmojiGeoStickersCount;
	long long _snapchatStickersCount;
	long long _emojiStickersFromRecentCount;
	long long _bitmojiStickersFromRecentCount;
	long long _bitmojiGeoStickersFromRecentCount;
	long long _snapchatStickersFromRecentCount;
	long long _stickerFromSearchCount;
	long long _stickerUserEnterSearchCount;
	long long _pretypeStickerTagSelectCount;
	long long _prefixMatchStickerTagSelectCount;
	long long _infoStickersCount;
	long long _contextualStickersCount;
	long long _infoStickerTapCount;
	long long _unlockableStickerCount;
	long long _giphyStickerCount;
	NSString* _emojiStickersList;
	NSString* _bitmojiStickersList;
	NSString* _bitmojiGeoStickersList;
	NSString* _snapchatStickersList;
	NSString* _infoStickersList;
	NSString* _widgetValueList;
	NSString* _geofilterWidgetValueList;
	NSString* _contextualStickersList;
	NSString* _unlockableStickerList;
	NSString* _giphyStickerList;
	NSSet* _stickerPackIds;
	long long _customStickerCreationCount;
	long long _customStickerDeletionCount;
	long long _customStickerSelectionCount;
	long long _customStickerSelectionFromRecentCount;
	NSString* _encodedStickers;
	NSDate* _snapCreateTime;
	NSString* _correspondentIdsString;
	NSString* _mischiefIdsString;
	NSString* _snapcraftStyleId;
	unsigned long long _tapCount;
	double _filterVenueYOffset;
	unsigned long long _venueTapIndex;
	NSString* _venueID;
	SCMagicToolsState* _magicToolsState;
	long long _brushResizeCount;
	NSString* _brushStroke;
	NSString* _audioFilterStyleId;
	long long _contextFilterGeneratedCount;
	NSString* _contextFilterSelectedId;
	NSString* _contextFilterSkyType;
	NSString* _contextFilterPortraitType;
	long long _groupStoriesSendCount;
	long long _availableGroupStoriesCount;
	long long _expiredGroupStoryPostCount;
	long long _availableExpiredGroupStoryCount;
	long long _officialStoriesSendCount;
	long long _sharedStoriesSendCount;
	long long _viewMoreStoriesTapCount;
	long long _filterStackingButtonAddCount;
	long long _filterStackingButtonRemoveCount;
	NSString* _entryId;
	NSString* _snapId;
	long long _mediaFormat;
	NSString* _spectaclesContentId;
	NSString* _previewSaveStyle;
	long long _groupNonUniqueUserRecipientCount;
	long long _groupUniqueUserRecipientCount;
	long long _totalUniqueUserRecipientCount;
	NSString* _topsnapAdId;
	NSString* _topsnapAdRequestClientId;
	long long _filterSource;
	NSNumber* _version;

}

@property (nonatomic,retain) NSNumber * version;                                                             //@synthesize version=_version - In the implementation block
@property (assign,nonatomic) long long animatedStickerCount;                                                 //@synthesize animatedStickerCount=_animatedStickerCount - In the implementation block
@property (assign,nonatomic) long long animatedFilterCount;                                                  //@synthesize animatedFilterCount=_animatedFilterCount - In the implementation block
@property (assign,nonatomic) BOOL withAnimated;                                                              //@synthesize withAnimated=_withAnimated - In the implementation block
@property (assign,nonatomic) long long lowLightStatus;                                                       //@synthesize lowLightStatus=_lowLightStatus - In the implementation block
@property (assign,nonatomic) BOOL drawing;                                                                   //@synthesize drawing=_drawing - In the implementation block
@property (assign,nonatomic) BOOL cropping;                                                                  //@synthesize cropping=_cropping - In the implementation block
@property (assign,nonatomic) BOOL flashOn;                                                                   //@synthesize flashOn=_flashOn - In the implementation block
@property (assign,nonatomic) BOOL frontCamera;                                                               //@synthesize frontCamera=_frontCamera - In the implementation block
@property (assign,nonatomic) long long cameraFlipsWhileRecording;                                            //@synthesize cameraFlipsWhileRecording=_cameraFlipsWhileRecording - In the implementation block
@property (assign,nonatomic) BOOL hasLabel;                                                                  //@synthesize hasLabel=_hasLabel - In the implementation block
@property (assign,nonatomic) BOOL lowLightBoostEnabledBeforeCapture;                                         //@synthesize lowLightBoostEnabledBeforeCapture=_lowLightBoostEnabledBeforeCapture - In the implementation block
@property (assign,nonatomic) BOOL handsFree;                                                                 //@synthesize handsFree=_handsFree - In the implementation block
@property (assign,nonatomic) BOOL withGallery;                                                               //@synthesize withGallery=_withGallery - In the implementation block
@property (assign,nonatomic) BOOL withMyStory;                                                               //@synthesize withMyStory=_withMyStory - In the implementation block
@property (nonatomic,retain) NSNumber * withMyStoryPrivacyOverride;                                          //@synthesize withMyStoryPrivacyOverride=_withMyStoryPrivacyOverride - In the implementation block
@property (assign,nonatomic) BOOL withOurStory;                                                              //@synthesize withOurStory=_withOurStory - In the implementation block
@property (assign,nonatomic) BOOL withSnap;                                                                  //@synthesize withSnap=_withSnap - In the implementation block
@property (assign,nonatomic) BOOL withLocationEnabled;                                                       //@synthesize withLocationEnabled=_withLocationEnabled - In the implementation block
@property (assign,nonatomic) BOOL savedToGalleryByScreenshot;                                                //@synthesize savedToGalleryByScreenshot=_savedToGalleryByScreenshot - In the implementation block
@property (assign,nonatomic) BOOL savedToGalleryByScreenRecording;                                           //@synthesize savedToGalleryByScreenRecording=_savedToGalleryByScreenRecording - In the implementation block
@property (assign,nonatomic) BOOL reply;                                                                     //@synthesize reply=_reply - In the implementation block
@property (assign,nonatomic) float mediaDuration;                                                            //@synthesize mediaDuration=_mediaDuration - In the implementation block
@property (assign,nonatomic) float viewTime;                                                                 //@synthesize viewTime=_viewTime - In the implementation block
@property (assign,nonatomic) long long mediaType;                                                            //@synthesize mediaType=_mediaType - In the implementation block
@property (assign,nonatomic) long long caption;                                                              //@synthesize caption=_caption - In the implementation block
@property (assign,nonatomic) long long filterIndexCount;                                                     //@synthesize filterIndexCount=_filterIndexCount - In the implementation block
@property (assign,nonatomic) long long filterSeenCount;                                                      //@synthesize filterSeenCount=_filterSeenCount - In the implementation block
@property (assign,nonatomic) long long filterIndexPos;                                                       //@synthesize filterIndexPos=_filterIndexPos - In the implementation block
@property (assign,nonatomic) long long recipientCount;                                                       //@synthesize recipientCount=_recipientCount - In the implementation block
@property (assign,nonatomic) long long invitedRecipientCount;                                                //@synthesize invitedRecipientCount=_invitedRecipientCount - In the implementation block
@property (assign,nonatomic) long long invitedRecipientShown;                                                //@synthesize invitedRecipientShown=_invitedRecipientShown - In the implementation block
@property (assign,nonatomic) long long storyPostCount;                                                       //@synthesize storyPostCount=_storyPostCount - In the implementation block
@property (assign,nonatomic) long long source;                                                               //@synthesize source=_source - In the implementation block
@property (assign,nonatomic) long long cameraSource;                                                         //@synthesize cameraSource=_cameraSource - In the implementation block
@property (nonatomic,copy) NSString * encryptedGeoData;                                                      //@synthesize encryptedGeoData=_encryptedGeoData - In the implementation block
@property (nonatomic,copy) NSString * filterGeoId;                                                           //@synthesize filterGeoId=_filterGeoId - In the implementation block
@property (nonatomic,copy) NSString * filterInfo;                                                            //@synthesize filterInfo=_filterInfo - In the implementation block
@property (nonatomic,copy) NSString * geoFilterDynamicContextSources;                                        //@synthesize geoFilterDynamicContextSources=_geoFilterDynamicContextSources - In the implementation block
@property (nonatomic,copy) NSString * filterVisual;                                                          //@synthesize filterVisual=_filterVisual - In the implementation block
@property (nonatomic,copy) NSString * lagunaUserAgent;                                                       //@synthesize lagunaUserAgent=_lagunaUserAgent - In the implementation block
@property (nonatomic,copy) NSString * lagunaDeviceId;                                                        //@synthesize lagunaDeviceId=_lagunaDeviceId - In the implementation block
@property (nonatomic,retain) NSString * shareChannel;                                                        //@synthesize shareChannel=_shareChannel - In the implementation block
@property (assign,nonatomic) long long multiSnapCount;                                                       //@synthesize multiSnapCount=_multiSnapCount - In the implementation block
@property (assign,nonatomic) long long multiSnapIndex;                                                       //@synthesize multiSnapIndex=_multiSnapIndex - In the implementation block
@property (assign,nonatomic) long long deletedSegments;                                                      //@synthesize deletedSegments=_deletedSegments - In the implementation block
@property (assign,nonatomic) BOOL trimmed;                                                                   //@synthesize trimmed=_trimmed - In the implementation block
@property (assign,nonatomic) BOOL hasSplit;                                                                  //@synthesize hasSplit=_hasSplit - In the implementation block
@property (assign,nonatomic) BOOL hasIndividualCreativeTools;                                                //@synthesize hasIndividualCreativeTools=_hasIndividualCreativeTools - In the implementation block
@property (assign,nonatomic) long long multiSnapPreviewCount;                                                //@synthesize multiSnapPreviewCount=_multiSnapPreviewCount - In the implementation block
@property (assign,nonatomic) long long multiSnapPreviewIndex;                                                //@synthesize multiSnapPreviewIndex=_multiSnapPreviewIndex - In the implementation block
@property (assign,nonatomic) long long multiSnapOutputCount;                                                 //@synthesize multiSnapOutputCount=_multiSnapOutputCount - In the implementation block
@property (assign,nonatomic) long long multiSnapOutputIndex;                                                 //@synthesize multiSnapOutputIndex=_multiSnapOutputIndex - In the implementation block
@property (nonatomic,copy) NSString * lensId;                                                                //@synthesize lensId=_lensId - In the implementation block
@property (nonatomic,copy) NSString * lensOptionId;                                                          //@synthesize lensOptionId=_lensOptionId - In the implementation block
@property (assign,nonatomic) long long lensSource;                                                           //@synthesize lensSource=_lensSource - In the implementation block
@property (assign,nonatomic) long long faceFrontCameraCount;                                                 //@synthesize faceFrontCameraCount=_faceFrontCameraCount - In the implementation block
@property (assign,nonatomic) long long faceBackCameraCount;                                                  //@synthesize faceBackCameraCount=_faceBackCameraCount - In the implementation block
@property (assign,nonatomic) long long lensIndexPos;                                                         //@synthesize lensIndexPos=_lensIndexPos - In the implementation block
@property (assign,nonatomic) long long lensIndexCount;                                                       //@synthesize lensIndexCount=_lensIndexCount - In the implementation block
@property (nonatomic,copy) NSString * lensBundleUrl;                                                         //@synthesize lensBundleUrl=_lensBundleUrl - In the implementation block
@property (nonatomic,copy,readonly) NSString * lensInfo; 
@property (nonatomic,copy) NSArray * lensConfigurations;                                                     //@synthesize lensConfigurations=_lensConfigurations - In the implementation block
@property (assign,nonatomic) BOOL hasGeoLens;                                                                //@synthesize hasGeoLens=_hasGeoLens - In the implementation block
@property (assign,nonatomic) BOOL hasSponsoredLens;                                                          //@synthesize hasSponsoredLens=_hasSponsoredLens - In the implementation block
@property (assign,nonatomic) BOOL captionTracking;                                                           //@synthesize captionTracking=_captionTracking - In the implementation block
@property (assign,nonatomic) BOOL captionHasStyling;                                                         //@synthesize captionHasStyling=_captionHasStyling - In the implementation block
@property (assign,nonatomic) long long captionAddCount;                                                      //@synthesize captionAddCount=_captionAddCount - In the implementation block
@property (assign,nonatomic) long long captionUseCount;                                                      //@synthesize captionUseCount=_captionUseCount - In the implementation block
@property (assign,nonatomic) long long captionDeletionCount;                                                 //@synthesize captionDeletionCount=_captionDeletionCount - In the implementation block
@property (nonatomic,copy) NSString * captionStyleList;                                                      //@synthesize captionStyleList=_captionStyleList - In the implementation block
@property (assign,nonatomic) long long tagFromCarouselCount;                                                 //@synthesize tagFromCarouselCount=_tagFromCarouselCount - In the implementation block
@property (assign,nonatomic) long long tagCount;                                                             //@synthesize tagCount=_tagCount - In the implementation block
@property (assign,nonatomic) long long unverifiedTagCount;                                                   //@synthesize unverifiedTagCount=_unverifiedTagCount - In the implementation block
@property (assign,nonatomic) long long stickerCount;                                                         //@synthesize stickerCount=_stickerCount - In the implementation block
@property (assign,nonatomic) long long stickerTrackingCount;                                                 //@synthesize stickerTrackingCount=_stickerTrackingCount - In the implementation block
@property (assign,nonatomic) long long stickerDeletionCount;                                                 //@synthesize stickerDeletionCount=_stickerDeletionCount - In the implementation block
@property (assign,nonatomic) long long stickerAutoGeneratedUsageCount;                                       //@synthesize stickerAutoGeneratedUsageCount=_stickerAutoGeneratedUsageCount - In the implementation block
@property (assign,nonatomic) long long filterMotion;                                                         //@synthesize filterMotion=_filterMotion - In the implementation block
@property (assign,nonatomic) BOOL filterReverse;                                                             //@synthesize filterReverse=_filterReverse - In the implementation block
@property (assign,nonatomic) long long swipeCount;                                                           //@synthesize swipeCount=_swipeCount - In the implementation block
@property (nonatomic,copy) NSString * snapSessionId;                                                         //@synthesize snapSessionId=_snapSessionId - In the implementation block
@property (nonatomic,retain) NSDate * startRecordingTimestamp;                                               //@synthesize startRecordingTimestamp=_startRecordingTimestamp - In the implementation block
@property (nonatomic,copy) NSString * captureSessionId;                                                      //@synthesize captureSessionId=_captureSessionId - In the implementation block
@property (assign,nonatomic) long long firstSwipeDirection;                                                  //@synthesize firstSwipeDirection=_firstSwipeDirection - In the implementation block
@property (nonatomic,retain) SCFilterViewMetrics * infoFilterViewMetrics;                                    //@synthesize infoFilterViewMetrics=_infoFilterViewMetrics - In the implementation block
@property (nonatomic,copy) NSDate * lastFilterRenderTime;                                                    //@synthesize lastFilterRenderTime=_lastFilterRenderTime - In the implementation block
@property (nonatomic,copy) NSString * filterRenderTimes;                                                     //@synthesize filterRenderTimes=_filterRenderTimes - In the implementation block
@property (nonatomic,copy) NSNumber * filterInfoValue;                                                       //@synthesize filterInfoValue=_filterInfoValue - In the implementation block
@property (assign,nonatomic) long long filterStreakValue;                                                    //@synthesize filterStreakValue=_filterStreakValue - In the implementation block
@property (assign,nonatomic) long long filterStreakType;                                                     //@synthesize filterStreakType=_filterStreakType - In the implementation block
@property (assign,nonatomic) BOOL snapTimeIsLoop;                                                            //@synthesize snapTimeIsLoop=_snapTimeIsLoop - In the implementation block
@property (nonatomic,copy) SCFilterCarouselLoggingParameters * filterCarouselLoggingParameters;              //@synthesize filterCarouselLoggingParameters=_filterCarouselLoggingParameters - In the implementation block
@property (assign,nonatomic) BOOL shouldSaveToMemories;                                                      //@synthesize shouldSaveToMemories=_shouldSaveToMemories - In the implementation block
@property (assign,nonatomic) long long saveCount;                                                            //@synthesize saveCount=_saveCount - In the implementation block
@property (assign,nonatomic) BOOL snapDidSendToChat;                                                         //@synthesize snapDidSendToChat=_snapDidSendToChat - In the implementation block
@property (assign,nonatomic) BOOL snapDidPostToStory;                                                        //@synthesize snapDidPostToStory=_snapDidPostToStory - In the implementation block
@property (assign,nonatomic) BOOL snapDidSaveAsCopy;                                                         //@synthesize snapDidSaveAsCopy=_snapDidSaveAsCopy - In the implementation block
@property (assign,nonatomic) BOOL snapDidSaveToReplace;                                                      //@synthesize snapDidSaveToReplace=_snapDidSaveToReplace - In the implementation block
@property (nonatomic,retain) SCGalleryUserContext * galleryUserContext;                                      //@synthesize galleryUserContext=_galleryUserContext - In the implementation block
@property (assign,nonatomic) long long gallerySendSource;                                                    //@synthesize gallerySendSource=_gallerySendSource - In the implementation block
@property (nonatomic,retain) NSString * destinations;                                                        //@synthesize destinations=_destinations - In the implementation block
@property (assign,nonatomic) long long galleryMediaType;                                                     //@synthesize galleryMediaType=_galleryMediaType - In the implementation block
@property (assign,nonatomic) long long orientation;                                                          //@synthesize orientation=_orientation - In the implementation block
@property (assign,nonatomic) long long entryType;                                                            //@synthesize entryType=_entryType - In the implementation block
@property (assign,nonatomic) BOOL meo;                                                                       //@synthesize meo=_meo - In the implementation block
@property (assign,nonatomic) BOOL hasCreative;                                                               //@synthesize hasCreative=_hasCreative - In the implementation block
@property (nonatomic,retain) NSString * entryExternalId;                                                     //@synthesize entryExternalId=_entryExternalId - In the implementation block
@property (nonatomic,retain) NSString * galleryCollectionCategory;                                           //@synthesize galleryCollectionCategory=_galleryCollectionCategory - In the implementation block
@property (assign,nonatomic) long long emojiStickersCount;                                                   //@synthesize emojiStickersCount=_emojiStickersCount - In the implementation block
@property (assign,nonatomic) long long bitmojiStickersCount;                                                 //@synthesize bitmojiStickersCount=_bitmojiStickersCount - In the implementation block
@property (assign,nonatomic) long long bitmojiGeoStickersCount;                                              //@synthesize bitmojiGeoStickersCount=_bitmojiGeoStickersCount - In the implementation block
@property (assign,nonatomic) long long snapchatStickersCount;                                                //@synthesize snapchatStickersCount=_snapchatStickersCount - In the implementation block
@property (assign,nonatomic) long long emojiStickersFromRecentCount;                                         //@synthesize emojiStickersFromRecentCount=_emojiStickersFromRecentCount - In the implementation block
@property (assign,nonatomic) long long bitmojiStickersFromRecentCount;                                       //@synthesize bitmojiStickersFromRecentCount=_bitmojiStickersFromRecentCount - In the implementation block
@property (assign,nonatomic) long long bitmojiGeoStickersFromRecentCount;                                    //@synthesize bitmojiGeoStickersFromRecentCount=_bitmojiGeoStickersFromRecentCount - In the implementation block
@property (assign,nonatomic) long long snapchatStickersFromRecentCount;                                      //@synthesize snapchatStickersFromRecentCount=_snapchatStickersFromRecentCount - In the implementation block
@property (assign,nonatomic) long long stickerFromSearchCount;                                               //@synthesize stickerFromSearchCount=_stickerFromSearchCount - In the implementation block
@property (assign,nonatomic) long long stickerUserEnterSearchCount;                                          //@synthesize stickerUserEnterSearchCount=_stickerUserEnterSearchCount - In the implementation block
@property (assign,nonatomic) long long pretypeStickerTagSelectCount;                                         //@synthesize pretypeStickerTagSelectCount=_pretypeStickerTagSelectCount - In the implementation block
@property (assign,nonatomic) long long prefixMatchStickerTagSelectCount;                                     //@synthesize prefixMatchStickerTagSelectCount=_prefixMatchStickerTagSelectCount - In the implementation block
@property (assign,nonatomic) long long infoStickersCount;                                                    //@synthesize infoStickersCount=_infoStickersCount - In the implementation block
@property (assign,nonatomic) long long contextualStickersCount;                                              //@synthesize contextualStickersCount=_contextualStickersCount - In the implementation block
@property (assign,nonatomic) long long infoStickerTapCount;                                                  //@synthesize infoStickerTapCount=_infoStickerTapCount - In the implementation block
@property (assign,nonatomic) long long unlockableStickerCount;                                               //@synthesize unlockableStickerCount=_unlockableStickerCount - In the implementation block
@property (assign,nonatomic) long long giphyStickerCount;                                                    //@synthesize giphyStickerCount=_giphyStickerCount - In the implementation block
@property (nonatomic,copy) NSString * emojiStickersList;                                                     //@synthesize emojiStickersList=_emojiStickersList - In the implementation block
@property (nonatomic,copy) NSString * bitmojiStickersList;                                                   //@synthesize bitmojiStickersList=_bitmojiStickersList - In the implementation block
@property (nonatomic,copy) NSString * bitmojiGeoStickersList;                                                //@synthesize bitmojiGeoStickersList=_bitmojiGeoStickersList - In the implementation block
@property (nonatomic,copy) NSString * snapchatStickersList;                                                  //@synthesize snapchatStickersList=_snapchatStickersList - In the implementation block
@property (nonatomic,copy) NSString * infoStickersList;                                                      //@synthesize infoStickersList=_infoStickersList - In the implementation block
@property (nonatomic,copy) NSString * widgetValueList;                                                       //@synthesize widgetValueList=_widgetValueList - In the implementation block
@property (nonatomic,copy) NSString * geofilterWidgetValueList;                                              //@synthesize geofilterWidgetValueList=_geofilterWidgetValueList - In the implementation block
@property (nonatomic,copy) NSString * contextualStickersList;                                                //@synthesize contextualStickersList=_contextualStickersList - In the implementation block
@property (nonatomic,copy) NSString * unlockableStickerList;                                                 //@synthesize unlockableStickerList=_unlockableStickerList - In the implementation block
@property (nonatomic,copy) NSString * giphyStickerList;                                                      //@synthesize giphyStickerList=_giphyStickerList - In the implementation block
@property (nonatomic,copy) NSSet * stickerPackIds;                                                           //@synthesize stickerPackIds=_stickerPackIds - In the implementation block
@property (assign,nonatomic) long long customStickerCreationCount;                                           //@synthesize customStickerCreationCount=_customStickerCreationCount - In the implementation block
@property (assign,nonatomic) long long customStickerDeletionCount;                                           //@synthesize customStickerDeletionCount=_customStickerDeletionCount - In the implementation block
@property (assign,nonatomic) long long customStickerSelectionCount;                                          //@synthesize customStickerSelectionCount=_customStickerSelectionCount - In the implementation block
@property (assign,nonatomic) long long customStickerSelectionFromRecentCount;                                //@synthesize customStickerSelectionFromRecentCount=_customStickerSelectionFromRecentCount - In the implementation block
@property (nonatomic,copy) NSString * encodedStickers;                                                       //@synthesize encodedStickers=_encodedStickers - In the implementation block
@property (nonatomic,copy) NSDate * snapCreateTime;                                                          //@synthesize snapCreateTime=_snapCreateTime - In the implementation block
@property (nonatomic,copy) NSString * correspondentIdsString;                                                //@synthesize correspondentIdsString=_correspondentIdsString - In the implementation block
@property (nonatomic,copy) NSString * mischiefIdsString;                                                     //@synthesize mischiefIdsString=_mischiefIdsString - In the implementation block
@property (nonatomic,copy) NSString * snapcraftStyleId;                                                      //@synthesize snapcraftStyleId=_snapcraftStyleId - In the implementation block
@property (assign,nonatomic) unsigned long long tapCount;                                                    //@synthesize tapCount=_tapCount - In the implementation block
@property (assign,nonatomic) double filterVenueYOffset;                                                      //@synthesize filterVenueYOffset=_filterVenueYOffset - In the implementation block
@property (assign,nonatomic) unsigned long long venueTapIndex;                                               //@synthesize venueTapIndex=_venueTapIndex - In the implementation block
@property (nonatomic,copy) NSString * venueID;                                                               //@synthesize venueID=_venueID - In the implementation block
@property (assign,nonatomic) BOOL hasBackgroundFilter;                                                       //@synthesize hasBackgroundFilter=_hasBackgroundFilter - In the implementation block
@property (nonatomic,copy) SCMagicToolsState * magicToolsState;                                              //@synthesize magicToolsState=_magicToolsState - In the implementation block
@property (assign,nonatomic) long long brushResizeCount;                                                     //@synthesize brushResizeCount=_brushResizeCount - In the implementation block
@property (nonatomic,copy) NSString * brushStroke;                                                           //@synthesize brushStroke=_brushStroke - In the implementation block
@property (assign,nonatomic) BOOL withAttachment;                                                            //@synthesize withAttachment=_withAttachment - In the implementation block
@property (nonatomic,copy) NSString * audioFilterStyleId;                                                    //@synthesize audioFilterStyleId=_audioFilterStyleId - In the implementation block
@property (assign,nonatomic) long long contextFilterGeneratedCount;                                          //@synthesize contextFilterGeneratedCount=_contextFilterGeneratedCount - In the implementation block
@property (nonatomic,copy) NSString * contextFilterSelectedId;                                               //@synthesize contextFilterSelectedId=_contextFilterSelectedId - In the implementation block
@property (nonatomic,copy) NSString * contextFilterSkyType;                                                  //@synthesize contextFilterSkyType=_contextFilterSkyType - In the implementation block
@property (nonatomic,copy) NSString * contextFilterPortraitType;                                             //@synthesize contextFilterPortraitType=_contextFilterPortraitType - In the implementation block
@property (assign,nonatomic) BOOL contextFilterHighEndModelIsEnabled;                                        //@synthesize contextFilterHighEndModelIsEnabled=_contextFilterHighEndModelIsEnabled - In the implementation block
@property (assign,nonatomic) BOOL contextFilterIsSeen;                                                       //@synthesize contextFilterIsSeen=_contextFilterIsSeen - In the implementation block
@property (assign,nonatomic) BOOL contextFilterIsEnabled;                                                    //@synthesize contextFilterIsEnabled=_contextFilterIsEnabled - In the implementation block
@property (assign,nonatomic) BOOL visualFilterIsSeen;                                                        //@synthesize visualFilterIsSeen=_visualFilterIsSeen - In the implementation block
@property (assign,nonatomic) long long groupStoriesSendCount;                                                //@synthesize groupStoriesSendCount=_groupStoriesSendCount - In the implementation block
@property (assign,nonatomic) long long availableGroupStoriesCount;                                           //@synthesize availableGroupStoriesCount=_availableGroupStoriesCount - In the implementation block
@property (assign,nonatomic) long long expiredGroupStoryPostCount;                                           //@synthesize expiredGroupStoryPostCount=_expiredGroupStoryPostCount - In the implementation block
@property (assign,nonatomic) long long availableExpiredGroupStoryCount;                                      //@synthesize availableExpiredGroupStoryCount=_availableExpiredGroupStoryCount - In the implementation block
@property (assign,nonatomic) long long officialStoriesSendCount;                                             //@synthesize officialStoriesSendCount=_officialStoriesSendCount - In the implementation block
@property (assign,nonatomic) long long sharedStoriesSendCount;                                               //@synthesize sharedStoriesSendCount=_sharedStoriesSendCount - In the implementation block
@property (assign,nonatomic) long long viewMoreStoriesTapCount;                                              //@synthesize viewMoreStoriesTapCount=_viewMoreStoriesTapCount - In the implementation block
@property (assign,nonatomic) long long filterStackingButtonAddCount;                                         //@synthesize filterStackingButtonAddCount=_filterStackingButtonAddCount - In the implementation block
@property (assign,nonatomic) long long filterStackingButtonRemoveCount;                                      //@synthesize filterStackingButtonRemoveCount=_filterStackingButtonRemoveCount - In the implementation block
@property (nonatomic,copy) NSString * entryId;                                                               //@synthesize entryId=_entryId - In the implementation block
@property (nonatomic,copy) NSString * snapId;                                                                //@synthesize snapId=_snapId - In the implementation block
@property (assign,nonatomic) long long mediaFormat;                                                          //@synthesize mediaFormat=_mediaFormat - In the implementation block
@property (nonatomic,copy) NSString * spectaclesContentId;                                                   //@synthesize spectaclesContentId=_spectaclesContentId - In the implementation block
@property (nonatomic,copy) NSString * previewSaveStyle;                                                      //@synthesize previewSaveStyle=_previewSaveStyle - In the implementation block
@property (assign,nonatomic) long long groupNonUniqueUserRecipientCount;                                     //@synthesize groupNonUniqueUserRecipientCount=_groupNonUniqueUserRecipientCount - In the implementation block
@property (assign,nonatomic) long long groupUniqueUserRecipientCount;                                        //@synthesize groupUniqueUserRecipientCount=_groupUniqueUserRecipientCount - In the implementation block
@property (assign,nonatomic) long long totalUniqueUserRecipientCount;                                        //@synthesize totalUniqueUserRecipientCount=_totalUniqueUserRecipientCount - In the implementation block
@property (nonatomic,copy) NSString * topsnapAdId;                                                           //@synthesize topsnapAdId=_topsnapAdId - In the implementation block
@property (nonatomic,copy) NSString * topsnapAdRequestClientId;                                              //@synthesize topsnapAdRequestClientId=_topsnapAdRequestClientId - In the implementation block
@property (assign,nonatomic) long long filterSource;                                                         //@synthesize filterSource=_filterSource - In the implementation block
-(void)willEncodeObject;
-(id)awakeAfterFastCoding;
-(long long)swipeCount;
-(void)setSwipeCount:(long long)arg1 ;
-(NSString *)snapSessionId;
-(void)setSnapSessionId:(NSString *)arg1 ;
-(long long)filterIndexPos;
-(void)setFilterIndexPos:(long long)arg1 ;
-(NSString *)lensId;
-(NSString *)lensOptionId;
-(long long)lensIndexPos;
-(long long)storyPostCount;
-(void)setLensId:(NSString *)arg1 ;
-(void)setLensOptionId:(NSString *)arg1 ;
-(void)setLensIndexPos:(long long)arg1 ;
-(void)setStoryPostCount:(long long)arg1 ;
-(NSString *)snapId;
-(void)setSnapId:(NSString *)arg1 ;
-(NSString *)contextFilterSelectedId;
-(void)setContextFilterSelectedId:(NSString *)arg1 ;
-(NSString *)entryId;
-(void)setEntryId:(NSString *)arg1 ;
-(long long)mediaFormat;
-(void)setMediaFormat:(long long)arg1 ;
-(NSString *)snapcraftStyleId;
-(BOOL)cropping;
-(void)setSnapcraftStyleId:(NSString *)arg1 ;
-(void)setCropping:(BOOL)arg1 ;
-(long long)animatedSnapType;
-(NSString *)lensInfo;
-(NSString *)encryptedGeoData;
-(void)setEncryptedGeoData:(NSString *)arg1 ;
-(void)setLagunaUserAgent:(NSString *)arg1 ;
-(NSString *)lagunaUserAgent;
-(void)setWithGallery:(BOOL)arg1 ;
-(BOOL)withGallery;
-(void)setTagCount:(long long)arg1 ;
-(void)setTagFromCarouselCount:(long long)arg1 ;
-(long long)tagCount;
-(long long)tagFromCarouselCount;
-(void)setLagunaDeviceId:(NSString *)arg1 ;
-(NSString *)lagunaDeviceId;
-(void)setFilterInfo:(NSString *)arg1 ;
-(void)setFilterVisual:(NSString *)arg1 ;
-(NSString *)filterInfo;
-(NSString *)filterVisual;
-(void)setAnimatedStickerCount:(long long)arg1 ;
-(void)setAnimatedFilterCount:(long long)arg1 ;
-(void)setWithAnimated:(BOOL)arg1 ;
-(void)setMultiSnapCount:(long long)arg1 ;
-(void)setMultiSnapPreviewCount:(long long)arg1 ;
-(void)setMultiSnapOutputCount:(long long)arg1 ;
-(void)setHasSplit:(BOOL)arg1 ;
-(void)setHasIndividualCreativeTools:(BOOL)arg1 ;
-(void)setCaptionAddCount:(long long)arg1 ;
-(void)setCaptionUseCount:(long long)arg1 ;
-(void)setCaptionDeletionCount:(long long)arg1 ;
-(void)setCaptionTracking:(BOOL)arg1 ;
-(void)setCaptionHasStyling:(BOOL)arg1 ;
-(void)setSnapTimeIsLoop:(BOOL)arg1 ;
-(void)setStickerCount:(long long)arg1 ;
-(void)setStickerDeletionCount:(long long)arg1 ;
-(void)setStickerTrackingCount:(long long)arg1 ;
-(void)setStickerUserEnterSearchCount:(long long)arg1 ;
-(void)setStickerFromSearchCount:(long long)arg1 ;
-(void)setStickerAutoGeneratedUsageCount:(long long)arg1 ;
-(void)setFilterReverse:(BOOL)arg1 ;
-(void)setBrushResizeCount:(long long)arg1 ;
-(void)setPretypeStickerTagSelectCount:(long long)arg1 ;
-(void)setPrefixMatchStickerTagSelectCount:(long long)arg1 ;
-(void)setContextFilterGeneratedCount:(long long)arg1 ;
-(void)setContextFilterIsSeen:(BOOL)arg1 ;
-(void)setVisualFilterIsSeen:(BOOL)arg1 ;
-(void)setSaveCount:(long long)arg1 ;
-(void)setFilterInfoValue:(NSNumber *)arg1 ;
-(void)setWithMyStory:(BOOL)arg1 ;
-(void)setViewMoreStoriesTapCount:(long long)arg1 ;
-(void)setExpiredGroupStoryPostCount:(long long)arg1 ;
-(void)setAvailableExpiredGroupStoryCount:(long long)arg1 ;
-(void)setFilterStackingButtonAddCount:(long long)arg1 ;
-(void)setFilterStackingButtonRemoveCount:(long long)arg1 ;
-(void)setWithAttachment:(BOOL)arg1 ;
-(void)setFaceFrontCameraCount:(long long)arg1 ;
-(void)setFaceBackCameraCount:(long long)arg1 ;
-(void)setLensIndexCount:(long long)arg1 ;
-(void)setDeletedSegments:(long long)arg1 ;
-(void)setFilterMotion:(long long)arg1 ;
-(void)setFirstSwipeDirection:(long long)arg1 ;
-(void)setCaptionStyleList:(NSString *)arg1 ;
-(void)setBrushStroke:(NSString *)arg1 ;
-(void)setContextFilterSkyType:(NSString *)arg1 ;
-(void)setContextFilterPortraitType:(NSString *)arg1 ;
-(void)setLensBundleUrl:(NSString *)arg1 ;
-(void)setWidgetValueList:(NSString *)arg1 ;
-(long long)animatedStickerCount;
-(long long)animatedFilterCount;
-(BOOL)withAnimated;
-(long long)multiSnapCount;
-(long long)multiSnapPreviewCount;
-(long long)multiSnapOutputCount;
-(BOOL)hasSplit;
-(BOOL)hasIndividualCreativeTools;
-(long long)captionAddCount;
-(long long)captionUseCount;
-(long long)captionDeletionCount;
-(BOOL)captionTracking;
-(BOOL)captionHasStyling;
-(BOOL)snapTimeIsLoop;
-(long long)stickerCount;
-(long long)stickerDeletionCount;
-(long long)stickerTrackingCount;
-(long long)stickerUserEnterSearchCount;
-(long long)stickerFromSearchCount;
-(long long)stickerAutoGeneratedUsageCount;
-(BOOL)filterReverse;
-(long long)brushResizeCount;
-(long long)pretypeStickerTagSelectCount;
-(long long)prefixMatchStickerTagSelectCount;
-(long long)contextFilterGeneratedCount;
-(BOOL)contextFilterIsSeen;
-(BOOL)visualFilterIsSeen;
-(long long)saveCount;
-(NSNumber *)filterInfoValue;
-(BOOL)withMyStory;
-(long long)viewMoreStoriesTapCount;
-(long long)expiredGroupStoryPostCount;
-(long long)availableExpiredGroupStoryCount;
-(long long)filterStackingButtonAddCount;
-(long long)filterStackingButtonRemoveCount;
-(BOOL)withAttachment;
-(long long)faceFrontCameraCount;
-(long long)faceBackCameraCount;
-(long long)lensIndexCount;
-(long long)deletedSegments;
-(long long)filterMotion;
-(long long)firstSwipeDirection;
-(NSString *)captionStyleList;
-(NSString *)brushStroke;
-(NSString *)contextFilterSkyType;
-(NSString *)contextFilterPortraitType;
-(NSString *)lensBundleUrl;
-(NSString *)widgetValueList;
-(void)setFilterVenueYOffset:(double)arg1 ;
-(void)setVenueTapIndex:(unsigned long long)arg1 ;
-(void)setLensSource:(long long)arg1 ;
-(void)setCaptureSessionId:(NSString *)arg1 ;
-(double)filterVenueYOffset;
-(unsigned long long)venueTapIndex;
-(long long)lensSource;
-(NSString *)captureSessionId;
-(void)setFilterIndexCount:(long long)arg1 ;
-(void)setFilterSource:(long long)arg1 ;
-(long long)filterIndexCount;
-(long long)filterSource;
-(void)setMultiSnapPreviewIndex:(long long)arg1 ;
-(void)setMultiSnapOutputIndex:(long long)arg1 ;
-(long long)multiSnapPreviewIndex;
-(long long)multiSnapOutputIndex;
-(void)setMultiSnapIndex:(long long)arg1 ;
-(void)setWithOurStory:(BOOL)arg1 ;
-(void)setGroupNonUniqueUserRecipientCount:(long long)arg1 ;
-(void)setGroupUniqueUserRecipientCount:(long long)arg1 ;
-(void)setTotalUniqueUserRecipientCount:(long long)arg1 ;
-(void)setStickerPackIds:(NSSet *)arg1 ;
-(long long)multiSnapIndex;
-(BOOL)withOurStory;
-(long long)groupNonUniqueUserRecipientCount;
-(long long)groupUniqueUserRecipientCount;
-(long long)totalUniqueUserRecipientCount;
-(NSSet *)stickerPackIds;
-(void)setTopsnapAdId:(NSString *)arg1 ;
-(NSString *)topsnapAdId;
-(void)setGalleryMediaType:(long long)arg1 ;
-(long long)galleryMediaType;
-(void)setLowLightStatus:(long long)arg1 ;
-(long long)lowLightStatus;
-(void)setGalleryCollectionCategory:(NSString *)arg1 ;
-(NSString *)galleryCollectionCategory;
-(void)setFilterStreakValue:(long long)arg1 ;
-(long long)filterStreakValue;
-(void)setMeo:(BOOL)arg1 ;
-(void)setHasCreative:(BOOL)arg1 ;
-(BOOL)meo;
-(BOOL)hasCreative;
-(void)setShareChannel:(NSString *)arg1 ;
-(NSString *)shareChannel;
-(void)setWithSnap:(BOOL)arg1 ;
-(BOOL)withSnap;
-(void)setCameraFlipsWhileRecording:(long long)arg1 ;
-(long long)cameraFlipsWhileRecording;
-(void)setStartRecordingTimestamp:(NSDate *)arg1 ;
-(void)setLowLightBoostEnabledBeforeCapture:(BOOL)arg1 ;
-(id)mediaTypeString;
-(void)setSavedToGalleryByScreenshot:(BOOL)arg1 ;
-(BOOL)shouldSaveToMemories;
-(void)setGroupStoriesSendCount:(long long)arg1 ;
-(void)setAvailableGroupStoriesCount:(long long)arg1 ;
-(void)setOfficialStoriesSendCount:(long long)arg1 ;
-(void)setSharedStoriesSendCount:(long long)arg1 ;
-(NSString *)filterGeoId;
-(BOOL)snapDidSendToChat;
-(BOOL)snapDidPostToStory;
-(BOOL)snapDidSaveAsCopy;
-(BOOL)snapDidSaveToReplace;
-(NSString *)audioFilterStyleId;
-(BOOL)contextFilterHighEndModelIsEnabled;
-(BOOL)contextFilterIsEnabled;
-(SCGalleryUserContext *)galleryUserContext;
-(NSString *)entryExternalId;
-(void)setGalleryUserContext:(SCGalleryUserContext *)arg1 ;
-(NSString *)spectaclesContentId;
-(NSDate *)snapCreateTime;
-(SCFilterViewMetrics *)infoFilterViewMetrics;
-(void)setSnapCreateTime:(NSDate *)arg1 ;
-(void)setEntryExternalId:(NSString *)arg1 ;
-(void)setSpectaclesContentId:(NSString *)arg1 ;
-(void)setFilterGeoId:(NSString *)arg1 ;
-(void)setAudioFilterStyleId:(NSString *)arg1 ;
-(void)setLensConfigurations:(NSArray *)arg1 ;
-(NSString *)previewSaveStyle;
-(BOOL)hasGeoContents;
-(void)setSnapDidSaveAsCopy:(BOOL)arg1 ;
-(void)setSnapDidSaveToReplace:(BOOL)arg1 ;
-(BOOL)flashOn;
-(BOOL)frontCamera;
-(void)setFrontCamera:(BOOL)arg1 ;
-(BOOL)lowLightBoostEnabledBeforeCapture;
-(NSNumber *)withMyStoryPrivacyOverride;
-(void)setWithMyStoryPrivacyOverride:(NSNumber *)arg1 ;
-(BOOL)withLocationEnabled;
-(void)setWithLocationEnabled:(BOOL)arg1 ;
-(BOOL)savedToGalleryByScreenshot;
-(BOOL)savedToGalleryByScreenRecording;
-(void)setSavedToGalleryByScreenRecording:(BOOL)arg1 ;
-(float)viewTime;
-(void)setViewTime:(float)arg1 ;
-(long long)filterSeenCount;
-(void)setFilterSeenCount:(long long)arg1 ;
-(long long)invitedRecipientCount;
-(void)setInvitedRecipientCount:(long long)arg1 ;
-(long long)invitedRecipientShown;
-(void)setInvitedRecipientShown:(long long)arg1 ;
-(NSString *)geoFilterDynamicContextSources;
-(void)setGeoFilterDynamicContextSources:(NSString *)arg1 ;
-(NSArray *)lensConfigurations;
-(BOOL)hasGeoLens;
-(void)setHasGeoLens:(BOOL)arg1 ;
-(BOOL)hasSponsoredLens;
-(void)setHasSponsoredLens:(BOOL)arg1 ;
-(long long)unverifiedTagCount;
-(void)setUnverifiedTagCount:(long long)arg1 ;
-(NSDate *)startRecordingTimestamp;
-(void)setInfoFilterViewMetrics:(SCFilterViewMetrics *)arg1 ;
-(NSDate *)lastFilterRenderTime;
-(void)setLastFilterRenderTime:(NSDate *)arg1 ;
-(NSString *)filterRenderTimes;
-(void)setFilterRenderTimes:(NSString *)arg1 ;
-(long long)filterStreakType;
-(void)setFilterStreakType:(long long)arg1 ;
-(SCFilterCarouselLoggingParameters *)filterCarouselLoggingParameters;
-(void)setFilterCarouselLoggingParameters:(SCFilterCarouselLoggingParameters *)arg1 ;
-(void)setShouldSaveToMemories:(BOOL)arg1 ;
-(void)setSnapDidSendToChat:(BOOL)arg1 ;
-(void)setSnapDidPostToStory:(BOOL)arg1 ;
-(long long)gallerySendSource;
-(void)setGallerySendSource:(long long)arg1 ;
-(long long)emojiStickersCount;
-(void)setEmojiStickersCount:(long long)arg1 ;
-(long long)bitmojiStickersCount;
-(void)setBitmojiStickersCount:(long long)arg1 ;
-(long long)bitmojiGeoStickersCount;
-(void)setBitmojiGeoStickersCount:(long long)arg1 ;
-(long long)snapchatStickersCount;
-(void)setSnapchatStickersCount:(long long)arg1 ;
-(long long)emojiStickersFromRecentCount;
-(void)setEmojiStickersFromRecentCount:(long long)arg1 ;
-(long long)bitmojiStickersFromRecentCount;
-(void)setBitmojiStickersFromRecentCount:(long long)arg1 ;
-(long long)bitmojiGeoStickersFromRecentCount;
-(void)setBitmojiGeoStickersFromRecentCount:(long long)arg1 ;
-(long long)snapchatStickersFromRecentCount;
-(void)setSnapchatStickersFromRecentCount:(long long)arg1 ;
-(long long)infoStickersCount;
-(void)setInfoStickersCount:(long long)arg1 ;
-(long long)contextualStickersCount;
-(void)setContextualStickersCount:(long long)arg1 ;
-(long long)infoStickerTapCount;
-(void)setInfoStickerTapCount:(long long)arg1 ;
-(long long)unlockableStickerCount;
-(void)setUnlockableStickerCount:(long long)arg1 ;
-(long long)giphyStickerCount;
-(void)setGiphyStickerCount:(long long)arg1 ;
-(NSString *)emojiStickersList;
-(void)setEmojiStickersList:(NSString *)arg1 ;
-(NSString *)bitmojiStickersList;
-(void)setBitmojiStickersList:(NSString *)arg1 ;
-(NSString *)bitmojiGeoStickersList;
-(void)setBitmojiGeoStickersList:(NSString *)arg1 ;
-(NSString *)snapchatStickersList;
-(void)setSnapchatStickersList:(NSString *)arg1 ;
-(NSString *)infoStickersList;
-(void)setInfoStickersList:(NSString *)arg1 ;
-(NSString *)geofilterWidgetValueList;
-(void)setGeofilterWidgetValueList:(NSString *)arg1 ;
-(NSString *)contextualStickersList;
-(void)setContextualStickersList:(NSString *)arg1 ;
-(NSString *)unlockableStickerList;
-(void)setUnlockableStickerList:(NSString *)arg1 ;
-(NSString *)giphyStickerList;
-(void)setGiphyStickerList:(NSString *)arg1 ;
-(long long)customStickerCreationCount;
-(void)setCustomStickerCreationCount:(long long)arg1 ;
-(long long)customStickerDeletionCount;
-(void)setCustomStickerDeletionCount:(long long)arg1 ;
-(long long)customStickerSelectionCount;
-(void)setCustomStickerSelectionCount:(long long)arg1 ;
-(long long)customStickerSelectionFromRecentCount;
-(void)setCustomStickerSelectionFromRecentCount:(long long)arg1 ;
-(NSString *)encodedStickers;
-(void)setEncodedStickers:(NSString *)arg1 ;
-(NSString *)correspondentIdsString;
-(void)setCorrespondentIdsString:(NSString *)arg1 ;
-(NSString *)mischiefIdsString;
-(void)setMischiefIdsString:(NSString *)arg1 ;
-(NSString *)venueID;
-(void)setVenueID:(NSString *)arg1 ;
-(BOOL)hasBackgroundFilter;
-(void)setHasBackgroundFilter:(BOOL)arg1 ;
-(SCMagicToolsState *)magicToolsState;
-(void)setMagicToolsState:(SCMagicToolsState *)arg1 ;
-(void)setContextFilterHighEndModelIsEnabled:(BOOL)arg1 ;
-(void)setContextFilterIsEnabled:(BOOL)arg1 ;
-(long long)groupStoriesSendCount;
-(long long)availableGroupStoriesCount;
-(long long)officialStoriesSendCount;
-(long long)sharedStoriesSendCount;
-(void)setPreviewSaveStyle:(NSString *)arg1 ;
-(NSString *)topsnapAdRequestClientId;
-(void)setTopsnapAdRequestClientId:(NSString *)arg1 ;
-(id)toUnlockablesSnapInfo;
-(void)updateLensDataWithConfiguration:(id)arg1 ;
-(void)_legacyUpdateLensDataWithConfiguration:(id)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)setOrientation:(long long)arg1 ;
-(long long)orientation;
-(void)setSource:(long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(unsigned long long)tapCount;
-(void)setTapCount:(unsigned long long)arg1 ;
-(long long)source;
-(NSString *)destinations;
-(void)setVersion:(NSNumber *)arg1 ;
-(NSNumber *)version;
-(id)awakeAfterUsingCoder:(id)arg1 ;
-(void)setRecipientCount:(long long)arg1 ;
-(long long)caption;
-(BOOL)hasLabel;
-(void)setCaption:(long long)arg1 ;
-(void)setFlashOn:(BOOL)arg1 ;
-(BOOL)handsFree;
-(void)setHandsFree:(BOOL)arg1 ;
-(void)setEntryType:(long long)arg1 ;
-(long long)mediaType;
-(void)setMediaType:(long long)arg1 ;
-(long long)entryType;
-(void)setDestinations:(NSString *)arg1 ;
-(void)updateWithConfiguration:(id)arg1 ;
-(long long)recipientCount;
-(BOOL)reply;
-(void)setReply:(BOOL)arg1 ;
-(BOOL)drawing;
-(void)setDrawing:(BOOL)arg1 ;
-(void)setHasLabel:(BOOL)arg1 ;
-(BOOL)trimmed;
-(void)setTrimmed:(BOOL)arg1 ;
-(void)setMediaDuration:(float)arg1 ;
-(float)mediaDuration;
-(void)setCameraSource:(long long)arg1 ;
-(long long)cameraSource;
@end

