/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:03 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface SCSnapchattersFideliusDeviceInfo : NSObject <NSCopying> {

	NSString* _outBeta;
	long long _version;

}

@property (nonatomic,copy,readonly) NSString * outBeta;              //@synthesize outBeta=_outBeta - In the implementation block
@property (nonatomic,readonly) long long version;                    //@synthesize version=_version - In the implementation block
-(NSString *)outBeta;
-(id)initWithOutBeta:(id)arg1 version:(long long)arg2 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)version;
@end

