/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:07 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class SCSessionRequestManager;

@interface SCSnapTokenNetworkRequests : NSObject {

	SCSessionRequestManager* _sessionRequestManager;

}

@property (nonatomic,readonly) SCSessionRequestManager * sessionRequestManager;              //@synthesize sessionRequestManager=_sessionRequestManager - In the implementation block
-(id)initWithUserSessionRequestManager:(id)arg1 ;
-(void)fetchSnapSessionForUserId:(id)arg1 serverScopeNames:(id)arg2 completionPerformer:(id)arg3 successBlock:(/*^block*/id)arg4 failureBlock:(/*^block*/id)arg5 ;
-(void)fetchAccessTokensForServerScopeNames:(id)arg1 refreshToken:(id)arg2 isPrefetch:(unsigned char)arg3 completionPerformer:(id)arg4 successBlock:(/*^block*/id)arg5 failureBlock:(/*^block*/id)arg6 ;
-(id)_buildAccessTokenSojuRequestForRefreshToken:(id)arg1 serverScopeNames:(id)arg2 ;
-(SCSessionRequestManager *)sessionRequestManager;
-(void)_accessTokenHttpSuccessForResponseDictionary:(id)arg1 successBlock:(/*^block*/id)arg2 failureBlock:(/*^block*/id)arg3 ;
-(id)_buildSnapSessionSojuRequestForUserId:(id)arg1 serverScopeNames:(id)arg2 ;
-(void)_snapSessionHttpSuccessWithResponseDictionary:(id)arg1 successBlock:(/*^block*/id)arg2 failureBlock:(/*^block*/id)arg3 ;
-(void)_accessTokenSuccessWithSojuResponse:(id)arg1 successBlock:(/*^block*/id)arg2 failureBlock:(/*^block*/id)arg3 ;
@end

