/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:33 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCSnapAirLogWriter.h>

@class NSArray;

@interface SCSnapchatInternalShakeLogWriter : NSObject <SCSnapAirLogWriter>

@property (nonatomic,readonly) NSArray * asyncLogSources; 
+(id)shared;
-(void)writeLogsToURL:(id)arg1 ;
-(BOOL)_writeDataWithFileName:(id)arg1 data:(id)arg2 baseUrl:(id)arg3 ;
-(NSArray *)asyncLogSources;
-(void)_dumpFunctionTraceLogs:(id)arg1 ;
-(void)_dumpNetWorkTraceLogs:(id)arg1 ;
-(void)_dumpAllLogs:(id)arg1 ;
-(void)_dumpExpreimentContexts:(id)arg1 ;
-(void)_dumpAudioSessionInfo:(id)arg1 ;
-(void)_dumpManagedCapturededInfo:(id)arg1 ;
-(void)_dumpBroadcastInfo:(id)arg1 ;
-(void)_dumpAdsLog:(id)arg1 ;
-(void)_dumpStudySettings:(id)arg1 ;
-(void)_dumpFideliusLogs:(id)arg1 ;
-(void)_dumpShazamAudio:(id)arg1 ;
-(id)_trimTimestampForNetworkTraceFile:(id)arg1 ;
@end

