/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:10 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SCSnapAdsAdResponseRendition : NSObject {

	long long _width;
	long long _height;
	double _fileSize;
	NSString* _mediaUrl;

}

@property (assign,nonatomic) long long width;                //@synthesize width=_width - In the implementation block
@property (assign,nonatomic) long long height;               //@synthesize height=_height - In the implementation block
@property (assign,nonatomic) double fileSize;                //@synthesize fileSize=_fileSize - In the implementation block
@property (nonatomic,copy) NSString * mediaUrl;              //@synthesize mediaUrl=_mediaUrl - In the implementation block
-(NSString *)mediaUrl;
-(void)setMediaUrl:(NSString *)arg1 ;
-(double)getAspectRatio;
-(long long)getQuality;
-(double)getFileSize;
-(long long)getHeight;
-(id)getMediaUrl;
-(id)initWithMediaUrl:(id)arg1 width:(long long)arg2 height:(long long)arg3 fileSize:(double)arg4 ;
-(long long)width;
-(long long)height;
-(void)setWidth:(long long)arg1 ;
-(void)setHeight:(long long)arg1 ;
-(double)fileSize;
-(void)setFileSize:(double)arg1 ;
-(long long)getWidth;
@end

