/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:46 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface SCSpectaclesECBPacketEncryptor : NSObject {

	void* _encryptorContext;

}

@property (assign,nonatomic) void* encryptorContext;              //@synthesize encryptorContext=_encryptorContext - In the implementation block
-(void*)encryptorContext;
-(BOOL)setTxNonce:(id)arg1 ;
-(BOOL)setRxNonce:(id)arg1 ;
-(BOOL)setTxSalt:(id)arg1 ;
-(BOOL)setRxSalt:(id)arg1 ;
-(BOOL)connectionReady;
-(id)decryptMessage:(id)arg1 ;
-(id)encryptMessage:(id)arg1 ;
-(void)setEncryptorContext:(void*)arg1 ;
-(id)init;
-(void)dealloc;
-(BOOL)setEncryptionKey:(id)arg1 ;
@end

