/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:16 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSData;

@interface SCSpectaclesPairingCandidateCode : NSObject {

	NSData* _candidateCode;
	NSData* _advertisementCode;
	NSData* _verificationCode;

}

@property (nonatomic,readonly) NSData * candidateCode;                  //@synthesize candidateCode=_candidateCode - In the implementation block
@property (nonatomic,readonly) NSData * advertisementCode;              //@synthesize advertisementCode=_advertisementCode - In the implementation block
@property (nonatomic,readonly) NSData * verificationCode;               //@synthesize verificationCode=_verificationCode - In the implementation block
+(id)backupPairingCodeWithTapConfirm;
+(id)backupPairingCodeWithoutTapConfirm;
-(NSData *)candidateCode;
-(NSData *)advertisementCode;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)initWithData:(id)arg1 ;
-(NSData *)verificationCode;
@end

