/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:02 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@class NSString, NSMutableArray, SCSSRVResultSource, GPBAny;

@interface SCSSRVQueryResult : GPBMessage

@property (nonatomic,copy) NSString * query; 
@property (assign,nonatomic) long long numResults; 
@property (nonatomic,copy) NSString * deeplinkURL; 
@property (nonatomic,retain) NSMutableArray * sampleResultsArray; 
@property (nonatomic,readonly) unsigned long long sampleResultsArray_Count; 
@property (nonatomic,retain) SCSSRVResultSource * source; 
@property (assign,nonatomic) BOOL hasSource; 
@property (nonatomic,retain) GPBAny * vendorSpecificData; 
@property (assign,nonatomic) BOOL hasVendorSpecificData; 
+(id)descriptor;
@end

