/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:02 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@interface SCSSMUserStoryInteractionFeatures : GPBMessage

@property (assign,nonatomic) unsigned long long storyKey; 
@property (assign,nonatomic) unsigned numWatches; 
@property (assign,nonatomic) unsigned snapCompletionPercent; 
@property (assign,nonatomic) unsigned watchTimePercent; 
@property (assign,nonatomic) unsigned numSnapsInStory; 
@property (assign,nonatomic) unsigned storyLengthSeconds; 
@property (assign,nonatomic) unsigned totalImpressionScore; 
@property (assign,nonatomic) BOOL subscribed; 
@property (assign,nonatomic) BOOL hidden; 
@property (assign,nonatomic) int storyEntrance; 
@property (assign,nonatomic) int storyExit; 
+(id)descriptor;
@end

