/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:02 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface SCStoriesSnapFraming : NSObject <NSCopying> {

	long long _createTimeUTCms;
	long long _source;

}

@property (nonatomic,readonly) long long createTimeUTCms;              //@synthesize createTimeUTCms=_createTimeUTCms - In the implementation block
@property (nonatomic,readonly) long long source;                       //@synthesize source=_source - In the implementation block
-(id)initWithCreateTimeUTCms:(long long)arg1 source:(long long)arg2 ;
-(long long)createTimeUTCms;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(long long)source;
@end

