/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:51 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UITextFieldDelegate.h>

@protocol SCStickerSearchBarDelegate;
@class UIButton, UITextField, NSString;

@interface SCStickerSearchBar : UIView <UITextFieldDelegate> {

	UIButton* _searchIconView;
	UIButton* _xButton;
	UITextField* _inputTextField;
	BOOL _enteredText;
	id<SCStickerSearchBarDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<SCStickerSearchBarDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * placeholder; 
@property (nonatomic,copy) NSString * text; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)xButtonPressed;
-(void)textFieldDidChange;
-(void)clearTextField;
-(void)searchIconPressed;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)setDelegate:(id<SCStickerSearchBarDelegate>)arg1 ;
-(id<SCStickerSearchBarDelegate>)delegate;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(NSString *)text;
-(void)setText:(NSString *)arg1 ;
-(BOOL)isFirstResponder;
-(void)textFieldDidBeginEditing:(id)arg1 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)setPlaceholder:(NSString *)arg1 ;
-(NSString *)placeholder;
@end

