/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:22 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIViewControllerAnimatedTransitioning.h>

@protocol UIViewControllerContextTransitioning;
@class SCAnimationPhaseCoordinator, SCPassthroughViewsCoordinator, NSString;

@interface SCSwipeTransitionController : NSObject <UIViewControllerAnimatedTransitioning> {

	unsigned long long _direction;
	double _animationDuration;
	SCAnimationPhaseCoordinator* _animationCoordinator;
	id<UIViewControllerContextTransitioning> _transitionContext;
	SCPassthroughViewsCoordinator* _passthroughViewsCoordinator;
	BOOL _presenting;

}

@property (assign,nonatomic) BOOL presenting;                       //@synthesize presenting=_presenting - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(CGPoint)_originPointForDirection:(unsigned long long)arg1 presentingViewController:(id)arg2 presentedViewController:(id)arg3 ;
-(id)presentationAnimationPhaseFromViewController:(id)arg1 toViewController:(id)arg2 ;
-(id)dismissalAnimationPhaseFromViewController:(id)arg1 toViewController:(id)arg2 ;
-(void)animateTransition:(BOOL)arg1 presentedViewController:(id)arg2 presentingViewController:(id)arg3 ;
-(id)_frameChangeAnimationPhaseWithDestinationFrame:(CGRect)arg1 view:(id)arg2 ;
-(BOOL)_isInteractive;
-(id)initWithDirection:(unsigned long long)arg1 animationDuration:(double)arg2 passthroughViews:(id)arg3 ;
-(void)resetWithDuration:(double)arg1 ;
-(double)transitionDuration:(id)arg1 ;
-(void)animateTransition:(id)arg1 ;
-(BOOL)presenting;
-(void)setPresenting:(BOOL)arg1 ;
-(BOOL)wasCancelled;
@end

