/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:47 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SCTraceFileReader.h>

@class NSMutableArray, NSString;

@interface SCTraceFileCatapultJsonReader : NSObject <SCTraceFileReader> {

	NSMutableArray* _catapultJson;
	unordered_map<unsigned long long, std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> >, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long>, std::__1::allocator<std::__1::pair<const unsigned long long, std::__1::vector<unsigned long long, std::__1::allocator<unsigned long long> > > > >* _enclosedTimestamp;
	unsigned long long _minDuration;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)durationEventBegin:(const char*)arg1 category:(id)arg2 timestamp:(unsigned long long)arg3 threadtime:(unsigned long long)arg4 tid:(unsigned long long)arg5 ;
-(void)durationEventSignal:(id)arg1 category:(id)arg2 timestamp:(unsigned long long)arg3 threadtime:(unsigned long long)arg4 tid:(unsigned long long)arg5 ;
-(void)durationEventEndWithCategory:(id)arg1 timestamp:(unsigned long long)arg2 threadtime:(unsigned long long)arg3 tid:(unsigned long long)arg4 ;
-(void)flowEventBegin:(const char*)arg1 category:(id)arg2 timestamp:(unsigned long long)arg3 uid:(unsigned)arg4 tid:(unsigned long long)arg5 ;
-(void)flowEventEnd:(const char*)arg1 category:(id)arg2 timestamp:(unsigned long long)arg3 uid:(unsigned)arg4 tid:(unsigned long long)arg5 ;
-(void)asyncEventBegin:(id)arg1 category:(id)arg2 timestamp:(unsigned long long)arg3 uid:(unsigned)arg4 tid:(unsigned long long)arg5 ;
-(void)asyncEventSignal:(id)arg1 category:(id)arg2 timestamp:(unsigned long long)arg3 uid:(unsigned)arg4 tid:(unsigned long long)arg5 ;
-(void)asyncEventEnd:(id)arg1 category:(id)arg2 timestamp:(unsigned long long)arg3 uid:(unsigned)arg4 tid:(unsigned long long)arg5 ;
-(id)initWithMinDuration:(unsigned long long)arg1 ;
-(id)catapultJson;
@end

