/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:53 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCTV3TooltipServices.h>

@protocol SCTV3TooltipServices <NSObject>
@required
-(void)resetAllTooltips;
-(BOOL)isTooltipVisible:(unsigned long long)arg1;
-(void)hideTooltip:(unsigned long long)arg1 forever:(BOOL)arg2;
-(void)showTooltip:(unsigned long long)arg1;

@end


@protocol SCTV3TooltipServicesDelegate;
@class SCUserToolTipStatus, SCExperimentManager, NSMutableDictionary, NSString;

@interface SCTV3TooltipServices : NSObject <SCTV3TooltipServices> {

	SCUserToolTipStatus* _tooltipStatus;
	SCExperimentManager* _experimentManager;
	NSMutableDictionary* _tooltipViews;
	BOOL _syncScheduled;
	id<SCTV3TooltipServicesDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<SCTV3TooltipServicesDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)resetAllTooltips;
-(BOOL)isTooltipVisible:(unsigned long long)arg1 ;
-(void)hideTooltip:(unsigned long long)arg1 forever:(BOOL)arg2 ;
-(void)showTooltip:(unsigned long long)arg1 ;
-(id)initWithExperimentManager:(id)arg1 ;
-(void)_synchronizeTooltipStatus;
-(BOOL)_shouldShowTooltip:(unsigned long long)arg1 ;
-(void)_markTooltipHasShown:(unsigned long long)arg1 ;
-(void)_reportExistingUsersTooltipShownEvent;
-(void)setDelegate:(id<SCTV3TooltipServicesDelegate>)arg1 ;
-(id<SCTV3TooltipServicesDelegate>)delegate;
@end

