/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:48 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <UIKit/UIView.h>

@class SCProfileHeaderView, UIScrollView, SCProfileIdentityCarouselView, UICollectionView, UIView, SCProfileChatInputBarView;

@interface SCUnifiedProfileView : UIView {

	double _listSectionListHeight;
	SCProfileHeaderView* _headerView;
	UIScrollView* _pageContentView;
	SCProfileIdentityCarouselView* _identityCarouselView;
	UICollectionView* _listSectionView;
	UIView* _tabCarouselView;
	SCProfileChatInputBarView* _chatInputBarView;

}

@property (nonatomic,readonly) SCProfileHeaderView * headerView;                                  //@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,readonly) UIScrollView * pageContentView;                                    //@synthesize pageContentView=_pageContentView - In the implementation block
@property (nonatomic,readonly) SCProfileIdentityCarouselView * identityCarouselView;              //@synthesize identityCarouselView=_identityCarouselView - In the implementation block
@property (nonatomic,retain) UICollectionView * listSectionView;                                  //@synthesize listSectionView=_listSectionView - In the implementation block
@property (nonatomic,retain) UIView * tabCarouselView;                                            //@synthesize tabCarouselView=_tabCarouselView - In the implementation block
@property (nonatomic,retain) SCProfileChatInputBarView * chatInputBarView;                        //@synthesize chatInputBarView=_chatInputBarView - In the implementation block
-(UIScrollView *)pageContentView;
-(void)setListSectionView:(UICollectionView *)arg1 ;
-(void)setTabCarouselView:(UIView *)arg1 ;
-(void)setChatInputBarView:(SCProfileChatInputBarView *)arg1 ;
-(SCProfileIdentityCarouselView *)identityCarouselView;
-(UICollectionView *)listSectionView;
-(UIView *)tabCarouselView;
-(SCProfileChatInputBarView *)chatInputBarView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)dealloc;
-(SCProfileHeaderView *)headerView;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
@end

