/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:53 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>
#import <Snapchat/SCUnlockableCommonCacheDelegate.h>

@class SCUnlockablesCommonDataStoreListenerAnnouncer, SCUserSession, NSDictionary, NSString;

@interface SCUnlockablesCommonDataStore : NSObject <NSCoding, SCUnlockableCommonCacheDelegate> {

	SCUnlockablesCommonDataStoreListenerAnnouncer* _announcer;
	SCUserSession* _userSession;
	NSDictionary* _unlockableCaches;

}

@property (nonatomic,retain) NSDictionary * unlockableCaches;              //@synthesize unlockableCaches=_unlockableCaches - In the implementation block
@property (nonatomic,readonly) SCUserSession * userSession;                //@synthesize userSession=_userSession - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(void)_removeSavedState;
+(id)path:(BOOL)arg1 ;
+(BOOL)isUsingGtqUnlockablesData:(id)arg1 ;
-(void)_saveState;
-(void)_subscribeForNotifications;
-(void)upsert:(id)arg1 cacheType:(long long)arg2 forLocation:(id)arg3 fromSources:(id)arg4 ;
-(void)upsert:(id)arg1 cacheType:(long long)arg2 forLocation:(id)arg3 fromSources:(id)arg4 completion:(/*^block*/id)arg5 ;
-(void)preFetch:(id)arg1 forCacheType:(long long)arg2 ;
-(void)removeUnlockablesById:(id)arg1 ;
-(void)_setUserSession:(id)arg1 ;
-(void)unlockableCache:(id)arg1 readyForPreFetch:(id)arg2 ;
-(void)unlockableCache:(id)arg1 didUpdate:(id)arg2 ;
-(id)initWithUnlockables:(id)arg1 ;
-(NSDictionary *)unlockableCaches;
-(void)setUnlockableCaches:(NSDictionary *)arg1 ;
-(id)init;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(void)clear;
-(SCUserSession *)userSession;
-(void)addListener:(id)arg1 ;
-(void)removeListener:(id)arg1 ;
-(void)updateLocation:(id)arg1 ;
@end

