/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:07 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCRequest.h>

@class NSDictionary, NSMutableURLRequest, NSURL;

@interface SCUploadRequest : SCRequest {

	NSDictionary* _parameters;
	NSDictionary* _additionalHTTPHeaders;
	NSMutableURLRequest* _urlRequest;
	NSURL* _uploadFileURL;
	NSURL* _url;

}
-(void)initializeURLRequestWithAuthenticator:(id)arg1 ;
-(void)executeWithAuthenticator:(id)arg1 completionQueue:(id)arg2 completionBlock:(/*^block*/id)arg3 ;
-(id)initWithURL:(id)arg1 parameters:(id)arg2 uploadFileURL:(id)arg3 additionalHTTPHeaders:(id)arg4 key:(id)arg5 contexts:(id)arg6 priority:(long long)arg7 fallbackPriority:(long long)arg8 connectivity:(long long)arg9 requestParser:(id)arg10 requestType:(long long)arg11 method:(long long)arg12 authenticated:(BOOL)arg13 requestTimestamp:(double)arg14 ;
-(id)description;
-(id)url;
-(id)path;
-(double)timeoutInterval;
@end

