/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:17 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Snapchat/Snapchat-Structs.h>
@class NSMutableArray, SCFrameRateEntry;

@interface SCVideoFrameDropCounter : NSObject {

	long long _frameCount;
	long long _stickyFrameCount;
	long long _severeStickyFrameCount;
	SCD_Struct_LS191 _targetInterval;
	SCD_Struct_LS191 _startTime;
	SCD_Struct_LS191 _currentTime;
	NSMutableArray* _frameDropLengths;
	BOOL _switchingCamera;
	BOOL _lensesActive;

}

@property (nonatomic,readonly) SCFrameRateEntry * frameRateEntry; 
-(id)initWithTargetFramerate:(double)arg1 ;
-(void)processFrameTime:(SCD_Struct_LS191)arg1 ;
-(SCFrameRateEntry *)frameRateEntry;
-(void)willChangeCaptureDevicePosition;
-(void)setLensesActive:(BOOL)arg1 ;
@end

