/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:51 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCWebScriptHelperDelegate.h>

@protocol SCWebImageScraperClientDelegate;
@class NSMutableDictionary, NSString, SCWebScriptHelper, SCUserSession;

@interface SCWebImageScraperClient : NSObject <SCWebScriptHelperDelegate> {

	NSMutableDictionary* _dummyImageCache;
	NSMutableDictionary* _websiteLinks;
	BOOL _loadingImages;
	NSString* _pageAbsoluteUrl;
	SCWebScriptHelper* _scriptHelper;
	SCUserSession* _userSession;
	int _state;
	id<SCWebImageScraperClientDelegate> _delegate;
	NSString* _requestId;

}

@property (assign,nonatomic) int state;                                                        //@synthesize state=_state - In the implementation block
@property (assign,nonatomic,__weak) id<SCWebImageScraperClientDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSString * requestId;                                           //@synthesize requestId=_requestId - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithUserSession:(id)arg1 ;
-(void)loadImagesFromUrl:(id)arg1 ;
-(id)imagesForUrl:(id)arg1 ;
-(void)resetRequest;
-(void)_receivedImage:(id)arg1 pageUrl:(id)arg2 imageSrcUrl:(id)arg3 ;
-(void)_loadImage:(id)arg1 scriptHelper:(id)arg2 pageUrl:(id)arg3 ;
-(void)webScriptHelper:(id)arg1 isReadyWithState:(int)arg2 ;
-(void)webScriptHelper:(id)arg1 isReadyWithTitle:(id)arg2 ;
-(void)webScriptHelper:(id)arg1 didEvaluate:(id)arg2 withResult:(id)arg3 ;
-(void)webScriptHelper:(id)arg1 didNotEvaluate:(id)arg2 ;
-(void)clearCacheForUrl:(id)arg1 ;
-(void)setDelegate:(id<SCWebImageScraperClientDelegate>)arg1 ;
-(id<SCWebImageScraperClientDelegate>)delegate;
-(int)state;
-(void)setState:(int)arg1 ;
-(NSString *)requestId;
-(void)clearAll;
@end

