/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:56 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SOJUSnapAdsPortalMetricsRequestBuilder : NSObject {

	NSString* _adId;
	NSString* _startTime;
	NSString* _endTime;
	NSString* _entityType;
	NSString* _entityId;

}
+(id)withJUSnapAdsPortalMetricsRequest:(id)arg1 ;
-(id)setEntityTypeEnum:(long long)arg1 ;
-(id)setAdId:(id)arg1 ;
-(id)setStartTime:(id)arg1 ;
-(id)build;
-(id)setEndTime:(id)arg1 ;
-(id)setEntityType:(id)arg1 ;
-(id)setEntityId:(id)arg1 ;
@end

