/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:56 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SOJUUnlockablesAppInstallAttachment.h>
@class NSString;


@protocol SOJUUnlockablesAppInstallAttachment <NSObject,NSCoding,NSCopying>
@property (nonatomic,copy,readonly) NSString * appName; 
@property (nonatomic,copy,readonly) NSString * iosAppId; 
@property (nonatomic,copy,readonly) NSString * androidAppUrl; 
@property (nonatomic,copy,readonly) NSString * appIconUrl; 
@required
-(NSString *)iosAppId;
-(NSString *)androidAppUrl;
-(NSString *)appIconUrl;
-(NSString *)appName;

@end


@class NSString;

@interface SOJUUnlockablesAppInstallAttachment : NSObject <SOJUUnlockablesAppInstallAttachment> {

	NSString* _appName;
	NSString* _iosAppId;
	NSString* _androidAppUrl;
	NSString* _appIconUrl;

}

@property (nonatomic,copy,readonly) NSString * appName;                    //@synthesize appName=_appName - In the implementation block
@property (nonatomic,copy,readonly) NSString * iosAppId;                   //@synthesize iosAppId=_iosAppId - In the implementation block
@property (nonatomic,copy,readonly) NSString * androidAppUrl;              //@synthesize androidAppUrl=_androidAppUrl - In the implementation block
@property (nonatomic,copy,readonly) NSString * appIconUrl;                 //@synthesize appIconUrl=_appIconUrl - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)fasterCodingVersion;
+(unsigned long long*)fasterCodingKeys;
+(BOOL)canInitFromProto;
-(BOOL)preferFasterCoding;
-(void)encodeWithFasterCoder:(id)arg1 ;
-(void)decodeWithFasterDecoder:(id)arg1 ;
-(void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2 ;
-(id)toJson;
-(NSString *)iosAppId;
-(NSString *)androidAppUrl;
-(NSString *)appIconUrl;
-(id)initWithAppName:(id)arg1 iosAppId:(id)arg2 androidAppUrl:(id)arg3 appIconUrl:(id)arg4 ;
-(id)initWithProtoBinary:(id)arg1 ;
-(id)initWithJSONDictionary:(id)arg1 ;
-(id)initWithProtoBuf:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)appName;
-(id)toDictionary;
@end

