/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:55 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SOJUScannableServletKhaleesiConfResponse.h>
@class NSNumber, NSString;


@protocol SOJUScannableServletKhaleesiConfResponse <NSObject,NSCoding,NSCopying>
@property (nonatomic,copy,readonly) NSNumber * enableFrontFacing; 
@property (nonatomic,copy,readonly) NSNumber * enableAndroidPassive; 
@property (nonatomic,copy,readonly) NSNumber * androidPassiveOffset; 
@property (nonatomic,copy,readonly) NSNumber * rollingWindowLength; 
@property (nonatomic,copy,readonly) NSNumber * sojuInitialStartDelay; 
@property (nonatomic,copy,readonly) NSNumber * sendInterval; 
@property (nonatomic,copy,readonly) NSNumber * sendOnFinish; 
@property (nonatomic,copy,readonly) NSNumber * minVolumeThreshold; 
@property (nonatomic,copy,readonly) NSNumber * enableKhaleesi; 
@property (nonatomic,copy,readonly) NSString * khaleesiToken; 
@property (nonatomic,copy,readonly) NSNumber * artistListFetchDelaySec; 
@property (nonatomic,copy,readonly) NSNumber * enableTopSnap; 
@required
-(NSNumber *)enableFrontFacing;
-(NSNumber *)enableAndroidPassive;
-(NSNumber *)androidPassiveOffset;
-(NSNumber *)rollingWindowLength;
-(NSNumber *)sojuInitialStartDelay;
-(NSNumber *)sendInterval;
-(NSNumber *)sendOnFinish;
-(NSNumber *)minVolumeThreshold;
-(NSNumber *)enableKhaleesi;
-(NSString *)khaleesiToken;
-(NSNumber *)artistListFetchDelaySec;
-(NSNumber *)enableTopSnap;

@end


@class NSNumber, NSString;

@interface SOJUScannableServletKhaleesiConfResponse : NSObject <SOJUScannableServletKhaleesiConfResponse> {

	NSNumber* _enableFrontFacing;
	NSNumber* _enableAndroidPassive;
	NSNumber* _androidPassiveOffset;
	NSNumber* _rollingWindowLength;
	NSNumber* _sojuInitialStartDelay;
	NSNumber* _sendInterval;
	NSNumber* _sendOnFinish;
	NSNumber* _minVolumeThreshold;
	NSNumber* _enableKhaleesi;
	NSString* _khaleesiToken;
	NSNumber* _artistListFetchDelaySec;
	NSNumber* _enableTopSnap;

}

@property (nonatomic,copy,readonly) NSNumber * enableFrontFacing;                    //@synthesize enableFrontFacing=_enableFrontFacing - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * enableAndroidPassive;                 //@synthesize enableAndroidPassive=_enableAndroidPassive - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * androidPassiveOffset;                 //@synthesize androidPassiveOffset=_androidPassiveOffset - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * rollingWindowLength;                  //@synthesize rollingWindowLength=_rollingWindowLength - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * sojuInitialStartDelay;                //@synthesize sojuInitialStartDelay=_sojuInitialStartDelay - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * sendInterval;                         //@synthesize sendInterval=_sendInterval - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * sendOnFinish;                         //@synthesize sendOnFinish=_sendOnFinish - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * minVolumeThreshold;                   //@synthesize minVolumeThreshold=_minVolumeThreshold - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * enableKhaleesi;                       //@synthesize enableKhaleesi=_enableKhaleesi - In the implementation block
@property (nonatomic,copy,readonly) NSString * khaleesiToken;                        //@synthesize khaleesiToken=_khaleesiToken - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * artistListFetchDelaySec;              //@synthesize artistListFetchDelaySec=_artistListFetchDelaySec - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * enableTopSnap;                        //@synthesize enableTopSnap=_enableTopSnap - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)fasterCodingVersion;
+(unsigned long long*)fasterCodingKeys;
+(BOOL)canInitFromProto;
-(BOOL)preferFasterCoding;
-(void)encodeWithFasterCoder:(id)arg1 ;
-(void)decodeWithFasterDecoder:(id)arg1 ;
-(void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2 ;
-(id)toJson;
-(BOOL)enableFrontFacingValue;
-(BOOL)enableAndroidPassiveValue;
-(double)androidPassiveOffsetValue;
-(double)rollingWindowLengthValue;
-(double)sojuInitialStartDelayValue;
-(double)sendIntervalValue;
-(BOOL)sendOnFinishValue;
-(double)minVolumeThresholdValue;
-(BOOL)enableKhaleesiValue;
-(double)artistListFetchDelaySecValue;
-(BOOL)enableTopSnapValue;
-(NSNumber *)enableFrontFacing;
-(NSNumber *)enableAndroidPassive;
-(NSNumber *)androidPassiveOffset;
-(NSNumber *)rollingWindowLength;
-(NSNumber *)sojuInitialStartDelay;
-(NSNumber *)sendInterval;
-(NSNumber *)sendOnFinish;
-(NSNumber *)minVolumeThreshold;
-(NSNumber *)enableKhaleesi;
-(NSString *)khaleesiToken;
-(NSNumber *)artistListFetchDelaySec;
-(NSNumber *)enableTopSnap;
-(id)initWithEnableFrontFacing:(id)arg1 enableAndroidPassive:(id)arg2 androidPassiveOffset:(id)arg3 rollingWindowLength:(id)arg4 sojuInitialStartDelay:(id)arg5 sendInterval:(id)arg6 sendOnFinish:(id)arg7 minVolumeThreshold:(id)arg8 enableKhaleesi:(id)arg9 khaleesiToken:(id)arg10 artistListFetchDelaySec:(id)arg11 enableTopSnap:(id)arg12 ;
-(id)initWithJSONDictionary:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)toDictionary;
@end

