/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:57 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SOJUUnlockablesSchedule.h>
@class NSString, NSNumber, NSArray;


@protocol SOJUUnlockablesSchedule <NSObject,NSCoding,NSCopying>
@property (nonatomic,copy,readonly) NSString * schedulingType; 
@property (nonatomic,copy,readonly) NSString * startDateTime; 
@property (nonatomic,copy,readonly) NSString * endDateTime; 
@property (nonatomic,copy,readonly) NSString * timezone; 
@property (nonatomic,copy,readonly) NSNumber * useLocalTimezone; 
@property (nonatomic,copy,readonly) NSString * repetitionFrequency; 
@property (nonatomic,copy,readonly) NSString * repetitionEndDateTime; 
@property (nonatomic,copy,readonly) NSString * weeklyFrequency; 
@property (nonatomic,copy,readonly) NSArray * repeatIntervals; 
@required
-(NSString *)schedulingType;
-(NSNumber *)useLocalTimezone;
-(NSString *)repetitionFrequency;
-(NSString *)repetitionEndDateTime;
-(NSString *)weeklyFrequency;
-(NSArray *)repeatIntervals;
-(NSString *)timezone;
-(NSString *)startDateTime;
-(NSString *)endDateTime;

@end


@class NSString, NSNumber, NSArray;

@interface SOJUUnlockablesSchedule : NSObject <SOJUUnlockablesSchedule> {

	NSString* _schedulingType;
	NSString* _startDateTime;
	NSString* _endDateTime;
	NSString* _timezone;
	NSNumber* _useLocalTimezone;
	NSString* _repetitionFrequency;
	NSString* _repetitionEndDateTime;
	NSString* _weeklyFrequency;
	NSArray* _repeatIntervals;

}

@property (nonatomic,copy,readonly) NSString * schedulingType;                     //@synthesize schedulingType=_schedulingType - In the implementation block
@property (nonatomic,copy,readonly) NSString * startDateTime;                      //@synthesize startDateTime=_startDateTime - In the implementation block
@property (nonatomic,copy,readonly) NSString * endDateTime;                        //@synthesize endDateTime=_endDateTime - In the implementation block
@property (nonatomic,copy,readonly) NSString * timezone;                           //@synthesize timezone=_timezone - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * useLocalTimezone;                   //@synthesize useLocalTimezone=_useLocalTimezone - In the implementation block
@property (nonatomic,copy,readonly) NSString * repetitionFrequency;                //@synthesize repetitionFrequency=_repetitionFrequency - In the implementation block
@property (nonatomic,copy,readonly) NSString * repetitionEndDateTime;              //@synthesize repetitionEndDateTime=_repetitionEndDateTime - In the implementation block
@property (nonatomic,copy,readonly) NSString * weeklyFrequency;                    //@synthesize weeklyFrequency=_weeklyFrequency - In the implementation block
@property (nonatomic,copy,readonly) NSArray * repeatIntervals;                     //@synthesize repeatIntervals=_repeatIntervals - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)fasterCodingVersion;
+(unsigned long long*)fasterCodingKeys;
+(BOOL)canInitFromProto;
-(BOOL)preferFasterCoding;
-(void)encodeWithFasterCoder:(id)arg1 ;
-(void)decodeWithFasterDecoder:(id)arg1 ;
-(void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2 ;
-(id)toJson;
-(long long)schedulingTypeEnum;
-(BOOL)useLocalTimezoneValue;
-(long long)repetitionFrequencyEnum;
-(NSString *)schedulingType;
-(NSNumber *)useLocalTimezone;
-(NSString *)repetitionFrequency;
-(NSString *)repetitionEndDateTime;
-(NSString *)weeklyFrequency;
-(NSArray *)repeatIntervals;
-(id)initWithSchedulingType:(id)arg1 startDateTime:(id)arg2 endDateTime:(id)arg3 timezone:(id)arg4 useLocalTimezone:(id)arg5 repetitionFrequency:(id)arg6 repetitionEndDateTime:(id)arg7 weeklyFrequency:(id)arg8 repeatIntervals:(id)arg9 ;
-(id)initWithProtoBinary:(id)arg1 ;
-(id)initWithJSONDictionary:(id)arg1 ;
-(id)initWithProtoBuf:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)timezone;
-(id)toDictionary;
-(NSString *)startDateTime;
-(NSString *)endDateTime;
@end

