/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:52 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/Snapchat-Structs.h>
#import <Snapchat/SOJUContextFilterSkyItem.h>
@class NSString, NSNumber;


@protocol SOJUContextFilterSkyItem <NSObject,NSCoding,NSCopying>
@property (nonatomic,copy,readonly) NSString * uuid; 
@property (nonatomic,copy,readonly) NSString * url; 
@property (nonatomic,copy,readonly) NSString * skyType; 
@property (nonatomic,copy,readonly) NSString * styleType; 
@property (nonatomic,copy,readonly) NSNumber * colorBrightness; 
@property (nonatomic,copy,readonly) NSString * replacementSkyUrl; 
@property (nonatomic,copy,readonly) NSString * blimpUrl; 
@required
-(NSString *)skyType;
-(NSString *)styleType;
-(NSNumber *)colorBrightness;
-(NSString *)replacementSkyUrl;
-(NSString *)blimpUrl;
-(NSString *)url;
-(NSString *)uuid;

@end


@class NSString, NSNumber;

@interface SOJUContextFilterSkyItem : NSObject <SOJUContextFilterSkyItem> {

	NSString* _uuid;
	NSString* _url;
	NSString* _skyType;
	NSString* _styleType;
	NSNumber* _colorBrightness;
	NSString* _replacementSkyUrl;
	NSString* _blimpUrl;

}

@property (nonatomic,copy,readonly) NSString * uuid;                           //@synthesize uuid=_uuid - In the implementation block
@property (nonatomic,copy,readonly) NSString * url;                            //@synthesize url=_url - In the implementation block
@property (nonatomic,copy,readonly) NSString * skyType;                        //@synthesize skyType=_skyType - In the implementation block
@property (nonatomic,copy,readonly) NSString * styleType;                      //@synthesize styleType=_styleType - In the implementation block
@property (nonatomic,copy,readonly) NSNumber * colorBrightness;                //@synthesize colorBrightness=_colorBrightness - In the implementation block
@property (nonatomic,copy,readonly) NSString * replacementSkyUrl;              //@synthesize replacementSkyUrl=_replacementSkyUrl - In the implementation block
@property (nonatomic,copy,readonly) NSString * blimpUrl;                       //@synthesize blimpUrl=_blimpUrl - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(unsigned long long)fasterCodingVersion;
+(unsigned long long*)fasterCodingKeys;
+(BOOL)canInitFromProto;
-(BOOL)preferFasterCoding;
-(void)encodeWithFasterCoder:(id)arg1 ;
-(void)decodeWithFasterDecoder:(id)arg1 ;
-(void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2 ;
-(id)toJson;
-(long long)skyTypeEnum;
-(long long)styleTypeEnum;
-(float)colorBrightnessValue;
-(NSString *)skyType;
-(NSString *)styleType;
-(NSNumber *)colorBrightness;
-(NSString *)replacementSkyUrl;
-(NSString *)blimpUrl;
-(id)initWithUuid:(id)arg1 url:(id)arg2 skyType:(id)arg3 styleType:(id)arg4 colorBrightness:(id)arg5 replacementSkyUrl:(id)arg6 blimpUrl:(id)arg7 ;
-(id)initWithProtoBinary:(id)arg1 ;
-(id)initWithJSONDictionary:(id)arg1 ;
-(id)initWithProtoBuf:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(NSString *)url;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)uuid;
-(id)toDictionary;
@end

