/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:52:07 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/SCBaseAPIClient.h>

@class SQAPICredentials;

@interface SQAPIClient : SCBaseAPIClient {

	BOOL _inSandbox;
	SQAPICredentials* _credentials;

}

@property (nonatomic,retain) SQAPICredentials * credentials;              //@synthesize credentials=_credentials - In the implementation block
@property (assign,nonatomic) BOOL inSandbox;                              //@synthesize inSandbox=_inSandbox - In the implementation block
+(void)resetSharedClientWithUrl;
+(void)updateSharedClient:(BOOL)arg1 ;
+(id)sharedClient;
-(id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3 ;
-(void)enqueueHTTPRequestOperation:(id)arg1 ;
-(id)initWithCredentials:(id)arg1 inSandbox:(BOOL)arg2 ;
-(void)clearCredentials;
-(void)setCredentials:(SQAPICredentials *)arg1 ;
-(void)setInSandbox:(BOOL)arg1 ;
-(BOOL)inSandbox;
-(void)registerOperationStateObserver:(id)arg1 ;
-(void)unregisterOperationStateObserver:(id)arg1 ;
-(id)getTransactionHistoryUrl;
-(void)setCredentials:(id)arg1 withExpiration:(id)arg2 forCustomer:(id)arg3 ;
-(BOOL)hasValidCredentialsForCustomer:(id)arg1 ;
-(void)handleLogout;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(SQAPICredentials *)credentials;
@end

