/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:44 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Snapchat/Snapchat-Structs.h>
@interface TCV3TalkCore : NSObject {

	Handle<std::__1::shared_ptr<talkcorev3::TalkCore>, std::__1::shared_ptr<talkcorev3::TalkCore> >* _cppRefHandle;

}
+(id)create:(id)arg1 delegate:(id)arg2 logger:(id)arg3 metricsReporter:(id)arg4 externalVideoService:(id)arg5 ;
-(id)initWithCpp:(const shared_ptr<talkcorev3::TalkCore>*)arg1 ;
-(id)createSession:(id)arg1 isTalkEnabled:(BOOL)arg2 isGroup:(BOOL)arg3 ;
-(void)processChatMessage:(id)arg1 ;
-(void)processChatConnectivityStatusChange:(BOOL)arg1 ;
-(void)injectNativeFrame:(long long)arg1 ;
-(id)getActiveConversations;
-(void)reachabilityChanged:(BOOL)arg1 ;
-(void)setProperty:(id)arg1 value:(id)arg2 ;
-(void)dispose;
@end

