/*
* This header is generated by classdump-dyld 1.0
* on Saturday, May 19, 2018 at 4:51:59 PM Eastern Daylight Time
* Operating System: Version 10.2 (Build 14C92)
* Image Source: /var/containers/Bundle/Application/7AB1B6B1-534C-4BF9-A7EB-BE2BD4C13043/Snapchat.app/Snapchat
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Snapchat/GPBMessage.h>

@class NSData, NSString;

@interface VLKNrfAuthResponse : GPBMessage

@property (assign,nonatomic) int origReqType; 
@property (assign,nonatomic) BOOL hasOrigReqType; 
@property (assign,nonatomic) BOOL success; 
@property (assign,nonatomic) BOOL hasSuccess; 
@property (nonatomic,copy) NSData * responseData; 
@property (assign,nonatomic) BOOL hasResponseData; 
@property (assign,nonatomic) BOOL hasMore; 
@property (assign,nonatomic) BOOL hasHasMore; 
@property (nonatomic,copy) NSString * errorMessage; 
@property (assign,nonatomic) BOOL hasErrorMessage; 
+(id)descriptor;
@end

